### ISSUE TITLE
Publish fails for large datasets on some s3 implementations

### ISSUE THREAD

**Issue by ErykKul** [IQSS/dataverse#10114]
**What steps does it take to reproduce the issue?**
When using s3 as storage, publish a large dataset where checksum verification takes longer than 30 minutes.

* When does this issue occur?
When publishing datasets with many large files where checksum validation takes longer than 30 minutes. This happens consistently on our installation with OpenStack s3 implementation.

* Which page(s) does it occurs on?
Dataset publish.

* What happens?
S3 closes the connection unexpectedly.

```
java.lang.RuntimeException: java.net.SocketException: Connection reset by peer (Write failed)
  at edu.harvard.iq.dataverse.util.FileUtil.calculateChecksum(FileUtil.java:742)
  at edu.harvard.iq.dataverse.util.FileUtil.validateDataFileChecksum(FileUtil.java:1902)
  at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.validateDataFiles(FinalizeDatasetPublicationCommand.java:325)
  at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.execute(FinalizeDatasetPublicationCommand.java:89)
  at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.execute(FinalizeDatasetPublicationCommand.java:50)
  at edu.harvard.iq.dataverse.EjbDataverseEngineInner.submit(EjbDataverseEngineInner.java:36)
```

* To whom does it occur (all users, curators, superusers)?
Users with publish permissions.

* What did you expect to happen?
Dataset gets published.

**Which version of Dataverse are you using?**
5.14, 6.0, current develop branch, ...

**Any related open or closed issues to this bug report?**
No.

**Screenshots:**

![image](https://github.com/IQSS/dataverse/assets/101262459/3dc61ad0-f27e-4f46-ae39-176c88f91973)

**Comment by ErykKul** [comment]
Link to the conversation on the Google Groups:
https://groups.google.com/g/dataverse-community/c/cQ3k8OvhHcI/m/vhDreGXTAAAJ
