### ISSUE TITLE
Trailing comma in the author name causes json-ld failure, kills the dataset page

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#10343]
I thought we had an issue for this, but can't find it immediately; but please close if this is a duplicate. 
A super embarrassing/annoying bug: 
Something in the json-ld/schema.org code is expecting a comma in the author string to indicate the "LastName, FirstName" notation; but fails miserably if there's a trailing comma, i.e. "SomeName,". As in
![Screen Shot 2024-02-26 at 12 46 24 PM](https://github.com/IQSS/dataverse/assets/737558/da83d396-2623-4494-8627-ec8267a4c401)

The dataset page uses the json-ld fragment in the headers and fails catastrophically when the record cannot be exported: 
![Screen Shot 2024-02-26 at 12 33 39 PM](https://github.com/IQSS/dataverse/assets/737558/8a3c4940-4631-42ef-b733-c6c70c3400a2)

Should be trivial to fix, I'm assuming. (in both places, ideally) 
(A quick workaround for the page failure is to place an empty `export_schema.org.cached` in to the dataset directory/s3 folder)

**Comment by laulandn** [comment]
This bug affected us too.  We are running 6.1 build "6.1_20240130", which predates the fixes mentioned above, and couldn't patch without rebuilding or upgrading, which we only do on a bi-yearly schedule.  So, to get around it I edited the offending metadata by hand.  But in the interests of information sharing, I was asked to post here.

Below is a partial, and truncated, stack trace when the problem occurred:

Error Rendering View[/dataset.xhtml]
jakarta.el.ELException: /dataset.xhtml @73,70 value="#{DatasetPage.jsonLd}": java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:77)
at jakarta.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:207)
at jakarta.faces.component.ComponentStateHelper.eval([ComponentStateHelper.java:176](http://componentstatehelper.java:176/))
... ...
 
Caused by: jakarta.el.ELException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at jakarta.el.BeanELResolver.getValue(BeanELResolver.java:345)
at com.sun.faces.el.DemuxCompositeELResolver._getValue([DemuxCompositeELResolver.java:139](http://demuxcompositeelresolver.java:139/))
... ... 

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at edu.harvard.iq.dataverse.util.PersonOrOrgUtil.getPersonOrOrganization(PersonOrOrgUtil.java:126)
at [edu.harvard.iq](http://edu.harvard.iq/).dataverse.DatasetVersion.getJsonLd([DatasetVersion.java:1851](http://datasetversion.java:1851/))
... ...
 
StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at edu.harvard.iq.dataverse.util.PersonOrOrgUtil.getPersonOrOrganization(PersonOrOrgUtil.java:126)
at [edu.harvard.iq](http://edu.harvard.iq/).dataverse.DatasetVersion.getJsonLd(DatasetVersion.java:1851)
... ...
 
Error Rendering View[/500.xhtml]
jakarta.el.ELException: /resources/iqbs/messages.xhtml @45,66 rendered="#{facesContext.validationFailed}": java.lang.IllegalStateException
at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:77)
at jakarta.faces.component.ComponentStateHelper.eval([ComponentStateHelper.java:189](http://componentstatehelper.java:189/))
... ...
 
Caused by: jakarta.el.ELException: java.lang.IllegalStateException
at jakarta.el.BeanELResolver.getValue(BeanELResolver.java:345)
at com.sun.faces.el.DemuxCompositeELResolver._getValue([DemuxCompositeELResolver.java:139](http://demuxcompositeelresolver.java:139/))
... ...
 
Caused by: java.lang.IllegalStateException
at com.sun.faces.context.FacesContextImpl.assertNotReleased(FacesContextImpl.java:642)
at com.sun.faces.context.FacesContextImpl.isValidationFailed([FacesContextImpl.java:626](http://facescontextimpl.java:626/))
... ...
 
Servlet.service() for servlet Faces Servlet threw exception
java.lang.IllegalStateException
at com.sun.faces.context.FacesContextImpl.assertNotReleased(FacesContextImpl.java:642)
at com.sun.faces.context.FacesContextImpl.isValidationFailed([FacesContextImpl.java:626](http://facescontextimpl.java:626/))
... ...
 
org.apache.catalina.core.StandardHostValve@78a6f0d1: Exception Processing ErrorPage[errorCode=500, location=/500.xhtml]
jakarta.servlet.ServletException
at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:709)
at jakarta.faces.webapp.FacesServlet.service([FacesServlet.java:449](http://facesservlet.java:449/))
... ...
 
Caused by: java.lang.IllegalStateException
at com.sun.faces.context.FacesContextImpl.assertNotReleased(FacesContextImpl.java:642)
at com.sun.faces.context.FacesContextImpl.isValidationFailed([FacesContextImpl.java:626](http://facescontextimpl.java:626/))
... ...
 
----- Root Cause -----
java.lang.IllegalStateException
at com.sun.faces.context.FacesContextImpl.assertNotReleased(FacesContextImpl.java:642)
at com.sun.faces.context.FacesContextImpl.isValidationFailed(FacesContextImpl.java:626)
at jakarta.faces.context.FacesContextWrapper.isValidationFailed([FacesContextWrapper.java:535](http://facescontextwrapper.java:535/))
... ...
