### ISSUE TITLE
Shapefiles: Map Thumbnail Image to Replace Default Icon 

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1143]
When a shapefile is uploaded to dataverse, display a default file icon related to maps/mapping.

Work to do:  Choose or create a default icon

Note: Once a data file is mapped, the default icon will be replaced with a thumbnail representation of the map.

/cc @mheppler @eaquigley

IQSS/geoconnect#68
![geoconnect-map_data-2014-1114_pdf](https://cloud.githubusercontent.com/assets/1036060/5097028/1f9ddff0-6f45-11e4-9477-08e9621a86ab.png)

**Comment by mheppler** [comment]
Rebranded this ticket to be specifically about the map thumbnail image since that is what a majority of this about. Another ticket exists (#1178) for the default icons of all files.

**Comment by landreev** [comment]
@raprasad , 
I've added code for showing thumbnails for worldmap files on the dataset page; if the .img file is available.
Could you please test it, with an actual map file and the worldmap app?
If it is working, please give me the ticket back - and I'll quickly wire it up to show thumbnails in the search cards as well.

**Comment by raprasad** [comment]
Switching back.  Works for logged in user.
Let me know when it works for guest and will retest.

\cc @landreev

**Comment by landreev** [comment]
@raprasad , 
These thumbnails should be showing on search cards as well now.

**Comment by raprasad** [comment]
moving to QA

/cc @kcondon

**Comment by kcondon** [comment]
Note for testing: the thumbnail only appears after you click Map it for first time and map is generated.
Currently blocked, waiting for issue #1423

**Comment by kcondon** [comment]
@raprasad 

This is not working: 
Initial map it keeps default icon, though preview exists. I think Raman said in a comment above that you need to style it after creation for the thumbnail to appear and there was a ticket for that. I styled it by changing color and now no icon appears at all, though the preview still exists.

Passing back for comment and whether we need different tickets.

I did see this error in the logs when I first created the map:

[2015-03-18T11:36:43.668-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.MapLayerMetadataServiceBean] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1426693003668] [levelValue: 800] [[
  retrieve url : http://worldmap.harvard.edu/download/wms/21928/png?layers=geonode:transportation_to_work_v24_zip_sfe&width=1205&bbox=-73.5332,41.2303,-69.8986,42.8881&service=WMS&format=image/png&srs=EPSG:4326&request=GetMap&height=550]]

[2015-03-18T11:36:43.668-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.MapLayerMetadataServiceBean] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1426693003668] [levelValue: 800] [[
  try to open InputStream]]

[2015-03-18T11:36:43.743-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.WorldMapRelatedData] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1426693003743] [levelValue: 1000] [[
  Failed to retrieve image from WorldMap server]]

[2015-03-18T11:36:43.745-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.WorldMapRelatedData] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1426693003745] [levelValue: 1000] [[
  
java.io.IOException: Server returned HTTP response code: 500 for URL: http://worldmap.harvard.edu/download/wms/21928/png?layers=geonode:transportation_to_work_v24_zip_sfe&width=1205&bbox=-73.5332,41.2303,-69.8986,42.8881&service=WMS&format=image/png&srs=EPSG:4326&request=GetMap&height=550
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.URL.openStream(URL.java:1037)
	at edu.harvard.iq.dataverse.MapLayerMetadataServiceBean.retrieveMapImageForIcon(MapLayerMetadataServiceBean.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:46)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor1237.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor1238.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy536.retrieveMapImageForIcon(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__MapLayerMetadataServiceBean__Intf____Bean__.retrieveMapImageForIcon(Unknown Source)
	at edu.harvard.iq.dataverse.api.WorldMapRelatedData.updateWorldMapLayerData(WorldMapRelatedData.java:616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at edu.harvard.iq.dataverse.api.ApiBlockingFilter.doFilter(ApiBlockingFilter.java:151)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
]]

**Comment by raprasad** [comment]
Please close. Same as #1479 -- copied the latest stack trace to #1479

**Comment by kcondon** [comment]
Discussed with Raman. There were two issues here and opened another ticket:
1. Thumbnail not appearing unless update style, with same stack trace, that is #1479 
2. Blank layer appearing when choose a classification that has lots of values that does not correspond to our data. That is a separate ticket. #1716

Closing.
