### ISSUE TITLE
Dataset Permissions for Dataset - Exception removing assigned role

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1372]
Removing the assigned role > Anyone with a Dataverse account > can be editor > throws exception on the log.  In the gui, the assigned role can't be removed.

server log: 
[2015-01-22T10:38:50.706-0500] [glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=48 _ThreadName=jk-connector(3)] [timeMillis: 1421941130706] [levelValue: 900] [[
  #{managePermissionsPage.removeRoleAssignment(roleAssignment.id)}: java.lang.ClassCastException: edu.harvard.iq.dataverse.Dataset cannot be cast to edu.harvard.iq.dataverse.Dataverse
javax.faces.FacesException: #{managePermissionsPage.removeRoleAssignment(roleAssignment.id)}: java.lang.ClassCastException: edu.harvard.iq.dataverse.Dataset cannot be cast to edu.harvard.iq.dataverse.Dataverse
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIData.broadcast(UIData.java:1108)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)

**Comment by esotiri** [comment]
resolved
