### ISSUE TITLE
Index: Seemingly random index error in logs: illegal character: http://0.0.0.0/

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1408]
I keep seeing this error in the logs on build but am not sure what's causing it:

[2015-02-03T12:47:22.978-0500] [glassfish 4.1] [WARNING] [AS-WEB-CORE-00230] [javax.enterprise.web.core] [tid: _ThreadID=29 _ThreadName=http-listener-1(5)] [timeMillis: 1422985642978] [levelValue: 900] [[
  The error-page /usr/local/glassfish4/glassfish/domains/domain1/applications/dataverse-4.0/faces/404.xhtml or /faces/404.xhtml does not exist]]

[2015-02-03T12:47:23.041-0500] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=29 _ThreadName=http-listener-1(5)] [timeMillis: 1422985643041] [levelValue: 900] [[
  StandardWrapperValve[default]: Servlet.service() for servlet default threw exception
java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 15: http://0.0.0.0/

	at org.ocpsoft.urlbuilder.util.Decoder.path(Decoder.java:19)
	at org.ocpsoft.urlbuilder.AddressBuilder.pathEncoded(AddressBuilder.java:147)
	at org.ocpsoft.urlbuilder.AddressBuilderPort.pathEncoded(AddressBuilderPort.java:54)
	at org.ocpsoft.rewrite.servlet.impl.BaseHttpRewrite.getInboundAddress(BaseHttpRewrite.java:88)
	at org.ocpsoft.rewrite.servlet.impl.HttpInboundRewriteImpl.getAddress(HttpInboundRewriteImpl.java:149)
	at org.ocpsoft.rewrite.faces.FacesRewriteLifecycleListener.beforeInboundLifecycle(FacesRewriteLifecycleListener.java:32)
	at org.ocpsoft.rewrite.faces.FacesRewriteLifecycleListener.beforeInboundLifecycle(FacesRewriteLifecycleListener.java:20)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:175)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 15: http://0.0.0.0/

	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at org.ocpsoft.urlbuilder.util.Decoder.path(Decoder.java:14)
	... 36 more
]]

**Comment by scolapasta** [comment]
@michbarsinai does this relate at all to any of the work you added with IP groups?

**Comment by michbarsinai** [comment]
This does not seem connected to the IP groups - some instances of this stack trace appear with no connection to the missing request metadata.

Also, note that there's no `edu.harvard....` classes in the stack trace - it's all internal stuff.

Assigning back to @scolapasta, this may need a more systems-based approach.

**Comment by eaquigley** [comment]
@kcondon please re test. thanks!

**Comment by kcondon** [comment]
I've grep'd production logs but did not see this error. Closing.
