### ISSUE TITLE
Deaccession Dataset: Upon deaccessioning dataset, user is shown 404 error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1918]
I deaccessioned a dataset that had only a single published version and saw a 404 error. This is related to the recent version state handling changes.

Saw some info in the server log:

[2015-04-08T13:11:19.838-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.DatasetVersionServiceBean] [tid: _ThreadID=411 _ThreadName=jk-connector(2)] [timeMillis: 1428513079838] [levelValue: 900] [[
  DatasetVersion not found: SELECT * FROM DatasetVersion dv INNER JOIN Dataset ds ON dv.dataset_id=ds.id AND ds.protocol= 'doi' AND ds.authority = '10.5072/FK2' AND ds.identifier = 'MURGZU' AND dv.versionstate = 'RELEASED' ORDER BY versionNumber DESC, minorVersionNumber DESC LIMIT 1;]]

[2015-04-08T13:11:19.839-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.DatasetVersionServiceBean] [tid: _ThreadID=411 _ThreadName=jk-connector(2)] [timeMillis: 1428513079839] [levelValue: 900] [[
  DatasetVersion not found: SELECT * FROM DatasetVersion dv INNER JOIN Dataset ds ON dv.dataset_id=ds.id AND ds.protocol= 'doi' AND ds.authority = '10.5072/FK2' AND ds.identifier = 'MURGZU' AND dv.versionstate = 'DRAFT' ORDER BY versionNumber DESC, minorVersionNumber DESC LIMIT 1;]]

**Comment by raprasad** [comment]
Fixed if deaccessioned version number is in url

**Comment by raprasad** [comment]
moved to qa

**Comment by kcondon** [comment]
Now throws exception in UI, see server log error:
[2015-04-08T20:19:05.004-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.DatasetVersionServiceBean] [tid: _ThreadID=131 _ThreadName=jk-connector(3)] [timeMillis: 1428538745004] [levelValue: 900] [[
  DatasetVersion not found: SELECT dv.* FROM DatasetVersion dv INNER JOIN Dataset ds ON dv.dataset_id=ds.id AND ds.protocol= 'doi' AND ds.authority = '10.5072/FK2' AND ds.identifier = 'MQMLWB' AND dv.versionstate = 'RELEASED' ORDER BY versionNumber DESC, minorVersionNumber DESC LIMIT 1;]]

[2015-04-08T20:19:05.005-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.DatasetVersionServiceBean] [tid: _ThreadID=131 _ThreadName=jk-connector(3)] [timeMillis: 1428538745005] [levelValue: 900] [[
  DatasetVersion not found: SELECT dv.* FROM DatasetVersion dv INNER JOIN Dataset ds ON dv.dataset_id=ds.id AND ds.protocol= 'doi' AND ds.authority = '10.5072/FK2' AND ds.identifier = 'MQMLWB' AND dv.versionstate = 'DRAFT' ORDER BY versionNumber DESC, minorVersionNumber DESC LIMIT 1;]]

[2015-04-08T20:19:05.006-0400] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=131 _ThreadName=jk-connector(3)] [timeMillis: 1428538745006] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB DatasetVersionServiceBean, method: public edu.harvard.iq.dataverse.DatasetVersionServiceBean$RetrieveDatasetVersionResponse edu.harvard.iq.dataverse.DatasetVersionServiceBean.retrieveDatasetVersionByPersistentId(java.lang.String,java.lang.String)]]

[2015-04-08T20:19:05.006-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=131 _ThreadName=jk-connector(3)] [timeMillis: 1428538745006] [levelValue: 900] [[
  
javax.ejb.EJBException
	at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy692.retrieveDatasetVersionByPersistentId(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__DatasetVersionServiceBean__Intf____Bean__.retrieveDatasetVersionByPersistentId(Unknown Source)
	at edu.harvard.iq.dataverse.DatasetPage.init(DatasetPage.java:967)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:289)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
	at javax.faces.component.UIViewAction.broadcast(UIViewAction.java:562)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DatasetVersionServiceBean.retrieveDatasetVersionByPersistentId(DatasetVersionServiceBean.java:552)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor1006.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 58 more
]]

**Comment by raprasad** [comment]
checking it.  @kcondon

**Comment by raprasad** [comment]
Back for QA.

##### The good:

  - The error was caused by a debug statement.  So it is now working

##### The bad (maybe):

   - If you have no other versions, you are brought to the page in the screenshot below—not the deaccession page—which does exist.

##### Question: What should be shown immediately after deaccessioning?

- Would this workflow be correct: 
	- (A) Deaccession -> Show deaccession page
- Currently it is following the Dataset page workflow:
	- (B) Deaccession ->  (1) looks for the latest release, (2) then a draft , and (3) then throws a 404

\cc @kcondon

**Comment by raprasad** [comment]
Updated logic after talking to @scolapasta:

With url specifying ```persistent id``` but NOT ```version```, search for dataset version in the following order:
-  latest released
- deaccessioned with highest version number first (even if not most recent deaccession)
- draft

**Comment by raprasad** [comment]
back to QA
