### ISSUE TITLE
SWORD: Can't use dcterms:type (kindOfData), JsonParseException via ImportGenericServiceBean.importXML

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2064]
First discovered by @jwhitney and @axfelix, if I try to use the `dcterms:type` field via SWORD I can't create the dataset and the get "JsonParseException: incorrect multiple   for field kindOfData" and the following stacktrace (I'm on commit 1d3c036).

Strangely, what the SWORD users sees is "Couldn't create dataset: Validation failed: Description Text is required. Author Name is required. Title is required."

We switched over to taking the XML and converting it to JSON in #973. I'm not very familiar with this code so I'll give this to @scolapasta for a first look.

```
[2015-04-21T13:23:52.760-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean] [tid: _ThreadID=98 _ThreadName=http-listener-2(4)] [timeMillis: 1429637032760] [levelValue: 1000] [[
  
edu.harvard.iq.dataverse.util.json.JsonParseException: incorrect multiple   for field kindOfData
	at edu.harvard.iq.dataverse.util.json.JsonParser.parseField(JsonParser.java:301)
	at edu.harvard.iq.dataverse.util.json.JsonParser.parseMetadataBlocks(JsonParser.java:232)
	at edu.harvard.iq.dataverse.util.json.JsonParser.parseDatasetVersion(JsonParser.java:212)
	at edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean.importXML(ImportGenericServiceBean.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:46)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor2081.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor2082.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy1470.importXML(Unknown Source)
	at edu.harvard.iq.dataverse.api.imports.__EJB31_Generated__ImportGenericServiceBean__Intf____Bean__.importXML(Unknown Source)
	at edu.harvard.iq.dataverse.api.datadeposit.CollectionDepositManagerImpl.createNew(CollectionDepositManagerImpl.java:109)
	at org.swordapp.server.CollectionAPI.post(CollectionAPI.java:165)
	at edu.harvard.iq.dataverse.api.datadeposit.SWORDv2CollectionServlet.doPost(SWORDv2CollectionServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
]]

[2015-04-21T13:23:53.348-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.api.datadeposit.CollectionDepositManagerImpl] [tid: _ThreadID=98 _ThreadName=http-listener-2(4)] [timeMillis: 1429637033348] [levelValue: 800] [[
  Validation failed: Description Text is required. Author Name is required. Title is required.]]
```

```
murphy:dataverse pdurbin$ cat /tmp/atom-entry-study.xml 
<?xml version="1.0"?>
<entry xmlns="http://www.w3.org/2005/Atom"
       xmlns:dcterms="http://purl.org/dc/terms/">
   <!-- some embedded metadata -->
   <dcterms:title>Roasting at Home</dcterms:title>
   <dcterms:creator>Peets, John</dcterms:creator>
   <dcterms:creator affiliation="Coffee Bean State University">Stumptown, Jane</dcterms:creator>
   <!-- Producer with financial or admin responsibility of the data -->
   <dcterms:publisher>Coffee Bean State University</dcterms:publisher>
   <!-- related publications -->
   <dcterms:isReferencedBy holdingsURI="http://dx.doi.org/10.1038/dvn333" agency="DOI" IDNo="10.1038/dvn333">Peets, J., &amp; Stumptown, J. (2013). Roasting at Home. New England Journal of Coffee, 3(1), 22-34.</dcterms:isReferencedBy>
   <!-- production date -->
   <dcterms:date>2013-07-11</dcterms:date>
   <!-- Other Identifier for the data in this study (or potentially global id if unused) -->
   <!--
   <dcterms:identifier>hdl:1XXZY.1/XYXZ</dcterms:identifier>
   -->
   <dcterms:description>Considerations before you start roasting your own coffee at home.</dcterms:description>
   <!-- keywords -->
   <dcterms:subject>coffee</dcterms:subject>
   <dcterms:subject>beverage</dcterms:subject>
   <dcterms:subject>caffeine</dcterms:subject>
   <!-- geographic coverage -->
   <dcterms:coverage>United States</dcterms:coverage>
   <dcterms:coverage>Canada</dcterms:coverage>
   <!-- kind of data -->
   <dcterms:type>aggregate data</dcterms:type>
   <!-- List of sources of the data collection-->
   <dcterms:source>Stumptown, Jane. 2011. Home Roasting. Coffeemill Press.</dcterms:source>
   <!-- license and restrictions -->
   <dcterms:license>NONE</dcterms:license>
   <dcterms:rights>Downloader will not use the Materials in any way prohibited by applicable laws.</dcterms:rights>
   <!-- related materials -->
   <dcterms:relation>Peets, John. 2010. Roasting Coffee at the Coffee Shop. Coffeemill Press</dcterms:relation>
   <dcterms:contributor type="Funder">CaffeineForAll</dcterms:contributor>
</entry>
```

`curl -s --insecure --data-binary @/tmp/atom-entry-study.xml -H 'Content-Type: application/atom+xml' -u 3c953434-6361-405c-95d8-ee7bc67080bb: https://localhost:8181/dvn/api/data-deposit/v1.1/swordv2/collection/dataverse/trees | xmllint -format -`

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<sword:error xmlns:sword="http://purl.org/net/sword/terms/" href="http://purl.org/net/sword/error/ErrorBadRequest">
  <atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title>
  <atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2015-04-21T13:23:53Z</atom:updated>
  <atom:generator xmlns:atom="http://www.w3.org/2005/Atom" uri="http://www.swordapp.org/" version="2.0"/>
  <sword:treatment>Processing failed</sword:treatment>
  <atom:summary xmlns:atom="http://www.w3.org/2005/Atom">Couldn't create dataset: Validation failed: Description Text is required. Author Name is required. Title is required.</atom:summary>
</sword:error>
```

**Comment by pdurbin** [comment]
Here's how the JSON looks:

        {
          "value": {
            "kindOfData": {
              "value": "aggregate data",
              "typeClass": "primitive",
              "multiple": false,
              "typeName": "kindOfData"
            }
          },
          "typeClass": "compound",
          "multiple": false,
          "typeName": "kindOfData"
        },

And here's some info on `kindOfData`:

```
$ curl -s http://localhost:8080/api/admin/datasetfield/kindOfData | jq .
{
  "data": {
    "isRequired": false,
    "solrFieldFacetable": "kindOfData_ss",
    "solrFieldSearchable": "kindOfData",
    "name": "kindOfData",
    "id": 64,
    "title": "Kind of Data",
    "metadataBlock": "citation",
    "fieldType": "TEXT",
    "allowsMultiples": true,
    "hasParent": false,
    "parentAllowsMultiples": "N/A (no parent)"
  },
  "status": "OK"
}
```

So it seems like `kindOfData` allows multiples but the JSON that's created set "multiple" to false.

**Comment by pdurbin** [comment]
If I print out "dataverseFieldName" in the "processXMLElement" method I can see "kindOfData" but that's about as far as I got:

https://github.com/IQSS/dataverse/blob/1d3c0363e305ffc836b705e0a1049eb3186ee937/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java#L191

@scolapasta maybe @landreev would be in a better position to take a look. I haven't worked on this XML processing code.

**Comment by pdurbin** [comment]
I updated `scripts/api/data-deposit/create-dataset` so we can easily reproduce the bug with the example XML we document at http://guides.dataverse.org/en/latest/api/sword.html

In that script you should only have to update the API token and the target dataverse.

```
murphy:dataverse pdurbin$ scripts/api/data-deposit/create-dataset
<?xml version="1.0" encoding="ISO-8859-1"?>
<sword:error xmlns:sword="http://purl.org/net/sword/terms/" href="http://purl.org/net/sword/error/ErrorBadRequest">
  <atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title>
  <atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2015-04-21T15:02:27Z</atom:updated>
  <atom:generator xmlns:atom="http://www.w3.org/2005/Atom" uri="http://www.swordapp.org/" version="2.0"/>
  <sword:treatment>Processing failed</sword:treatment>
  <atom:summary xmlns:atom="http://www.w3.org/2005/Atom">Couldn't create dataset: Validation failed: Title is required. Author Name is required. Description Text is required.</atom:summary>
</sword:error>
```

**Comment by pdurbin** [comment]
I'm **not** saying that the change below is an appropriate fix but it **does** at least produce JSON that seems more correct and I'm able to create a dataset:

        {
          "value": [
            "aggregate data"
          ],
          "typeClass": "primitive",
          "multiple": true,
          "typeName": "kindOfData"
        },

```
murphy:dataverse pdurbin$ git diff -U6
diff --git a/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java b/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
index 0c7d787..0c57817 100644
--- a/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
+++ b/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
@@ -272,13 +272,13 @@ public class ImportGenericServiceBean {
     private FieldDTO makeDTO(DatasetFieldType dataverseFieldType, FieldDTO value, String dataverseFieldName) {
         if (dataverseFieldType.isAllowMultiples()){
             if(dataverseFieldType.isCompound()){
                 value = FieldDTO.createMultipleCompoundFieldDTO(dataverseFieldName, value);
             }
             else {
-                value = FieldDTO.createCompoundFieldDTO(dataverseFieldName, value);
+                value = FieldDTO.createMultiplePrimitiveFieldDTO(dataverseFieldName, Arrays.asList(value.getSinglePrimitive()));
             }
             if (dataverseFieldType.isChild()) {
                 DatasetFieldType parentDatasetFieldType = dataverseFieldType.getParentDatasetFieldType();
                 if (parentDatasetFieldType.isAllowMultiples()) {
                     value = FieldDTO.createMultipleCompoundFieldDTO(parentDatasetFieldType.getName(), value);
```

**Comment by pdurbin** [comment]
@scolapasta I just reviewed my fix at 6c22947 (in a new branch) with @ekraffmiller and she thinks it looks good. Basically, the code was calling createCompoundFieldDTO when the field was already established to be **not** compound. You said you'd like @rtreacy to take a look since it's his code so I'll give this ticket to him. It's a one-line change so I hope we can get this is 4.0.1. Otherwise OJS (@jwhitney and @axfelix) will have to patch their code, which we'd like to avoid.

**Comment by rtreacy** [comment]
Looks right

**Comment by pdurbin** [comment]
@scolapasta when would you like this fix to land? This week? 4.0.1?

**Comment by pdurbin** [comment]
I merged this fix into master. I recommend testing with this file:

https://github.com/IQSS/dataverse/blob/master/doc/sphinx-guides/source/api/sword-atom-entry.xml

I deployed the latest code to https://apitest.dataverse.org if @axfelix or @jwhitney would like to test.

Moving to QA.

**Comment by axfelix** [comment]
Tested and working on apitest. Thanks, folks!

**Comment by kcondon** [comment]
Confirmed fixed by user, closing
