### ISSUE TITLE
Server log: In production we are seeing dozens of log files per day all filled with the same atmosphere error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2406]
This is causing a real maintenance issue with the partition filling up with useless logging info:

**Comment by bencomp** [comment]
Sounds like a configuration issue to me, unless the "atmosphere error" is thrown by the application unnecessarily. Could you elaborate for your fellow sysadmins?

**Comment by kcondon** [comment]
@bencomp Ben, there was a small config change with how apache uses atmosphere to talk to glassfish. The app works with or without this change but I believe it was intended to improve the asynch page updates for ingest. @landreev would have the details and I believe there is a ticket #1017 where he discusses it. It has not officially become part of the Installation Guide yet since it was experimental.

Here is an example of the server log error. It does not happen all the time but tends to create server log "storms":

[2015-07-28T10:00:43.934-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=51 _ThreadName=http-listener-2(2)] [timeMillis: 1438092043934] [levelValue: 900] [[
  StandardWrapperValve[Push Servlet]: Servlet.service() for servlet Push Servlet threw exception
java.lang.IllegalStateException: Request is within the scope of a filter or servlet that does not support asynchronous operations
        at org.apache.catalina.connector.Request.startAsync(Request.java:4257)
        at org.apache.catalina.connector.Request.startAsync(Request.java:4234)
        at org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:1044)
        at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:464)
        at org.atmosphere.cpr.AtmosphereRequest.startAsync(AtmosphereRequest.java:526)
        at org.atmosphere.container.Servlet30CometSupport.suspend(Servlet30CometSupport.java:129)
        at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:104)
        at org.atmosphere.container.GlassFishServ30WebSocketSupport.service(GlassFishServ30WebSocketSupport.java:62)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1699)
        at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:201)
        at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:187)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:745)
]]

**Comment by landreev** [comment]
@kcondon 
Kevin, 
Can I just pass this to you/put this in QA, so that you could close it, w/out assigning it to any release/milestone? 

The issue above - tons of junk in the log files - was fixed last fall. It was traced to something specific to our production - Benson's rewrite filters in the web.xml (somehow) broke the requirement for having async enabled on every filter in the chain. (googling the exception above will find more info on this, in case anyone is curios). 
So it was fixed by moving the rewrite filters out of the Dataverse web.xml and into the Apache configuration. 

It is all moot point by now however, since as of 4.2.3 we are not using atmosphere at all; as it was replaced with some simpler javascript solution on the dataset page.
