### ISSUE TITLE
Solr: Error in server log associated with server instability: No enum constant org.apache.solr.client.solrj.SolrQuery.ORDER.Referrer

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2600]
We've seen various enum errors in server.log: No enum constant

[2015-09-28T04:45:11.239-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.web.core] [tid: _ThreadID=252 _ThreadName=jk-connector(7)] [timeMillis: 1443429911239] [levelValue: 900] [[
  Servlet.service() for servlet Faces Servlet threw exception
java.lang.IllegalArgumentException: No enum constant org.apache.solr.client.solrj.SolrQuery.ORDER.Referrer
        at java.lang.Enum.valueOf(Enum.java:236)
        at org.apache.solr.client.solrj.SolrQuery$ORDER.valueOf(SolrQuery.java:45)
        at org.apache.solr.client.solrj.SolrQuery$SortClause.<init>(SolrQuery.java:1072)
        at edu.harvard.iq.dataverse.search.SearchServiceBean.search(SearchServiceBean.java:120)
        at sun.reflect.GeneratedMethodAccessor703.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy316.search(Unknown Source)
        at edu.harvard.iq.dataverse.search.__EJB31_Generated__SearchServiceBean__Intf____Bean__.search(Unknown Source)
        at edu.harvard.iq.dataverse.search.SearchIncludeFragment.search(SearchIncludeFragment.java:290)
        at edu.harvard.iq.dataverse.search.SearchIncludeFragment.search(SearchIncludeFragment.java:182)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
        at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
        at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
        at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
        at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
        at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
        at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)

**Comment by pdurbin** [comment]
Per [2600-grep-c.txt](https://github.com/IQSS/dataverse/files/3864/2600-grep-c.txt) these errors on 2015-09-02, well before the 4.2 deployment. I'm not sure of the cause but here is a full stack trace (line numbers from d6443eb ): [2600-full-stackstace-d6443eb.txt](https://github.com/IQSS/dataverse/files/3869/2600-full-stackstace-d6443eb.txt)

**Comment by pdurbin** [comment]
This is easy to reproduce. I can get `java.lang.IllegalArgumentException: No enum constant org.apache.solr.client.solrj.SolrQuery.ORDER.foobar` to show up in my logs by hitting <http://localhost:8080/?order=foobar>

**Comment by pdurbin** [comment]
We discussed this issue today in the context of server instability but I think it's a red herring. They're probably unrelated. However, it adds a lot of noise to the logs and we want to prevent users from seeing exceptions when they hack on our URLs so I pushed a fix in e6df62a with some guidance from @scolapasta on using an enum as a JSF view parameter. Passing to QA.

**Comment by kcondon** [comment]
Errors are suppressed both in UI and API as indicated. Closing.
