### ISSUE TITLE
Ingest of CSV (without header row) fails because of database column size limit

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2626]
I noticed a red triangle and exclamation point in our test environment. When hovering over it, it says that the ingest succeeded, but failed to put the data in the database.

The logs show that the root cause is a 255 character limit on a column. I don't expect that values in a CSV file are always at most 255 characters, so this limit should be removed.

(Perhaps not relevant to this issue, but recurring messages in the logs are related to Weld as included below.)

```
[2015-10-05T13:52:29.275+0200] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=59 _ThreadName=p: thread-pool-1; w: 1] [timeMillis: 1444045949275] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB IngestServiceBean, method: public boolean edu.harvard.iq.dataverse.ingest.IngestServiceBean.ingestAsTabular(java.lang.Long)]]

[2015-10-05T13:52:29.275+0200] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=59 _ThreadName=p: thread-pool-1; w: 1] [timeMillis: 1444045949275] [levelValue: 900] [[

javax.ejb.EJBException: Transaction aborted
    at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:725)
    at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
    at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
    at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
    at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
    at com.sun.proxy.$Proxy295.ingestAsTabular(Unknown Source)
    at edu.harvard.iq.dataverse.ingest.__EJB31_Generated__IngestServiceBean__Intf____Bean__.ingestAsTabular(Unknown Source)
    at edu.harvard.iq.dataverse.ingest.IngestMessageBean.onMessage(IngestMessageBean.java:88)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
    at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
    at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
    at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
    at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
    at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
    at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
    at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
    at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
    at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
    at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
    at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
    at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
    at org.glassfish.ejb.mdb.MessageBeanContainer.deliverMessage(MessageBeanContainer.java:1219)
    at org.glassfish.ejb.mdb.MessageBeanListenerImpl.deliverMessage(MessageBeanListenerImpl.java:81)
    at com.sun.enterprise.connectors.inbound.MessageEndpointInvocationHandler.invoke(MessageEndpointInvocationHandler.java:171)
    at com.sun.proxy.$Proxy429.onMessage(Unknown Source)
    at com.sun.messaging.jms.ra.OnMessageRunner.run(OnMessageRunner.java:283)
    at com.sun.enterprise.connectors.work.OneWork.doWork(OneWork.java:107)
    at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:497)
    at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:540)
Caused by: javax.transaction.RollbackException: Transaction marked for rollback.
    at com.sun.enterprise.transaction.JavaEETransactionImpl.commit(JavaEETransactionImpl.java:490)
    at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.commit(JavaEETransactionManagerSimplified.java:854)
    at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:719)
    ... 37 more
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
Error Code: 0
Call: INSERT INTO DATAVARIABLE (FILEENDPOSITION, FILEORDER, FILESTARTPOSITION, FORMAT, FORMATCATEGORY, INTERVAL, LABEL, NAME, NUMBEROFDECIMALPOINTS, ORDEREDFACTOR, RECORDSEGMENTNUMBER, TYPE, UNF, UNIVERSE, WEIGHTED, DATATABLE_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    bind => [16 parameters bound]
Query: InsertObjectQuery(edu.harvard.iq.dataverse.DataVariable[ id=null ])
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl$1.handleException(EntityManagerSetupImpl.java:696)
    at org.eclipse.persistence.transaction.AbstractSynchronizationListener.handleException(AbstractSynchronizationListener.java:275)
    at org.eclipse.persistence.transaction.AbstractSynchronizationListener.beforeCompletion(AbstractSynchronizationListener.java:170)
    at org.eclipse.persistence.transaction.JTASynchronizationListener.beforeCompletion(JTASynchronizationListener.java:68)
    at com.sun.enterprise.transaction.JavaEETransactionImpl.commit(JavaEETransactionImpl.java:452)
    ... 39 more
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
Error Code: 0
Call: INSERT INTO DATAVARIABLE (FILEENDPOSITION, FILEORDER, FILESTARTPOSITION, FORMAT, FORMATCATEGORY, INTERVAL, LABEL, NAME, NUMBEROFDECIMALPOINTS, ORDEREDFACTOR, RECORDSEGMENTNUMBER, TYPE, UNF, UNIVERSE, WEIGHTED, DATATABLE_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    bind => [16 parameters bound]
Query: InsertObjectQuery(edu.harvard.iq.dataverse.DataVariable[ id=null ])
    at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1611)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:962)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:631)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2002)
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:377)
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165)
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180)
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489)
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80)
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90)
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301)
    at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58)
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
    at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798)
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108)
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1786)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1737)
    at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:226)
    at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsForClassWithChangeSet(CommitManager.java:193)
    at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:138)
    at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4207)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1531)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.issueSQLbeforeCompletion(UnitOfWorkImpl.java:3168)
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.issueSQLbeforeCompletion(RepeatableWriteUnitOfWork.java:352)
    at org.eclipse.persistence.transaction.AbstractSynchronizationListener.beforeCompletion(AbstractSynchronizationListener.java:158)
    ... 41 more
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:332)
    at sun.reflect.GeneratedMethodAccessor847.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.postgresql.ds.jdbc23.AbstractJdbc23PooledConnection$StatementHandler.invoke(AbstractJdbc23PooledConnection.java:453)
    at com.sun.proxy.$Proxy377.executeUpdate(Unknown Source)
    at com.sun.gjc.spi.base.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:125)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890)
    ... 73 more
]]

[2015-10-05T13:52:29.276+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.ingest.IngestMessageBean] [tid: _ThreadID=59 _ThreadName=p: thread-pool-1; w: 1] [timeMillis: 1444045949276] [levelValue: 800] [[
  Unknown exception occurred  during ingest (supressed stack trace); re-setting ingest status.]]

[2015-10-05T13:52:29.276+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.ingest.IngestMessageBean] [tid: _ThreadID=59 _ThreadName=p: thread-pool-1; w: 1] [timeMillis: 1444045949276] [levelValue: 800] [[
  looking up datafile for id 6]]

[2015-10-05T13:52:29.355+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.ingest.IngestMessageBean] [tid: _ThreadID=59 _ThreadName=p: thread-pool-1; w: 1] [timeMillis: 1444045949355] [levelValue: 800] [[
  trying to save datafile 6]]

[2015-10-05T13:52:29.474+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.ingest.IngestMessageBean] [tid: _ThreadID=59 _ThreadName=p: thread-pool-1; w: 1] [timeMillis: 1444045949474] [levelValue: 800] [[
  attempting to remove dataset lock for dataset 5]]

[2015-10-05T13:52:31.282+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444045951282] [levelValue: 900] [[
  WELD-000714: HttpContextLifecycle guard leak detected. The Servlet container is not fully compliant. The value was 1]]

[2015-10-05T13:52:31.283+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Context] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444045951283] [levelValue: 900] [[
  WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpRequestContextImpl association: com.sun.enterprise.web.pwc.connector.coyote.PwcCoyoteRequest@5c55435d]]

[2015-10-05T13:52:31.284+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Context] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444045951284] [levelValue: 900] [[
  WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpSessionContextImpl association: com.sun.enterprise.web.pwc.connector.coyote.PwcCoyoteRequest@5c55435d]]

[2015-10-05T13:52:31.289+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444045951289] [levelValue: 900] [[
  WELD-000715: HttpContextLifecycle guard not set. The Servlet container is not fully compliant.]]

[2015-10-05T13:52:49.611+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444045969611] [levelValue: 900] [[
  WELD-000714: HttpContextLifecycle guard leak detected. The Servlet container is not fully compliant. The value was 1]]

[2015-10-05T13:52:49.611+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Context] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444045969611] [levelValue: 900] [[
  WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpRequestContextImpl association: com.sun.enterprise.web.pwc.connector.coyote.PwcCoyoteRequest@348ad621]]

[2015-10-05T13:52:49.612+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Context] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444045969612] [levelValue: 900] [[
  WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpSessionContextImpl association: com.sun.enterprise.web.pwc.connector.coyote.PwcCoyoteRequest@348ad621]]

[2015-10-05T13:52:49.613+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444045969613] [levelValue: 900] [[
  WELD-000715: HttpContextLifecycle guard not set. The Servlet container is not fully compliant.]]

[2015-10-05T13:53:18.107+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=49 _ThreadName=jk-connector(3)] [timeMillis: 1444045998107] [levelValue: 900] [[
  WELD-000714: HttpContextLifecycle guard leak detected. The Servlet container is not fully compliant. The value was 1]]

[2015-10-05T13:53:18.108+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Context] [tid: _ThreadID=49 _ThreadName=jk-connector(3)] [timeMillis: 1444045998108] [levelValue: 900] [[
  WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpRequestContextImpl association: com.sun.enterprise.web.pwc.connector.coyote.PwcCoyoteRequest@19bba9d5]]

[2015-10-05T13:53:18.108+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Context] [tid: _ThreadID=49 _ThreadName=jk-connector(3)] [timeMillis: 1444045998108] [levelValue: 900] [[
  WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpSessionContextImpl association: com.sun.enterprise.web.pwc.connector.coyote.PwcCoyoteRequest@19bba9d5]]

[2015-10-05T13:53:18.110+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=49 _ThreadName=jk-connector(3)] [timeMillis: 1444045998110] [levelValue: 900] [[
  WELD-000715: HttpContextLifecycle guard not set. The Servlet container is not fully compliant.]]

[2015-10-05T13:53:30.801+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444046010801] [levelValue: 900] [[
  WELD-000714: HttpContextLifecycle guard leak detected. The Servlet container is not fully compliant. The value was 1]]

[2015-10-05T13:53:30.801+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Context] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444046010801] [levelValue: 900] [[
  WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpRequestContextImpl association: com.sun.enterprise.web.pwc.connector.coyote.PwcCoyoteRequest@b177478]]

[2015-10-05T13:53:30.801+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Context] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444046010801] [levelValue: 900] [[
  WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpSessionContextImpl association: com.sun.enterprise.web.pwc.connector.coyote.PwcCoyoteRequest@b177478]]

[2015-10-05T13:53:30.803+0200] [glassfish 4.1] [WARN] [] [org.jboss.weld.Servlet] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1444046010803] [levelValue: 900] [[
  WELD-000715: HttpContextLifecycle guard not set. The Servlet container is not fully compliant.]]
```

**Comment by bencomp** [comment]
It appears that the CSV file has no header. Indeed at least one column contains long text; treating that as a header is bound to fail.

This is not to say that real headers will always have names that don't exceed 255 characters.

- do CSV files always need to have a header?
    - if not, should Dataverse provide substitute column (= variable) names?
    - if so, should Dataverse reject files without headers?
- do variable names have to be shorter than 256 characters?
    - if so, should Dataverse reject headers with names over 255 characters or shorten them?

**Comment by oscardssmith** [comment]
I think it is reasonable to require a header, as otherwise, there is no reliable way to tell.
Dataverse should reject csv's without headers.
Dataverse should not reject headers with names over 255 chars.

**Comment by pdurbin** [comment]
@oscardssmith I believe that during sprint planning @djbrooke ask you to do something this this issue. Combine it with #3767 maybe? I forget.

**Comment by oscardssmith** [comment]
Yeah, 3767 fix addresses this

**Comment by pdurbin** [comment]
@oscardssmith ah, and you've already added the "connects to" line to pull request #3930. Perfect. Thanks. Closing.
