### ISSUE TITLE
Edit File Metadata: Works but throws exception in server log.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2680]
When I edit file metadata on a dataset with more than one version, I see an error in the error log on loading the edit metadata page:

[2015-10-23T12:39:09.153-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=50 _ThreadName=jk-connector(4)] [timeMillis: 1445618349153] [levelValue: 900] [[
  /dataset.xhtml @339,105 rendered="#{!DatasetPage.workingVersion.deaccessioned and                                                   (!empty DatasetPage.datasetVersionUI.descriptionDisplay                                                  or !empty DatasetPage.datasetVersionUI.keywordDisplay                                                  or !empty DatasetPage.datasetVersionUI.subject.value                                                   or !empty DatasetPage.datasetVersionUI.relPublicationCitation                                                  or !empty DatasetPage.datasetVersionUI.notes.value)}": java.lang.NullPointerException
javax.el.ELException: /dataset.xhtml @339,105 rendered="#{!DatasetPage.workingVersion.deaccessioned and                                                   (!empty DatasetPage.datasetVersionUI.descriptionDisplay                                                  or !empty DatasetPage.datasetVersionUI.keywordDisplay                                                  or !empty DatasetPage.datasetVersionUI.subject.value                                                   or !empty DatasetPage.datasetVersionUI.relPublicationCitation                                                  or !empty DatasetPage.datasetVersionUI.notes.value)}": java.lang.NullPointerException
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:114)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
	at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:457)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1210)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1220)
	at javax.faces.component.UIForm.processDecodes(UIForm.java:225)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1220)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1220)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:929)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.el.ELException: java.lang.NullPointerException
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:368)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:140)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:204)
	at com.sun.el.parser.AstEmpty.getValue(AstEmpty.java:66)
	at com.sun.el.parser.AstNot.getValue(AstNot.java:63)
	at com.sun.el.parser.AstOr.getValue(AstOr.java:63)
	at com.sun.el.parser.AstOr.getValue(AstOr.java:58)
	at com.sun.el.parser.AstAnd.getValue(AstAnd.java:63)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
	... 48 more
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DatasetVersionUI.getRelPublicationCitation(DatasetVersionUI.java:238)
	at edu.harvard.iq.dataverse.DatasetVersionUI$Proxy$_$$_WeldClientProxy.getRelPublicationCitation(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor4598.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:363)
	... 60 more
]]

**Comment by pdurbin** [comment]
The line numbers are for v. 4.2.1 build 11-05d26ad

**Comment by pdurbin** [comment]
I can reproduce this on my laptop on commit e1f314c and [isseu2680stacktrace-e1f314c.txt](https://github.com/IQSS/dataverse/files/20906/isseu2680stacktrace-e1f314c.txt) is a complete stack trace.

The NullPointerException is being thrown because this.datasetRelPublications is null in DatasetVersionUI.java. Here's the code in context:

```
public String getRelPublicationCitation() {
    if (!this.datasetRelPublications.isEmpty()) {
        return this.getDatasetRelPublications().get(0).getText();
    } else {
        return "";
    }
}
```

Here's the line: https://github.com/IQSS/dataverse/blob/e1f314c3c7d59956673ad04a6eb2c66a9b942a94/src/main/java/edu/harvard/iq/dataverse/DatasetVersionUI.java#L238

I assume it's safe enough to add an additional null check but I'll check with @sekmiller first since he's the one who has worked in this file the most.

**Comment by pdurbin** [comment]
@sekmiller and I decided it was fine to add the additional null check for `datasetRelPublications` which I did in 0165b0c but now there's a different exception being thrown. I'm still on that commit and here's a stacktrace: [stacktrace-0165b0c.txt](https://github.com/IQSS/dataverse/files/21094/stacktrace-0165b0c.txt)

To summarize, it's saying

/filesFragment.xhtml @35,97 value="#{DatasetPage.showAccessPopup}": java.lang.NullPointerException
javax.el.ELException: /filesFragment.xhtml @35,97 value="#{DatasetPage.showAccessPopup}": java.lang.NullPointerException

and here's the NullPointerException:

Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DatasetPage.isShowAccessPopup(DatasetPage.java:2000)

Here's line 2000: https://github.com/IQSS/dataverse/blob/0165b0c966d626f8a1c8a125ddd2ce15d3c18c80/src/main/java/edu/harvard/iq/dataverse/DatasetPage.java#L2000

In the `for (FileMetadata fmd : workingVersion.getFileMetadatas()) {` loop the variable `workingVersion` is null and @sekmiller and I are not sure why. During this morning's meeting @landreev said he'd take an initial look so I'm giving this issue to him. Again, to reproduce this, I'm attempting to edit the metadata on a file in a draft dataset like this:

![screen shot 2015-10-26 at 1 51 48 pm](https://cloud.githubusercontent.com/assets/21006/10737470/c1c77402-7be8-11e5-9edb-8b986b988f8c.png)

**Comment by landreev** [comment]
@kcondon : 

To rehash what I was saying earlier: 
These errors were kind of irrelevant. Because they were all coming from the DatasetPage; and the DatasetPage has no business even trying to do anything/render anything at this point - as it is already redirecting to EditFilesPage. So it just looked like for some strange reason it was trying to render itself one more time. But it was in this half-baked state, as it was already shutting down. Hence no working Dataset version and all these NULL pointers. It started happening after Steve and Mike rebuilt the page not to use ajax for the file select checkboxes. (that was a good thing overall; but it introduced some challenges, as some things related to that redirect now have to be done on the xhtml side, and not on the bean side)

But it was still wasting some cycles/crapping in the logs, so I feel it was a good idea to fix it. 
Please retest. But please give me this ticket again when you're done with it; or remind me to update it - I want to let Mike know what I did, in case it helps elsewhere on the page. Just don't have time to explain this now.

**Comment by kcondon** [comment]
OK works, closing
