### ISSUE TITLE
Index: Index all halts due to bad data in email field, should report error and continue.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3190]
Index all halts due to bad data in the email field of the authenticateduser field. The email value is of the form: "email1@domain.org, email2@domain.org".

Index halts and apparently does not index any object at all since no indextime was updated. I believe a preferred behavior would be to index incrementally up to the failure and then log/report the problem and ideally skip over the failing item and continue but if not, at least index up until it reaches the bad data.

A side issue is why is this field being indexed and why is it failing with this new release when the data appears to have been there for a long time (account id is 1/2 way through list of accounts).

Update: There is a least one case of dataset contact email, a required field, being blank which may also halt index. The dataset id is: 52712

**Comment by kcondon** [comment]
Command line:
{"status":"ERROR","message":"javax.ejb.EJBTransactionRolledbackException javax.ejb.TransactionRolledbackLocalException Exception thrown from bean javax.persistence.PersistenceException javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:'preUpdate'. Please refer to embedded ConstraintViolations for details. javax.validation.ConstraintViolationException Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:'preUpdate'. Please refer to embedded ConstraintViolations for details.

Server log:
Caused by: javax.persistence.PersistenceException: javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Valid
ation on callback event:'preUpdate'. Please refer to embedded ConstraintViolations for details.
        at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:480)
        at edu.harvard.iq.dataverse.DatasetServiceBean.findAllOrSubset(DatasetServiceBean.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        ... 114 more
Caused by: javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:'preUpdate'. Please refer to embedded ConstraintViolations for details.
        at org.eclipse.persistence.internal.jpa.metadata.listeners.BeanValidationListener.validateOnCallbackEvent(BeanValidationListener.java:90)
        at org.eclipse.persistence.internal.jpa.metadata.listeners.BeanValidationListener.preUpdate(BeanValidationListener.java:72)
        at org.eclipse.persistence.descriptors.DescriptorEventManager.notifyListener(DescriptorEventManager.java:721)
        at org.eclipse.persistence.descriptors.DescriptorEventManager.notifyEJB30Listeners(DescriptorEventManager.java:691)
        at org.eclipse.persistence.descriptors.DescriptorEventManager.executeEvent(DescriptorEventManager.java:229)
        at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.calculateChanges(DeferredChangeDetectionPolicy.java:87)
        at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.calculateChangesForExistingObject(DeferredChangeDetectionPolicy.java:56)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:664)
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:438)
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:863)
        at org.eclipse.persistence.internal.jpa.QueryImpl.performPreQueryFlush(QueryImpl.java:963)
        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:207)
:

**Comment by sekmiller** [comment]
The fix applied does not address the issue of a failure due to a ConstraintViolationException, such as when an authenticated user with a role on one or more datasets has an invalid email address saved to the database (migration error?).

It does catch exceptions when the indexer is iterating through the dataverse and dataset lists for a given partition.  The indexing continues with the next dataverse or dataset and additional information is appended to the log - something like:

FAILURE indexing dataset 555 of 556 (id=1772 ) Exception info: javax.ejb.EJBException: javax.ejb.CreateException: Could not create stateless EJB

**Comment by scolapasta** [comment]
If we just putting this in the standard log, we're likely to miss it.

We probably want to create a log file specific for these OR possibly e-mail someone? (my concern with the e-mail is if every thing is failing, we wouldn't want to send 1000s of e-mails). 

Maybe one e-mail gets send if at least one failure happens? (with a message like "check the system log" but that would be enough to at least alert us)

**Comment by sekmiller** [comment]
Added a line on failures to the summary statistics at the end of the index process so if there are failures it will look something like this:

Info:   done iterating through all datasets
Info:   index all took 106046 milliseconds
Info:   There were index failures. 4 dataverse(s) and 6 dataset(s) failed to index. Please check the log for more information.
Info:   494 dataverses and 556 datasets indexed. index all took 106046 milliseconds. Solr index was not cleared before indexing.

**Comment by kcondon** [comment]
Indexall throws an exception at the end but otherwise works:
[2017-11-29T18:43:35.838-0500] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=146 _ThreadName=__ejb-thread-pool4] [timeMillis: 1511999015838] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB IndexAllServiceBean, method: public java.util.concurrent.Future edu.harvard.iq.dataverse.search.IndexAllServiceBean.indexAllOrSubset(long,long,boolean,boolean)]]

**Comment by sekmiller** [comment]
This "preUpdate" Constraint Validation is an indication that something like an invalid email address is present. Because of the nature of this error, it is very difficult to recover from. This type of error is not addressed in the fix.


javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:'preUpdate'. Please refer to embedded ConstraintViolations for details.

**Comment by pdurbin** [comment]
Related: #4340
