### ISSUE TITLE
dataset creation problem with role assignment

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3428]
Hello,

We've seen a few (but not a lot) errors in creating new datasets similar to:

[#|2016-10-25T10:02:15.688-0400|WARNING|glassfish 4.1|org.eclipse.persistence.session.file:/usr/local/glassfish4/glassfish/domains/domain1/applications/dataverse-4.5/WEB-INF/classes/_VDCNet-ejbPU|_ThreadID=50;_T
hreadName=jk-connector(4);_TimeMillis=1477404135688;_LevelValue=900;|
  Local Exception Stack: 
Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: null value in column "createdate" violates not-null constraint
  Detail: Failing row contains (7403864, DataFile, null, null, 2016-10-25 10:01:52.386, null, 2016-10-25 10:01:52.386, f, null, null, 7403861, null).
Error Code: 0
Call: INSERT INTO DVOBJECT (CREATEDATE, INDEXTIME, MODIFICATIONTIME, PERMISSIONINDEXTIME, PERMISSIONMODIFICATIONTIME, PREVIEWIMAGEAVAILABLE, PUBLICATIONDATE, CREATOR_ID, OWNER_ID, RELEASEUSER_ID, DTYPE) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [11 parameters bound]
Query: InsertObjectQuery([DataFile id:null name:null])
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1611)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:962)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:631)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2002)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:363)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489)
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80)
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301)
        at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1786)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1737)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:226)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsForClassWithChangeSet(CommitManager.java:193)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:138)
        at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4207)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithPreBuiltChangeSet(UnitOfWorkImpl.java:1587)
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:452)
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:863)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.flush(EntityManagerWrapper.java:437)
        at edu.harvard.iq.dataverse.DataverseRoleServiceBean.save(DataverseRoleServiceBean.java:65)
<snip>

seen by the end user as:

![createdatenull](https://cloud.githubusercontent.com/assets/12831666/19699381/1f4c945c-9ac1-11e6-8395-b034d1e86a31.jpg)

The problem appears to be around line 64 of https://github.com/IQSS/dataverse/blob/3a753cacb52eef009ae96fd89cf5ee1d193a8a9c/src/main/java/edu/harvard/iq/dataverse/DataverseRoleServiceBean.java

We at Odum are curious to know if you have seen these errors in Harvard's dataverse?

Thank you!
Donald

**Comment by pdurbin** [comment]
@donsizemore thanks for the bug report. @akio-sone indicated that you've seen this on v. 4.5 build 41-dc58ae1. Can you please try to reproduce the bug on https://demo.dataverse.org which is running v. 4.5.1 build 49-7e5e8c9? Also, please feel free to email the entire server.log to support@dataverse.org

This bug reminds me a bit of #2862 but maybe that's just me. I'm saying this because I see `DataFile` in the stacktrace. Files seem to be involved.

**Comment by donsizemore** [comment]
We've only seen rashes of these at two times: this morning just before Sophia's UNC Dataverse webinar, and exactly one week prior, oddly enough. We have a 4.5.1 host here unless you want us to trigger it specifically on demo.dataverse.org, but Akio and I imagine that this condition would take just enough system load and semi-random user activity that it might be difficult to trigger. I may script the creation of say 25 datasets through the API on a test box, but I think this may manifest only under moderately heavy user load.

**Comment by donsizemore** [comment]
I also meant to add that, in the case above, Thu-Mai was able to create a dataset in that same Dataverse, and then the end-user was able to create the same dataset (though I'm not sure if or how he reloaded the page for a new session). I'll poke some more on this end.

**Comment by pdurbin** [comment]
@donsizemore you're welcome to test on any 4.5.1 host. If you're running the host, you can see what's in server.log, of course. If you can reproduce it on the demo server, I can see it. 😄

**Comment by donsizemore** [comment]
A similar(?) error popped up this afternoon. Again, the user tried again and succeeded:

[#|2016-10-25T12:31:03.023-0400|SEVERE|glassfish 4.1|edu.harvard.iq.dataverse.ManagePermissionsPage|_ThreadID=48;_ThreadName=jk-connector(2);_TimeMillis=1477413063023;_LevelValue=1000;|
  Error assiging role: Command edu.harvard.iq.dataverse.engine.command.impl.AssignRoleCommand@44b2eebe failed: null
edu.harvard.iq.dataverse.engine.command.exception.CommandException: Command edu.harvard.iq.dataverse.engine.command.impl.AssignRoleCommand@44b2eebe failed: null
        at edu.harvard.iq.dataverse.EjbDataverseEngine.submit(EjbDataverseEngine.java:205)
        at sun.reflect.GeneratedMethodAccessor882.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy205.submit(Unknown Source)
        at edu.harvard.iq.dataverse.__EJB31_Generated__EjbDataverseEngine__Intf____Bean__.submit(Unknown Source)
        at edu.harvard.iq.dataverse.ManagePermissionsPage.assignRole(ManagePermissionsPage.java:402)
        at edu.harvard.iq.dataverse.ManagePermissionsPage.assignRole(ManagePermissionsPage.java:374)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
<snip>

Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unq_roleassignment_0"
  Detail: Key (assigneeidentifier, role_id, definitionpoint_id)=(@kpartlo, 1, 72) already exists.
Error Code: 0
Call: INSERT INTO ROLEASSIGNMENT (ASSIGNEEIDENTIFIER, PRIVATEURLTOKEN, DEFINITIONPOINT_ID, ROLE_ID) VALUES (?, ?, ?, ?)
        bind => [4 parameters bound]
Query: InsertObjectQuery(RoleAssignment{id=null, assignee=@kpartlo, role=DataverseRole{id=1, alias=admin}, definitionPoint=[Dataverse id:72 name:Carleton College]})
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:868)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.flush(EntityManagerWrapper.java:437)
        at edu.harvard.iq.dataverse.DataverseRoleServiceBean.save(DataverseRoleServiceBean.java:65)

and

Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unq_roleassignment_0"
  Detail: Key (assigneeidentifier, role_id, definitionpoint_id)=(@kpartlo, 1, 72) already exists.
Error Code: 0
Call: INSERT INTO ROLEASSIGNMENT (ASSIGNEEIDENTIFIER, PRIVATEURLTOKEN, DEFINITIONPOINT_ID, ROLE_ID) VALUES (?, ?, ?, ?)
        bind => [4 parameters bound]
Query: InsertObjectQuery(RoleAssignment{id=null, assignee=@kpartlo, role=DataverseRole{id=1, alias=admin}, definitionPoint=[Dataverse id:72 name:Carleton College]})
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)

Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unq_roleassignment_0"
  Detail: Key (assigneeidentifier, role_id, definitionpoint_id)=(@kpartlo, 1, 72) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:332)
        at sun.reflect.GeneratedMethodAccessor433.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.postgresql.ds.jdbc23.AbstractJdbc23PooledConnection$StatementHandler.invoke(AbstractJdbc23PooledConnection.java:453)
        at com.sun.proxy.$Proxy225.executeUpdate(Unknown Source)
        at com.sun.gjc.spi.base.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:125)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890)
        ... 154 more

**Comment by pdurbin** [comment]
@donsizemore huh. These sound like different bugs. Notice how different database tables are in play if you compare the "INSERT INTO" lines. What's most helpful is the steps to reliably reproduce the bugs.

**Comment by pdurbin** [comment]
@donsizemore thanks for passing along your server.log file in https://help.hmdc.harvard.edu/Ticket/Display.html?id=242907

For the `INSERT INTO DVOBJECT` error this is being called by `ctxt.roles().save(new RoleAssignment(savedDataset.getOwner().getDefaultContributorRole(), getRequest().getUser(), savedDataset, privateUrlToken));` at https://github.com/IQSS/dataverse/blob/v4.5/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetCommand.java#L179 which is being called by https://github.com/IQSS/dataverse/blob/v4.5/src/main/java/edu/harvard/iq/dataverse/DatasetPage.java#L2739

Just prior to the exception, you can see this in the logs: `ADDING FILE: Health and Lifestyle Annotated.pdf; for dataset: REDACTED`. I'm not sure what's causing the bug.

@donsizemore any luck replicating the bug on https://demo.dataverse.org or your server running Dataverse 4.5.1? Steps for how to reproduce this bug would be very welcome!

**Comment by pdurbin** [comment]
@donsizemore any news on this? Are you able to give us steps to reproduce the problem? Thanks!

**Comment by donsizemore** [comment]
@pdurbin no, we haven't been able to reproduce it, but we've seen a number of them on our production server, and apparently managed to trigger the condition once on a test server a few weeks ago (this could've been someone external testing shibboleth; the apache logs aren't archived back that far on the test server)

@akio-sone and i published a number of datasets simultaneously on the test server with edu.harvard.iq.dataverse.ingest.IngestServiceBean.level=FINE but didn't manage to trigger the bug...

I was curious if you all had seen similar errors in your production logs?

**Comment by pdurbin** [comment]
@donsizemore our production logs are split across three servers and there are number of security hoops to jump through to get at them. We should probably be using Splunk or something to make answering questions like this easier.

**Comment by djbrooke** [comment]
@pdurbin - your ears must have been burning. Last night, I sent an email to Harvard IT with a request to set up Splunk.

**Comment by pdurbin** [comment]
@djbrooke great! Please see the "Monitoring wishlist for dataverse.harvard.edu" at INC01464301.

**Comment by pdurbin** [comment]
@donsizemore any news on this one? I'm tempted to close it if we can't reproduce it. We can always open a fresh one in the future.

**Comment by donsizemore** [comment]
I haven't heard any more from our user base, and we're perilously close to upgrading to the current version of Dataverse. Let's close this one and we'll re-open if it re-appears. Thanks.

**Comment by pdurbin** [comment]
@donsizemore thanks!
