### ISSUE TITLE
Set expectations in Developer Guide for testing and document tools (Jacoco, Coveralls, REST Assured)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3431]
I've learned a lot about JUnit and code coverage since I wrote http://guides.dataverse.org/en/4.5.1/developers/testing.html and on that page I don't even mention https://coveralls.io/github/IQSS/dataverse which I set up as part of #775.

Internally I sent this around in August 2015:

To see the code coverage report (screenshot attached) from Netbeans, you can do the following:

- right click the "dataverse" project
- click Code Coverage
- click Show Report

![screen shot 2015-08-12 at 11 20 31 am](https://cloud.githubusercontent.com/assets/21006/19728264/bf0ed474-9b60-11e6-95a6-6e43d3d1b1de.png)

The screenshot I didn't send around but probably should have is this red vs. green view on a per-file basis that shows you which lines aren't even being touched by tests:

![screen shot 2016-10-26 at 9 50 44 am](https://cloud.githubusercontent.com/assets/21006/19728522/b0f91f38-9b61-11e6-9704-ddd9840472f6.png)

I find this invaluable when trying to figure out where to focus my testing efforts.

If you aren't using Netbeans, you can just open your equivalent of file:///Users/pdurbin/NetBeansProjects/dataverse/target/site/jacoco/index.html and see something like this:

![dataverse_-_2016-10-26_09 46 32](https://cloud.githubusercontent.com/assets/21006/19728378/21993d14-9b61-11e6-8a69-61ab651e14fc.png)

(I don't believe I'm doing anything special to create that "index.html" file but if other developers don't have it locally, please let me know!)

This issue closely relates to the larger issue and goal of better automated testing at #2746 but it's a simple doc change to explain how to use these tools.

**Comment by michbarsinai** [comment]
For testing, note that it's much easier to test commands: https://github.com/IQSS/dataverse/blob/develop/doc/theTestableCommand/TheTestableCommand.md

We do have a collection of mock objects for writing tests. Please add more as you go along. They are all here:
https://github.com/IQSS/dataverse/tree/develop/src/test/java/edu/harvard/iq/dataverse/mocks

(note: this is the `test` code folder, not `src`).

**Comment by pdurbin** [comment]
@michbarsinai thanks! I'm thinking we should take https://github.com/IQSS/dataverse/blob/develop/doc/theTestableCommand/TheTestableCommand.md and convert it from .md to .rst and have it be part of http://guides.dataverse.org/en/latest/developers/testing.html . Does that sound ok? I wrote a lot of testable commands for Private URL but we should see if you and I are on the same page. Code review is very welcome! Here are the classes:

- https://github.com/IQSS/dataverse/blob/v4.5.1/src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreatePrivateUrlCommandTest.java
- https://github.com/IQSS/dataverse/blob/v4.5.1/src/test/java/edu/harvard/iq/dataverse/engine/command/impl/DeletePrivateUrlCommandTest.java
- https://github.com/IQSS/dataverse/blob/v4.5.1/src/test/java/edu/harvard/iq/dataverse/engine/command/impl/GetPrivateUrlCommandTest.java

**Comment by pdurbin** [comment]
REST Assured tests should be remotely executable. See #3468.

**Comment by pdurbin** [comment]
Yesterday it became clear to me that folks such as @pameyer naturally assumed that `mvn test` executed all tests. This is not actually the case. **JUnit** tests are executed by `mvn test` because they have no dependency on Glassfish, Postgresl, or Solr but **REST Assured** tests are not because they do require these extra dependencies to be set up and running. In the Dev Guide we should document how to execute REST Assured tests. See also related issues #3468, #2746 and the comment at https://github.com/IQSS/dataverse/issues/1936#issuecomment-249191102

Here's an example of me running a REST Assured 

`mvn test -Dtest=FileRecordJobIT`

You can also specify multiple tests and the server to operate against like this:

`mvn test -Dtest=DataversesIT,DatasetsIT,SwordIT,AdminIT,BuiltinUsersIT,UsersIT,UtilIT,ConfirmEmailIT,FileMetadataIT -Ddataverse.test.baseurl='http://phoenix.dataverse.org'`

This last example is take from https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/

**Comment by pdurbin** [comment]
Related: #3163

**Comment by pdurbin** [comment]
@bsilverstein95 please pull the latest from develop and make sure `ConfirmEmailIT` still passes. Then we'll have you run the entire suite on your laptop from the command line with this:

`mvn test -Dtest=DataversesIT,DatasetsIT,SwordIT,AdminIT,BuiltinUsersIT,UsersIT,UtilIT,ConfirmEmailIT,FileMetadataIT,FilesIT,SearchIT'

You'll need to install Maven for `mvn` to work: https://maven.apache.org/

**Comment by pdurbin** [comment]
Part of the definition of done for this issue is @bsilverstein95 or any developer being able to run the API Tests after reading the Dev Guide.

Right now he's seeing "Dataverse config issue: No API key defined for built in user management".

The fix for this is to run the following curl command:

`curl -X PUT -d 'burrito' http://localhost:8080/api/admin/settings/BuiltinUsers.KEY`

@bsilverstein95 please give this a try and if it works, please create a branch off develop called `3431-dev-testing` (or whatever) and mention this fix at `doc/sphinx-guides/source/developers/testing.rst`.

Pinging @dlmurphy who may be able to provide assistance with all things guides.

**Comment by dlmurphy** [comment]
@bsilverstein95 If you need any help getting set up to edit testing.rst, let me know and I'll be happy to help. Also, ping me when that edit is in and I'll be happy to proofread.

**Comment by bsilverstein95** [comment]
@dlmurphy Appreciate it! I will reach out if/when I need help with that. (Haven't had a chance to use Sphinx / edit the guide prior).

In regards to @pdurbin 's solution I had much more success than with the curl command from the [Configuration Guide's BuiltinUsers.KEY](http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#builtinusers-key) section, which advises:

`curl -X PUT -d builtInS3kretKey http://localhost:8080/api/admin/settings/:BuiltinUsers.KEY`

I guess the API just likes burritos.

**Comment by pdurbin** [comment]
@bsilverstein95 heads up that you linked to an old version of the guides (2884-install-guide-reorg). We got rid of that pesky colon in 91efe09.

**Comment by bsilverstein95** [comment]
Oh! That would totally explain it. Thanks @pdurbin !

**Comment by pdurbin** [comment]
@bsilverstein95 pushed a branch called `3431-dev-guide` and I set up hourly builds at http://guides.dataverse.org/en/3431-dev-guide/developers/testing.html

**Comment by dlmurphy** [comment]
On @pdurbin's suggestion, retitled the "Branching Strategy" page to "Version Control" and added a "Using Git" section with information on how to make commits and merge conflicts to give developers a concrete process to refer to.

**Comment by pdurbin** [comment]
@dlmurphy thanks. We need to fix the errors like this:

`/home/pdurbin/NetBeansProjects/dataverse/doc/sphinx-guides/source/developers/index.rst:15: WARNING: toctree contains reference to nonexisting document u'developers/branching-strategy'`


`checking consistency... /home/pdurbin/NetBeansProjects/dataverse/doc/sphinx-guides/source/developers/version-control.rst:: WARNING: document isn't included in any toctree`

`/home/pdurbin/NetBeansProjects/dataverse/doc/sphinx-guides/source/developers/dev-environment.rst:99: WARNING: unknown document: /developers/branching-strategy`

**Comment by pdurbin** [comment]
@dlmurphy I fixed those errors in 271137d and assigned myself a bunch of issues related to the Dev Guide that I may or may not try to roll into the `3431-dev-guide` branch: #3729 #3418 #2746 #2724 #2644 #2575 #2574 #2163 #1936 #1797. If you're aware of others, please let me know.

@landreev in 3c0c538 I added the bit about how you have to build the war file before running the installer. @oscardssmith was looking over my shoulder and he approved of the change, saying that it would have helped him get set up for development.

**Comment by ferrys** [comment]
Using the command `mvn test -Dtest=FilesIT` (this also occurs when running DatasetsIT.java and DataversesIT.java) on my local dataverse on the develop branch, I am getting 10 failed tests:
`  testAddFileBadJson(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)
  test_005_AddFileBadPermissions(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)
  test_006_ReplaceFileGood(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)
  test_006_ReplaceFileGoodTabular(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)
  testForceReplace(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)
  test_007_ReplaceFileUnpublishedAndBadIds(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)
  test_008_ReplaceFileAlreadyDeleted(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)
  testReplaceFileBadJson(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)
  testAddTinyFile(edu.harvard.iq.dataverse.api.FilesIT): Expected status code <201> doesn't match actual status code <500>.(..)`

The glassfish logs suggest a null pointer in addDataverse, 
`[2017-06-09T12:10:32.008-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler] [tid: _ThreadID=30 _ThreadName=http-listener-1(2)] [timeMillis: 1497024632008] [levelValue: 1000] [[
  API internal error f610dce6-b1c2-4188-93b9-aa151ba44f85: Null Pointer
java.lang.NullPointerException
	at edu.harvard.iq.dataverse.api.Dataverses.addDataverse(Dataverses.java:151)
	at sun.reflect.GeneratedMethodAccessor1486.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:46)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor1472.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy668.addDataverse(Unknown Source)
	at edu.harvard.iq.dataverse.api.__EJB31_Generated__Dataverses__Intf____Bean__.addDataverse(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1486.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at edu.harvard.iq.dataverse.api.ApiBlockingFilter.doFilter(ApiBlockingFilter.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at edu.harvard.iq.dataverse.api.ApiRouter.doFilter(ApiRouter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:873)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:739)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:575)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:546)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:428)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:378)
	at edu.harvard.iq.dataverse.api.ApiRouter.doFilter(ApiRouter.java:34)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
]]`

**Comment by pdurbin** [comment]
@ferrys thanks. @bsilverstein95 is taking a look.

**Comment by bsilverstein95** [comment]
I've updated the testing portion of the developer guide to include the fix for the issue @ferrys (and myself) had above with `FilesIT.java` but just to make it known, the fix is to edit your root dataverse's permissions for users adding new dataverses. From localhost:8080 log in as dataverseAdmin and click the Edit button beside the root dataverse. Under "Who can add to this dataverse?” choose “Anyone with a dataverse account can add sub dataverses" then save and re-run.

Alternatively, if you don't like those four mouse clicks in the UI, execute the script found at:

`scripts/search/tests/grant-authusers-add-on-root`

**Comment by dlmurphy** [comment]
Reviewed Phil's additions to the Version Control page of the Dev Guide and it's looking great! I'd say that part of this issue is all set.

**Comment by sekmiller** [comment]
In order the run the DatasetsIT test you need to run createSequence.sql against your local database.

**Comment by pdurbin** [comment]
> In order the run the DatasetsIT test you need to run createSequence.sql against your local database.

Right. This is mentioned at https://github.com/IQSS/dataverse/blob/7076bdcc0ee1743d73a356f5ee542f7d76ea17f3/doc/sphinx-guides/source/developers/testing.rst#identifier-generation

**Comment by sekmiller** [comment]
Suggestions for Test Design: try to limit the size of the test methods to aid in debugging them
Future work: Automate the Integration Tests - so that all can be run by a single command.

**Comment by pdurbin** [comment]
@sekmiller good suggestions for the future. Thanks.
