### ISSUE TITLE
Show file upload limit as megabytes or kilobytes as appropriate rather than always as bytes

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3570]
"File upload limit is 10,737,418,240 bytes per file" looks pretty silly. It should be in megabytes in this case:

<img width="486" alt="screen shot 2017-01-13 at 4 21 50 pm" src="https://cloud.githubusercontent.com/assets/21006/21946420/6bddd23c-d9ae-11e6-88bb-95fdccc3e703.png">

**Comment by pdurbin** [comment]
https://commons.apache.org/proper/commons-io/javadocs/api-2.4/org/apache/commons/io/FileUtils.html#byteCountToDisplaySize(long)

**Comment by pdurbin** [comment]
I think this would be nice to have but I'm fine with others suggesting it. Closing.

**Comment by pdurbin** [comment]
It was embarrassing to have "2.7 billion bytes" in my slides last week ( https://twitter.com/philipdurbin/status/1007680649136832518 ) so I'm reopening this issue.

![screen shot 2018-06-20 at 11 54 22 am](https://user-images.githubusercontent.com/21006/41669845-b8bc6b54-7480-11e8-804d-83a9e621bba6.png)

**Comment by mheppler** [comment]
"1"

**Comment by djbrooke** [comment]
If the issue comes back, it truly loves you and it wants to be brought into a sprint.

**Comment by pdurbin** [comment]
Pull request #4768 looks good. Thanks, @oscardssmith ! Moving to QA.

**Comment by pdurbin** [comment]
As of 5d0a6de there's a PropertyNotFoundException:

```
[2018-06-22T15:20:27.884-0400] [glassfish 4.1] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.application] [tid: _ThreadID=53 _ThreadName=jk-connector(5)] [timeMillis: 1529695227884] [levelValue: 1000] [[
  Error Rendering View[/editdatafiles.xhtml]
javax.el.PropertyNotFoundException: /editFilesFragment.xhtml @147,89 value="#{systemConfig.getHumanMaxFileUploadSize}": The class 'edu.harvard.iq.dataverse.util.SystemConfig$Proxy$_$$_Weld$EnterpriseProxy$' does not have the property 'getHumanMaxFileUploadSize'.
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:182)
        at javax.faces.component.UIParameter.getValue(UIParameter.java:143)
        at com.sun.faces.renderkit.html_basic.OutputMessageRenderer.encodeEnd(OutputMessageRenderer.java:103)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
        at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.el.PropertyNotFoundException: The class 'edu.harvard.iq.dataverse.util.SystemConfig$Proxy$_$$_Weld$EnterpriseProxy$' does not have the property 'getHumanMaxFileUploadSize'.
        at javax.el.BeanELResolver.getBeanProperty(BeanELResolver.java:731)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:351)
        at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
        at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
        at com.sun.el.parser.AstValue.getValue(AstValue.java:140)
        at com.sun.el.parser.AstValue.getValue(AstValue.java:204)
        at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
        at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
        ... 60 more
]]
```

**Comment by oscardssmith** [comment]
I think it's because `getHumanMaxFileUploadSize` in the xhtml is trying to reference a fixed setting whereas it should be using the wrapper I made. Any idea why?

**Comment by pdurbin** [comment]
@oscardssmith I fixed it in 74b1cd2. This is one of the mysteries of JSF to me. Please take a look. This reminds me that we should probably be using our JSF wrapper rather than calling systemConfig directly. Please look for usages of "SettingsWrapper".

**Comment by pdurbin** [comment]
Actually, since SettingsWrapper is ViewScoped I don't think we need to bother with it since we're always going to get a new view when we click "Upload Files" so I'll just move this to QA.

**Comment by kcondon** [comment]
I think this should show fractional amounts to one decimal place like linux does when doing df -h, ie. 2.5GB not 2GB

**Comment by pdurbin** [comment]
@kcondon good point. https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html#byteCountToDisplaySize(long) indicates that the rounding down is expected behavior:

"If the size is over 1GB, the size is returned as the number of whole GB, i.e. the size is rounded down to the nearest GB boundary.

Similarly for the 1MB and 1KB boundaries."

I guess I'm find with the rounding down. Better than rounding up and having depositors being disappointed!
