### ISSUE TITLE
OAI-PMH responses indicating errors should be processable by OAI-PMH clients

### ISSUE THREAD

**Issue by tkgesis** [IQSS/dataverse#3797]
A valid OAI request such as
https://dataverse.unc.edu/oai?verb=ListIdentifiers&set=census&metadataPrefix=dc
should return a response processable for OAI-PMH clients or HTTP 5XX.

**Comment by pdurbin** [comment]
@tkgesis thanks but when I run `curl -i 'https://dataverse.unc.edu/oai?verb=ListIdentifiers&set=census&metadataPrefix=dc'` I see `HTTP/1.1 500 Internal Server Error` rather than `200`. That said, I do agree that it should return a processable response! Maybe we just need to change the subject/title of this issue.

**Comment by donsizemore** [comment]
[#|2017-04-26T13:29:06.671-0400|WARNING|<snip>
  StandardWrapperValve[OAIServlet]: Servlet.service() for servlet OAIServlet threw exception
javax.servlet.ServletException: Unknown servlet exception in Get.

**Comment by tkgesis** [comment]
'dc' is not a supported metadataPrefix, while 'oai_dc' is.

**Comment by tkgesis** [comment]
According to http://www.openarchives.org/OAI/openarchivesprotocol.html#ErrorConditions 
a XML response indicating the badArgument would do.

**Comment by pdurbin** [comment]
> 'dc' is not a supported metadataPrefix, while 'oai_dc' is.

Ah, so you get the same error at https://dataverse.unc.edu/oai?verb=ListIdentifiers&set=census&metadataPrefix=foobar presumably.

**Comment by donsizemore** [comment]
[#|2017-04-27T06:00:08.092-0400|WARNING|glassfish 4.1|edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet|_ThreadID=48;_ThreadName=jk-connector(2);_TimeMillis=1493287208092;_LevelValue=900;|
  Unknown exception in Get; null|#]

[#|2017-04-27T06:00:08.093-0400|WARNING|glassfish 4.1|javax.enterprise.web|_ThreadID=48;_ThreadName=jk-connector(2);_TimeMillis=1493287208093;_LevelValue=900;|
  StandardWrapperValve[OAIServlet]: Servlet.service() for servlet OAIServlet threw exception
javax.servlet.ServletException: Unknown servlet exception in Get.
        at edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet.doGet(OAIServlet.java:262)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:748)
|#]

**Comment by pdurbin** [comment]
@donsizemore thanks for the stacktrace and the version of Dataverse you're running. Here's where "Unknown servlet exception in Get." is coming from: https://github.com/IQSS/dataverse/blob/v4.5.1/src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java#L262

**Comment by pdurbin** [comment]
@tkgesis @donsizemore has this been fixed? I just went to https://dataverse.unc.edu/oai?verb=ListIdentifiers&set=census&metadataPrefix=dc and now it says "HTTP Status 503 - Sorry. OAI Service is disabled on this Dataverse node" like this:

![screen shot 2018-06-01 at 10 18 16 am](https://user-images.githubusercontent.com/21006/40845571-1e2f3a62-6585-11e8-8666-038b0e61d3ea.png)

Previously it was a 500 error: https://github.com/IQSS/dataverse/issues/3797#issuecomment-297482276

**Comment by pdurbin** [comment]
Just noting that I get a 500 on demo running 5.10.1 with this:

```
curl -i 'https://demo.dataverse.org/oai?verb=ListIdentifiers&set=census&metadataPrefix=dc'
```

**Comment by donsizemore** [comment]
@pdurbin I just tried, and I get: `<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd"><responseDate>2022-11-18T20:11:43Z</responseDate><request>https://demo.dataverse.org/oai</request><error code="noRecordsMatch">Requested set 'census' does not exist</error></OAI-PMH`

**Comment by pdurbin** [comment]
@donsizemore nice! Same! Here it is with a little pretty printing:

```
$ curl -s 'https://demo.dataverse.org/oai?verb=ListIdentifiers&set=census&metadataPrefix=dc' | xmllint -format -
<?xml version="1.0"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
  <responseDate>2022-11-18T20:46:56Z</responseDate>
  <request>https://demo.dataverse.org/oai</request>
  <error code="noRecordsMatch">Requested set 'census' does not exist</error>
</OAI-PMH>
```

Closing! (@tkgesis please let us know if it still isn't fixed for you.)

**Comment by pdurbin** [comment]
Oh, wait... a 200 response...

```
$ curl -i 'https://demo.dataverse.org/oai?verb=ListIdentifiers&set=census&metadataPrefix=dc'
HTTP/1.1 200 OK
Date: Fri, 18 Nov 2022 20:50:34 GMT
Server: Apache/2.4.37 (rocky) OpenSSL/1.1.1k mod_apreq2-20101207/2.8.1
Content-Type: text/xml;charset=UTF-8
Transfer-Encoding: chunked
```

I assume we want non-200 like @tkgesis asked for. Re-opening. Sorry for the noise!

**Comment by sekmiller** [comment]
Right. He's looking for an error response.

**Comment by pdurbin** [comment]
Ok, at least we already return `error code="noRecordsMatch"`, (it's something 😄 ):

```
  <error code="noRecordsMatch">Requested set 'census' does not exist</error>
```

**Comment by poikilotherm** [comment]
Note: you might want to open an issue at gdcc/xoai and tag me.

**Comment by sekmiller** [comment]
Latest library from XOAI (deployed to demo) fixes this issue.

**Comment by pdurbin** [comment]
Related:

- #10205
