### ISSUE TITLE
Glassfish 5.0.0.b05 deployment fails creating root dataverse

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3801]
Test installation of v4.6.1 build 69-1ed82ae on CentOS 7.3 using Postgres 9.2 and Glassfish 5.0.0.b05, Solr 4.6. Everything proceeds smoothly until the root dataverse creation:

[2017-04-27T10:50:31.175-0400] [glassfish 5.0] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=46 _ThreadName=admin-listener(3)] [timeMillis: 1493304631175] [levelValue: 800] [[  Loading application [dataverse] at [/]]]

[2017-04-27T10:50:31.390-0400] [glassfish 5.0] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=46 _ThreadName=admin-listener(3)] [timeMillis: 1493304631390] [levelValue: 800] [[
  dataverse was successfully deployed in 41,236 milliseconds.]]

[2017-04-27T10:50:31.399-0400] [glassfish 5.0] [WARNING] [] [org.glassfish.jersey.internal.Errors] [tid: _ThreadID=46 _ThreadName=admin-listener(3)] [timeMillis: 1493304631399] [levelValue: 900] [[  The following warnings have been detected: WARNING: The (sub)resource method oaiSets in edu.harvard.iq.dataverse.api.HarvestingServer contains empty path annotation.
WARNING: The (sub)resource method harvestingClients in edu.harvard.iq.dataverse.api.HarvestingClients contains empty path annotation.
]]

[2017-04-27T10:50:32.466-0400] [glassfish 5.0] [WARNING] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=30 _ThreadName=http-listener-1(1)] [timeMillis: 1493304632466] [levelValue: 900] [[
  Context path from ServletContext:  differs from path from bundle: /]]

[2017-04-27T10:50:41.105-0400] [glassfish 5.0] [WARNING] [] [javax.mail] [tid: _ThreadID=33 _ThreadName=http-listener-1(4)] [timeMillis: 1493304641105] [levelValue: 900] [[
  expected resource not found: /META-INF/javamail.default.providers]]

[2017-04-27T10:50:41.107-0400] [glassfish 5.0] [WARNING] [] [javax.mail] [tid: _ThreadID=33 _ThreadName=http-listener-1(4)] [timeMillis: 1493304641107] [levelValue: 900] [[
  expected resource not found: /META-INF/javamail.default.address.map]]

[2017-04-27T10:50:41.280-0400] [glassfish 5.0] [INFO] [] [edu.harvard.iq.dataverse.api.Dataverses] [tid: _ThreadID=32 _ThreadName=http-listener-1(3)] [timeMillis: 1493304641280] [levelValue: 800] [[
  Creating root dataverse]]

[2017-04-27T10:50:41.581-0400] [glassfish 5.0] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=134 _ThreadName=__ejb-thread-pool1] [timeMillis: 1493304641581] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB DataverseServiceBean, method: public edu.harvard.iq.dataverse.Dataverse edu.harvard.iq.dataverse.DataverseServiceBean.findRootDataverse()]]

[2017-04-27T10:50:41.581-0400] [glassfish 5.0] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=134 _ThreadName=__ejb-thread-pool1] [timeMillis: 1493304641581] [levelValue: 900] [[

javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
        at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:666)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:511)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy309.findRootDataverse(Unknown Source)
        at edu.harvard.iq.dataverse.__EJB31_Generated__DataverseServiceBean__Intf____Bean__.findRootDataverse(Unknown Source)
        at edu.harvard.iq.dataverse.search.SolrIndexServiceBean.indexPermissionsOnSelfAndChildren(SolrIndexServiceBean.java:400)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:824)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:823)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:823)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy241.indexPermissionsOnSelfAndChildren(Unknown Source)
        at edu.harvard.iq.dataverse.search.__EJB31_Generated__SolrIndexServiceBean__Intf____Bean__.indexPermissionsOnSelfAndChildren(Unknown Source)
        at edu.harvard.iq.dataverse.search.IndexAsync.indexRole(IndexAsync.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:824)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:823)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:823)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.
        at org.eclipse.persistence.internal.jpa.QueryImpl.throwNoResultException(QueryImpl.java:976)
        at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:526)
        at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
        at edu.harvard.iq.dataverse.DataverseServiceBean.findRootDataverse(DataverseServiceBean.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:824)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:823)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:823)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        ... 70 more
]]

[2017-04-27T10:50:41.584-0400] [glassfish 5.0] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=134 _ThreadName=__ejb-thread-pool1] [timeMillis: 1493304641584] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB SolrIndexServiceBean, method: public edu.harvard.iq.dataverse.search.IndexResponse edu.harvard.iq.dataverse.search.SolrIndexServiceBean.indexPermissionsOnSelfAndChildren(edu.harvard.iq.dataverse.DvObject)]]

**Comment by donsizemore** [comment]
during this time, the install script (and solr) output say:

OK, the Dataverse application appears to be running...

Executing post-deployment setup script setup-all.sh...
192458 [qtp1307096070-11] INFO  org.apache.solr.update.UpdateHandler  – start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
192459 [qtp1307096070-11] INFO  org.apache.solr.update.UpdateHandler  – No uncommitted changes. Skipping IW.commit.
192460 [qtp1307096070-11] INFO  org.apache.solr.search.SolrIndexSearcher  – Opening Searcher@6daac4d7 main
192461 [qtp1307096070-11] INFO  org.apache.solr.update.UpdateHandler  – end_commit_flush
192462 [searcherExecutor-4-thread-1] INFO  org.apache.solr.core.SolrCore  – QuerySenderListener sending requests to Searcher@6daac4d7 main{StandardDirectoryReader(segments_1:1:nrt)}
192462 [searcherExecutor-4-thread-1] INFO  org.apache.solr.core.SolrCore  – QuerySenderListener done.
192462 [searcherExecutor-4-thread-1] INFO  org.apache.solr.core.SolrCore  – [collection1] Registered new searcher Searcher@6daac4d7 main{StandardDirectoryReader(segments_1:1:nrt)}
192463 [qtp1307096070-11] INFO  org.apache.solr.update.processor.LogUpdateProcessor  – [collection1] webapp=/solr path=/update/json params={commit=true} {deleteByQuery=*:* (-1565843398052544512),commit=} 0 39
done!
Making additional configuration changes...

Executing curl -X PUT -d dls@ad.unc.edu http://localhost:8080/api/admin/settings/:SystemEmail
{"status":"OK","data":{":SystemEmail":"dls@ad.unc.edu"}}OK.

Executing curl -X PUT -d false http://localhost:8080/api/admin/settings/:TwoRavensTabularView
{"status":"OK","data":{":TwoRavensTabularView":"false"}}OK.

You should now have a running DVN instance at
  http://irss-gftest.irss.unc.edu:8080

**Comment by donsizemore** [comment]
I should point out that with 5.0.0.b05 I didn't down-grade the Weld OSGI bundle:

[dls@irss-gftest example]$ sudo /usr/local/glassfish4/bin/asadmin osgi lb |grep -i weld
   94|Resolved   |    1|Weld connector for glassfish (5.0.0.b05)
  290|Resolved   |    1|org.glassfish.main.web.weld-integration-fragment (0.0.0)
  291|Resolved   |    1|Weld integration for glassfish (5.0.0.b05)
  292|Resolved   |    1|Weld OSGi Bundle (2.2.13.Final)

**Comment by donsizemore** [comment]
Retracing some of setup-all.sh manually, the root dataverse is indeed present in the database, and Dataverse likes the metadata block and default facets:
{"status":"ERROR","message":"Root Dataverse already exists. Cannot create another one"}
{"status":"OK","data":{"message":"Metadata blocks of dataverse :root updated."}}
{"status":"OK","data":{"message":"Facets of dataverse :root updated."}}

The homepage displays "Validation Error – Required fields were missed or there was a validation error. Please scroll down to see details." but nothing is written to server.log.

On launch Solr only warns
Apr 27 15:59:02 irss-gftest java: 3191 [coreLoadExecutor-3-thread-1] INFO  org.apache.solr.core.RequestHandlers  – created /update: solr.UpdateRequestHandler
Apr 27 15:59:02 irss-gftest java: 3200 [coreLoadExecutor-3-thread-1] WARN  org.apache.solr.core.SolrResourceLoader  – Solr loaded a deprecated plugin/analysis class [solr.JsonUpdateRequestHandler]. Please consult documentation how to replace it accordingly.
Apr 27 15:59:02 irss-gftest java: 3200 [coreLoadExecutor-3-thread-1] INFO  org.apache.solr.core.RequestHandlers  – created /update/json: solr.JsonUpdateRequestHandler
Apr 27 15:59:02 irss-gftest java: 3201 [coreLoadExecutor-3-thread-1] WARN  org.apache.solr.core.SolrResourceLoader  – Solr loaded a deprecated plugin/analysis class [solr.CSVRequestHandler]. Please consult documentation how to replace it accordingly.
Apr 27 15:59:02 irss-gftest java: 3201 [coreLoadExecutor-3-thread-1] INFO  org.apache.solr.core.RequestHandlers  – created /update/csv: solr.CSVRequestHandler

and I've verified I gave it the correct schema.xml.  Sorry, didn't get to poke at this much more today, just documenting bits here.

**Comment by donsizemore** [comment]
closing in favor of #2628
