### ISSUE TITLE
RuntimeException in creating new custom nodes in glassfish-4.1.2

### ISSUE THREAD

**Issue by hemal0105** [IQSS/dataverse#3984]
RuntimeException in creating new custom nodes in glassfish-4.1.2.

This error occurred when creating new node from DAS console left side tabs.

Stacktrace is as below
[2017-07-07T10:48:37.868+0530] [glassfish 4.1] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=86 _ThreadName=admin-listener(6)] [timeMillis: 1499404717868] [levelValue: 1000] [[
  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException while attempting to process a 'beforeCreate' event for 'event167'.
       at com.sun.jsftemplating.layout.descriptors.LayoutElementBase.dispatchHandlers(LayoutElementBase.java:422)
       at com.sun.jsftemplating.layout.descriptors.LayoutElementBase.dispatchHandlers(LayoutElementBase.java:394)
       at com.sun.jsftemplating.layout.descriptors.LayoutComponent.beforeCreate(LayoutComponent.java:348)
       at com.sun.jsftemplating.layout.descriptors.LayoutComponent.getChild(LayoutComponent.java:288)
       at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:556)
       at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:551)
       at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:507)
       at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:507)
       at com.sun.jsftemplating.layout.LayoutViewHandler.createView(LayoutViewHandler.java:255)
       at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:256)
       at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
       at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:123)
       at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
       at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
       at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
       at com.sun.webui.jsf.util.UploadFilter.doFilter(UploadFilter.java:233)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
       at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
       at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:678)
       at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
       at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
       at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
       at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
       at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
       at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
       at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
       at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
       at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
       at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:231)
       at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
       at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
       at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:231)
       at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
       at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
       at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
       at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
       at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
       at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
       at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
       at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
       at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
       at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
       at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
       at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)
       at com.sun.jsftemplating.layout.descriptors.handler.Handler.invoke(Handler.java:442)
       at com.sun.jsftemplating.layout.descriptors.LayoutElementBase.dispatchHandlers(LayoutElementBase.java:420)
       ... 60 more
Caused by: java.lang.NullPointerException
       at com.sun.jsftemplating.handlers.UtilHandlers.mapPut(UtilHandlers.java:314)
       ... 65 more
]]

**Comment by pdurbin** [comment]
> RuntimeException in creating new custom nodes in glassfish-4.1.2.
> 
> This error occurred when creating new node from DAS console left side tabs.

@hemal0105 hi! Since you are describing a problem with Glassfish, can you please open an issue at https://github.com/javaee/glassfish/issues intead?

**Comment by hemal0105** [comment]
Apologies for posting query here instead of glassfish.
Thank you for helping.

**Comment by pdurbin** [comment]
@hemal0105 no worries! I see you opened https://github.com/javaee/glassfish/issues/22003 so I'm going to close this issue. If you need any help installing Dataverse, please reach out using any of the channels listed at http://guides.dataverse.org/en/4.7/installation/intro.html#getting-help . Thanks.
