### ISSUE TITLE
Allow to use of AWS Iam Role to access S3

### ISSUE THREAD

**Issue by abollini** [IQSS/dataverse#4294]
I'm setting up Dataverse on AWS EC2 and I want to use S3 as storage. The code assumes that credentials need to be provided in the ~/.aws/credentials but this is only one of the way to configure the AWS SDK, moreover this is discouraged when you are already on EC2. The AWS recommendation is to use an IAM role.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

Anyone is already working on that?

**Comment by pdurbin** [comment]
@abollini thanks for opening this issue. I didn't know using ~/.aws/credentials is discouraged in some cases. I'm pretty sure no on is working adding support of an IAM role as well. Is this an option you're interested in adding yourself? If so, we can help guide you in making a pull request.

**Comment by abollini** [comment]
hi @pdurbin yes, this is something that we will need to fix in the medium/long term.

**Comment by pdurbin** [comment]
@abollini ok, but for now it sounds like you can get by with ~/.aws/credentials. Harvard Dataverse is moving from physical hardware to AWS soon and we're planning on using ~/.aws/credentials as far as I know. We're working on a backup script from S3 if that's of interest: #4157

**Comment by abollini** [comment]
@pdurbin thanks to share the link to the backup discussion. Our strategy is to use versioning and lifecycle management on S3, so that deletion happen only 30-60 days later. 
We are looking to a script to verify that all the files in dataverse are really on S3 as expected on a daily basis using the inventory. Indeed, during our initial test we have noted that lacking of permission to write on S3 result in the files to be not uploaded without any errors reported to the user or in the log file. You will note the issue only when you will go to download the file...

Finally we want to support a more self-service granular backup service based on AIP deposited on duracloud so that we will have also integrity check.

**Comment by pdurbin** [comment]
> during our initial test we have noted that lacking of permission to write on S3 result in the files to be not uploaded without any errors reported to the user or in the log file

This sounds like a pretty serious bug and similar to what @gupta-yash  was reporting at #4223 ("when I uploaded my dataset on the Dataverse dashboard, it isn't showing up in my S3 bucket"). @abollini would you be interested in opening a new issue about this? I'm interested in your thoughts on how you think the failure should be communicated back to the end user (and sysadmin?).

> Finally we want to support a more self-service granular backup service based on AIP deposited on duracloud so that we will have also integrity check.

This reminds me of https://wiki.archivematica.org/Dataverse , especially "The proposed workflow consists of issuing API calls to Dataverse, receiving content (data files and metadata) for ingest into Archivematica, preparing Archivematica Archival Information Packages (AIPs) and placing them in archival storage".

The latest update on that was from @amberleahey about a month ago who wrote, "At Scholars Portal we are working with Artefactual's team, including Justin Simpson (Director, Archivematica) to get this into a public release, most likely in 2018" over at https://groups.google.com/d/msg/dataverse-community/4e4F2O-UpQk/4g5zrcVrAwAJ

**Comment by matthew-a-dunlap** [comment]
Hi @abollini , during our development we used IAM roles along with S3 support. We created a group of IAM users under our root account with only the required access, and generated each one their own access key. Those keys were then used in the credentials files. What usage of IAM roles are you looking for?

**Comment by abollini** [comment]
hi @matthew-a-dunlap sorry for the late reply I miss the github notification...
at the end I have solved our issue with the small change proposed in the PR #4375 
When you use an EC2 instance you can conveniently give to it an IAM Role http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html
this avoid the need of temporary API KEY keeping the env secure (API KEYs should be refreshed periodically to keep them secure, this add extra effort to the ops team).

Another benefit is that we can now use the AWS config file to specify the S3 endpoint in Europe instead than use the default US Virginia region.

BTW an interesting bug that we had hit: if you create a new S3 Bucket in a region other than Virginia (Dublin in our case) and you configure Dataverse to use it immediately: it works... after a while you start to get authorization errors. This is expected as new S3 bucket will be always initially served from Virginia see http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHosting and the current dataverse code force the use of the S3 Virginia endpoint (as noted above this is solved in the above PR)

**Comment by pdurbin** [comment]
@abollini thanks for the pull request! I just advanced it to the "Code Review" column at https://waffle.io/IQSS/dataverse (see also http://guides.dataverse.org/en/4.8.4/developers/version-control.html#make-sure-your-pull-request-has-been-advanced-to-code-review ). Every morning at our standup meeting we talk about which issues are in the Code Review column (and QA and Development).

I'm not sure what to say about forcing the use of the S3 Virginia endpoint. Can you please open a new issue about that bug you found? It sounds very different than IAM auth stuff.

**Comment by pdurbin** [comment]
@abollini please nevermind about opening a new issue. @landreev and I looked at your pull request after standup this morning and now I that `Regions.US_EAST_1` is hard-coded auth part of the code. This seems bad but I thought you were saying that all files only ever get saved on S3 in Virginia.

I'm not super familiar with this code but I mentioned it to @matthew-a-dunlap . It looks like it was added back in 39375c8 and may have simply been an oversight. Thanks for catching this.

**Comment by pdurbin** [comment]
@landreev heads up that I went ahead and moved @abollini 's pull request to QA. Please feel free to drag it back if you feel like there are changes you think should be made.

@abollini if you feel like the docs could be improved, please feel free to edit `doc/sphinx-guides/source/installation/config.rst` which talks about S3 storage and auth.

**Comment by pdurbin** [comment]
@abollini I added some documentation at 67e0371 about using IAM Roles. You or @matthew-a-dunlap or others may want to improve upon what I added. I'm not very familiar with IAM Roles myself but at least we're now hinting in the Dataverse Installation Guide that the `~/.aws/credentials` file is not strictly required and that IAM Roles can be used instead.

Also, thanks for the tweet at https://twitter.com/4ScienceIT/status/940535617921970177 and the pull request! 😄

**Comment by pdurbin** [comment]
@abollini I was just talking to @matthew-a-dunlap and @kcondon about your fix. The `~/.aws/credentials` is not necessary on an EC2 instance right? Is that because environment variables or something are automatically inserted on EC2 instances such that the S3 client/code gets the proper credentials? Should I not even care how it works? 😄 Should I just be happy that a `~/.aws/credentials` file isn't necessary? Sorry, I'm new to all this AWS stuff.

**Comment by abollini** [comment]
hi @pdurbin ,
thanks to go over the PR so quickly.
The credentials file is not necessary on an EC2 instance **if you use assign a IAM role** to the instance. If your EC2 instance doesn't have a IAM role because for instance you have multiple services/users on the server with different privilege you can use the credentials file in the home of the user used to run glassfish/dataverse to set your credentials or system variables that can be set on the jvm (-Daws.accessKeyId=.... -Daws.secretKey=...) 
Please note that if system variables and the credentials file will take precedence over EC2 IAM role if both options are used.
The update that you make to the documentation looks good to me

**Comment by pdurbin** [comment]
@abollini phew. Thanks! 😄

**Comment by kcondon** [comment]
@abollini I work in QA and tried a simple test creating a dataset using S3 storage using my previously working credentials file. The result was an error complaining about a missing region. I added region=us-east-1 to the file and it still failed. Any ideas?

Here is the stack trace:

[2017-12-18T15:46:43.741-0500] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=54 _ThreadName=jk-connector(5)] [timeMillis: 1513630003741] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB IngestServiceBean, method: public void edu.harvard.iq.dataverse.ingest.IngestServiceBean.addFiles(edu.harvard.iq.dataverse.DatasetVersion,java.util.List)]]

[2017-12-18T15:46:43.742-0500] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=54 _ThreadName=jk-connector(5)] [timeMillis: 1513630003742] [levelValue: 900] [[
  
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:662)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:507)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy253.addFiles(Unknown Source)
	at edu.harvard.iq.dataverse.ingest.__EJB31_Generated__IngestServiceBean__Intf____Bean__.addFiles(Unknown Source)
	at edu.harvard.iq.dataverse.engine.command.impl.CreateDatasetCommand.execute(CreateDatasetCommand.java:166)
	at edu.harvard.iq.dataverse.engine.command.impl.CreateDatasetCommand.execute(CreateDatasetCommand.java:33)
	at edu.harvard.iq.dataverse.EjbDataverseEngine.submit(EjbDataverseEngine.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy309.submit(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__EjbDataverseEngine__Intf____Bean__.submit(Unknown Source)
	at edu.harvard.iq.dataverse.DatasetPage.save(DatasetPage.java:2489)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:289)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.AmazonClientException: Cannot instantiate a S3 client using AWS SDK defaults for credentials and region
	at edu.harvard.iq.dataverse.dataaccess.S3AccessIO.<init>(S3AccessIO.java:79)
	at edu.harvard.iq.dataverse.dataaccess.DataAccess.createNewStorageIO(DataAccess.java:103)
	at edu.harvard.iq.dataverse.dataaccess.DataAccess.createNewStorageIO(DataAccess.java:80)
	at edu.harvard.iq.dataverse.ingest.IngestServiceBean.addFiles(IngestServiceBean.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 95 more
Caused by: com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:371)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:337)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.defaultClient(AmazonS3ClientBuilder.java:54)
	at edu.harvard.iq.dataverse.dataaccess.S3AccessIO.<init>(S3AccessIO.java:77)
	... 127 more
]]

**Comment by landreev** [comment]
OK, it looks like we need to explicitly set up the key, secret key and region as environmental variables, or JVM option, etc. - if we want to continue using S3 without relying on IM role. 

We would actually prefer NOT to have to do this. Any chance you could modify your PR to roll back to using the ~/.aws/credentials file, if the IM role was not available? 

Something along the lines of 

```
try {
   // first try .defaultClient() - configuration via IM role:
   s3 = AmazonS3ClientBuilder.standard().defaultClient();
} catch (Exception e) {
   // ... if that fails, try looking for ~/.aws/credentials:
   try {
      awsCredentials = new ProfileCredentialsProvider().getCredentials(); 
      s3 = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(awsCredentials)).build();
   ... etc.

```

**Comment by landreev** [comment]
OK, nevermind - it looks like it is NOT necessary, to rewrite any of your code. 
Your line
```
   s3 = AmazonS3ClientBuilder.standard().defaultClient();
```
appears to be working without an IM role defined, by defaulting to the configuration in ~/.aws. As long as we specify the default region in the configuration, in the file ~/.aws/config, like this:
```
[default]
region = us-east-1
```

(it wasn't initially working for us, because I thought that this region=... line needed to be added to ~/.aws/credentials instead). 

We do need to add a couple of lines to the documentation though, explaining how to set the region in the ~/.aws configuration.

**Comment by landreev** [comment]
It's kind of interesting that this fails: 
```
   awsCredentials = new ProfileCredentialsProvider().getCredentials(); 
      s3 = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(awsCredentials)).build();
```

unless the region is specifically set in the configuration. Because some AWS documentation appears to suggest that if the region is not specified, it should default to us-east-1...

**Comment by abollini** [comment]
hi @landreev , happy to see that you have solved the issue with the config file. We are on different timezone, I was unable to reply before.

I think that is a best practice to explicitly set the default region on the aws sdk

**Comment by landreev** [comment]
Hi @abollini , could you please give me access to https://github.com/4Science/dataverse - I would like to add a paragraph to the guide, about specifying the region (when not using IM role). Would be nice to do it in the same pull request. 

(if this is a problem - we'll just merge your PR, then add this change via a local brunch; either way works).

**Comment by landreev** [comment]
This is what I want to add to the doc: 
```
You must also specify the AWS region, in the ``config`` file, for example:

| ``[default]``
| ``region = us-east-1``

Place these two files in a folder named ``.aws`` under the home directory for the user running your Dataverse Glassfish instance. 
```

(there maybe a couple of instances elsewhere in the doc where "the file" should be replaced with "the files")

**Comment by abollini** [comment]
hi @landreev I have granted you write access to our repository. It is strange that you need that as I have given permission to the maintainers to edit my PR... anyway, now you should be definitively able to do that if other improvements are needed.

I have included your suggestion and make other small edit to remember about the config file also in the IAM section.

**Comment by landreev** [comment]
@abollini thanks!

**Comment by landreev** [comment]
@kcondon Kevin, please remind me to add 2 sentences to the release notes: "If you are using S3, we used to have the AWS region hard-coded, we got rid of that, so you now have to specify the region as follows: ..."

**Comment by landreev** [comment]
@kcondon - I've added a couple of cosmetic changes to the guide. I think it's ready.
