### ISSUE TITLE
Cannot publish a dataset if the affiliation of an author is blank

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4330]
A `NullPointerException` is preventing datasets from being published when an author does not have an affiliation in the `develop` branch as of 0f36aa0 and probably earlier.

In the code we do a `getValue` like this without checking if `datasetAuthor.getAffiliation()` is null:

     String affiliation = datasetAuthor.getAffiliation().getValue();`

From the user perspective, the page doesn't respond to the "Publish" button.

To reproduce delete "Dataverse.org" (highlighted in blue below) or whatever the UI has populated as the author affiliation:

![screen shot 2017-11-30 at 4 08 06 pm](https://user-images.githubusercontent.com/21006/33455938-a4f6ad34-d5eb-11e7-965b-18c4a3a5283f.png)

Then try to publish.

![screen shot 2017-11-30 at 4 08 31 pm](https://user-images.githubusercontent.com/21006/33455937-a4ea35b8-d5eb-11e7-8e3b-2209cccdfb5c.png)

In `server.log` you will see the following stack trace:

```
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DatasetVersion.getJsonLd(DatasetVersion.java:1239)
	at edu.harvard.iq.dataverse.export.SchemaDotOrgExporter.exportDataset(SchemaDotOrgExporter.java:24)
	at edu.harvard.iq.dataverse.export.ExportService.cacheExport(ExportService.java:262)
	at edu.harvard.iq.dataverse.export.ExportService.exportAllFormats(ExportService.java:160)
	at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.exportMetadata(FinalizeDatasetPublicationCommand.java:137)
	at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.execute(FinalizeDatasetPublicationCommand.java:100)
	at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.execute(FinalizeDatasetPublicationCommand.java:39)
```

I showed the bug to @kcondon and @djbrooke agreed that we should fix this before releasing 4.8.4. This bug was discovered by investigating the failing API tests in #4329.

**Comment by pdurbin** [comment]
I just made pull request #4331 . Can someone please code review it? Please go ahead and fix up my change if you don't like how I fixed it. Thanks.

**Comment by matthew-a-dunlap** [comment]
Looks good!
