### ISSUE TITLE
Response has already been committed error followed by Out of memory problem

### ISSUE THREAD

**Issue by mullaium** [IQSS/dataverse#4411]
Hi,
We are using Dataverse version 4.8.4, with Postgresql version 9.6.5, with Glassfish 4.1, we keep getting this error, "Response has already been committed"....
 and the application runs out of Java memory (3Gb).

This happens all the time when the server is up and it takes about 24 hours to runout of 2Gb memory which I increased to 3Gb now and it still runs out of memory. This happens even when there are no user browsing  and I think it is triggered by the solr related activities, i could be wrong.
Any help is appreciated..Thanks in advance.

Error log below......
 
[2018-01-11T12:49:34.207-0600] [glassfish 4.1] [WARNING] [] [] [tid: _ThreadID=35 _ThreadName=http-listener-1(10)] [timeMillis: 1515696574207] [levelValue: 900] [[
  Response has already been committed, and further write operations are not permitted. This may result in an IllegalStateException being triggered by the underlying application. To avoid this situation, consider adding a Rule `.when(Direction.isInbound().and(Response.isCommitted())).perform(Lifecycle.abort())`, or figure out where the response is being incorrectly committed and correct the bug in the offending code.]]

[2018-01-11T12:49:34.594-0600] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=35 _ThreadName=http-listener-1(10)] [timeMillis: 1515696574594] [levelValue: 900] [[
  org.apache.catalina.core.StandardHostValve@3acd62e9: Exception processing ErrorPage[errorCode=404, location=/404.xhtml]
java.io.IOException: Connection is closed
        at org.glassfish.grizzly.nio.NIOConnection.assertOpen(NIOConnection.java:432)
        at org.glassfish.grizzly.http.io.OutputBuffer.flush(OutputBuffer.java:735)
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:291)
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:275)
        at org.apache.catalina.connector.Response.flushBuffer(Response.java:689)
        at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:336)
        at org.apache.catalina.core.StandardHostValve.dispatchToErrorPage(StandardHostValve.java:701)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:380)
        at org.apache.catalina.core.StandardHostValve.postInvoke(StandardHostValve.java:234)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:418)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.flushByteBuffer(TCPNIOUtils.java:149)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.writeCompositeBuffer(TCPNIOUtils.java:87)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:129)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:106)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:260)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:169)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:71)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleWrite(TCPNIOTransportFilter.java:126)
        at org.glassfish.grizzly.filterchain.TransportFilter.handleWrite(TransportFilter.java:191)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$8.execute(ExecutorResolver.java:111)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)

Cheers,
-Mullai.

**Comment by pdurbin** [comment]
@mullaium thanks for bringing this issue to our attention and starting the thread at https://groups.google.com/d/msg/dataverse-community/db3PjaQ1UQ4/RBpd5flMAAAJ

In that thread it sounds like @donsizemore suggested increasing the amount of memory available.

**Comment by pdurbin** [comment]
@mullaium are you all set? If so, can you please close this issue?

**Comment by mheppler** [comment]
I reported seeing this same `Exception processing ErrorPage[errorCode=404, location=/404.xhtml]` in _Broken 403 Error pg #5967_. Not sure how related it is to the 403 error handling I was seeing, but thought I'd at least record it somewhere.

What actually brought me to this issue was the `Response has already been committed...` warning that I saw in my server logs, from the dataset pg. @scolapasta informed me that we've had this warning for a while, and it might not be an easy fix.

Also very related to the issue @PaulBoon opened, _Too much logging messages #5749_.

**Comment by djbrooke** [comment]
Hi @mullaium, I'm going to close this issue as I'm unsure of the next steps. We've been working on a few issues related to memory usage recently and we have at least one more to go (#6035). We'll keep working in this area, but if this is still an issue please reopen with a few more details. Thank you!
