### ISSUE TITLE
Review/fix exception handling in the S3 StorageIO driver

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4578]
By design, the methods implementing StorageIO functions should only be throwing IOExceptions when things go wrong. 
It appears that this may not be the case with S3AccessIO. For example, an attempt to open an object that does not exist in the bucket appears to be throwing something that's not an IOException, resulting in the API access method exiting with a 500, instead of a clean 404.
Similarly, a failure to upload or save an S3 object may be throwing a wrong exception... which in turn may produce a condition where the failure goes undetected; and that's how we end up with DataFiles that exist in the database, but miss the corresponding physical file - ? 

Sorry for all the vague "may be"s; the "review" part is the key - this needs to be investigated more.

**Comment by landreev** [comment]
Example: 
On a Dataverse configured to use S3, upload a file, unplug the networking cable (and/or disable wireless) before hitting "save". Tons of exceptions in the server.log, frozen page. 
From the server log, this appears to be the exception thrown: 
com.amazonaws.SdkClientException (https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SdkClientException.html)
- this is a RunTime exception. 

fragment of the stack trace: 
at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1267)
	at edu.harvard.iq.dataverse.dataaccess.S3AccessIO.open(S3AccessIO.java:102)
	at edu.harvard.iq.dataverse.dataaccess.DataAccess.createNewStorageIO(DataAccess.java:118)
	at edu.harvard.iq.dataverse.dataaccess.DataAccess.createNewStorageIO(DataAccess.java:90)

- so it's in our S3AccessIO.open() method. Solution: the exception needs to be caught properly and the open() method should handle it in some clean way - throw an IOException(), retrurn null - whatever. But as is, it's breaking everything. 

The experiment above does NOT result in a DataFile that's saved in the databse, but not on S3.

**Comment by landreev** [comment]
Quick thoughts on how to test: 
Everything that was working before, S3-wise, should still be working. 

But the focus of the issue was the error conditions. The goal there was to eliminate uncaught/not properly intercepted error conditions. In terms of observable effects - nothing that can go wrong with s3 should result in a stack trace in the server.log.

It may not be possible to test this to be 100% sure. (simply because there is no way to think of and imitate everything that can possibly go wrong with S3!). 

But there are some reproducible tests. 

See the second comment in the issue - the case of the datafile in the Dataverse with the S3 file missing. Attempting to download such file, before the PR: a stack trace in server.log; an ugly 500 for the user. After the PR: a clean API 404 message - "cannot find or open physical file".

Another test: bad S3 credentials; or non-existing bucket. 

Uploading a file, then unplugging the network cable before clicking "save". (you may not be able to test this from home, if you don't have a running local build). 

So, once again, whatever bad things happen - there shouldn't be a noisy stack trace in the log. Because that's a sign of an unintercepted error.
