### ISSUE TITLE
Email Service Error

### ISSUE THREAD

**Issue by lbigramUWI** [IQSS/dataverse#4655]
Does anyone know what could be the problem here? See below...
It throws the error for every password reset. For any type of email address, even our university domain address. 

In addition, this is the setting in the domain.xml
mail-resource host="192.168.2.251" from="uwidataverse@sta.uwi.edu" user="dataversenotify" jndi-name="mail/notifyMailSession"

[2018-05-09T05:15:48.741-0400] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=49 _ThreadName=Thread-8] [timeMillis: 1525857348741] [levelValue: 800] [[
  javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
        com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

        at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1949)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1195)
        at javax.mail.Transport.send0(Transport.java:254)
        at javax.mail.Transport.send(Transport.java:146)
        at edu.harvard.iq.dataverse.MailServiceBean.sendSystemEmail(MailServiceBean.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy209.sendSystemEmail(Unknown Source)
        at edu.harvard.iq.dataverse.__EJB31_Generated__MailServiceBean__Intf____Bean__.sendSystemEmail(Unknown Source)
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetServiceBean.sendPasswordResetEmail(PasswordResetServiceBean.java:99)
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetServiceBean.requestPasswordReset(PasswordResetServiceBean.java:73)
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetServiceBean.requestReset(PasswordResetServiceBean.java:53)

**Comment by djbrooke** [comment]
Hi @lbigramUWI - I think this may be solved by upgrading to 4.8.6, which contains the fix from #4240. I'll wait for someone else with more knowledge to take a look before closing this as a possible duplicate.

**Comment by lbigramUWI** [comment]
Okay, i will try this.

**Comment by lbigramUWI** [comment]
@djbrooke , thank you for the assistance. The upgrade solved the problem.

**Comment by djbrooke** [comment]
Great news! I'll close this one for now.
