### ISSUE TITLE
Export: reExportAll results in out of memory error when exporting prod db on 20GB web server.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4682]
When running reExportAll endpoint on a web server with 20GB heap and against a copy of production db, it fails after about 4 hours with java out of memory error:

```
[2018-05-15T01:15:48.688-0400] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=1649 _ThreadName=__ejb-thread-
pool4] [timeMillis: 1526361348688] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB DatasetServiceBean, method: public void edu.harvard.iq.dataverse.DatasetServiceBean.reExportA
llAsync()]]

[2018-05-15T01:15:48.689-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=1649 _ThreadName=__ejb-thread-pool4] [time
Millis: 1526361348689] [levelValue: 900] [[
  
javax.ejb.EJBException
        at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
        at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
        at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:114)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by djbrooke** [comment]
We'd want this free memory as it goes. We handle a similar issue with IndexAll. 

@kcondon can you mention the related issue here?
