### ISSUE TITLE
Resource Bundle Property files

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#4892]
This issues is created to investigate on storing all language specific resource bundle property files in the file system outside DV WAR file

Conversation started from here : https://github.com/IQSS/dataverse/issues/4856#issuecomment-406633954

ScholarsPortal github branch has implementation: 
https://github.com/scholarsportal/dataverse/tree/dataverse-externalProperty

I would like to merge this code along with UIToggle to perform better testing:
https://github.com/IQSS/dataverse/issues/4685

**Comment by pdurbin** [comment]
@JayanthyChengan hi! Thanks for pull request #5023 

I just dragged this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@JayanthyChengan hi, I'm on 3d6acb8 of your pull request and I'm getting the following stack trace when I try to run the app:

```
[2018-09-12T10:57:50.548-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.util.BundleUtil] [tid: _ThreadID=44 _ThreadName=admin-listener(1)] [timeMillis: 1536764270548] [levelValue: 800] [[
  dataverselocalebean   : **** : en]]

[2018-09-12T10:57:50.552-0400] [glassfish 4.1] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=44 _ThreadName=admin-listener(1)] [timeMillis: 1536764270552] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbDeployer load method
java.lang.RuntimeException: EJB Container initialization error
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:234)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:291)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:99)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:206)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:313)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at edu.harvard.iq.dataverse.validation.PasswordValidatorServiceBean.<init>(PasswordValidatorServiceBean.java:102)
	at edu.harvard.iq.dataverse.validation.__EJB31_Generated__PasswordValidatorServiceBean__Intf____Bean__.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.sun.ejb.containers.BaseContainer.instantiateOptionalEJBLocalBusinessObjectImpl(BaseContainer.java:3866)
	at com.sun.ejb.containers.StatelessSessionContainer.initializeHome(StatelessSessionContainer.java:237)
	at com.sun.ejb.containers.StatelessContainerFactory.createContainer(StatelessContainerFactory.java:63)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:221)
	... 43 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name Bundle, locale en
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1082)
	at edu.harvard.iq.dataverse.util.BundleUtil.getStringFromBundle(BundleUtil.java:47)
	at edu.harvard.iq.dataverse.util.BundleUtil.getStringFromBundle(BundleUtil.java:23)
	at edu.harvard.iq.dataverse.validation.GoodStrengthRule.<clinit>(GoodStrengthRule.java:18)
	... 54 more
]]

[2018-09-12T10:57:50.554-0400] [glassfish 4.1] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=44 _ThreadName=admin-listener(1)] [timeMillis: 1536764270554] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.RuntimeException: EJB Container initialization error
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:234)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:291)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:99)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:206)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:313)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at edu.harvard.iq.dataverse.validation.PasswordValidatorServiceBean.<init>(PasswordValidatorServiceBean.java:102)
	at edu.harvard.iq.dataverse.validation.__EJB31_Generated__PasswordValidatorServiceBean__Intf____Bean__.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.sun.ejb.containers.BaseContainer.instantiateOptionalEJBLocalBusinessObjectImpl(BaseContainer.java:3866)
	at com.sun.ejb.containers.StatelessSessionContainer.initializeHome(StatelessSessionContainer.java:237)
	at com.sun.ejb.containers.StatelessContainerFactory.createContainer(StatelessContainerFactory.java:63)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:221)
	... 43 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name Bundle, locale en
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1082)
	at edu.harvard.iq.dataverse.util.BundleUtil.getStringFromBundle(BundleUtil.java:47)
	at edu.harvard.iq.dataverse.util.BundleUtil.getStringFromBundle(BundleUtil.java:23)
	at edu.harvard.iq.dataverse.validation.GoodStrengthRule.<clinit>(GoodStrengthRule.java:18)
	... 54 more
]]

[2018-09-12T10:57:50.555-0400] [glassfish 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=44 _ThreadName=admin-listener(1)] [timeMillis: 1536764270555] [levelValue: 1000] [[
  Exception while loading the app]]

[2018-09-12T10:57:50.563-0400] [glassfish 4.1] [INFO] [] [org.eclipse.persistence.session.file:/Users/pdurbin/NetBeansProjects/dataverse/target/dataverse-4.9.2/WEB-INF/classes/_VDCNet-ejbPU.connection] [tid: _ThreadID=169 _ThreadName=pool-50-thread-1] [timeMillis: 1536764270563] [levelValue: 800] [[
  file:/Users/pdurbin/NetBeansProjects/dataverse/target/dataverse-4.9.2/WEB-INF/classes/_VDCNet-ejbPU logout successful]]

[2018-09-12T10:57:50.567-0400] [glassfish 4.1] [INFO] [] [javax.enterprise.system.container.ejb.org.glassfish.ejb.persistent.timer] [tid: _ThreadID=44 _ThreadName=admin-listener(1)] [timeMillis: 1536764270567] [levelValue: 800] [[
  No timers to be deleted for id: 100713350386548736]]

[2018-09-12T10:57:50.571-0400] [glassfish 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=44 _ThreadName=admin-listener(1)] [timeMillis: 1536764270571] [levelValue: 1000] [[
  Exception while loading the app : EJB Container initialization error
java.lang.ExceptionInInitializerError
	at edu.harvard.iq.dataverse.validation.PasswordValidatorServiceBean.<init>(PasswordValidatorServiceBean.java:102)
	at edu.harvard.iq.dataverse.validation.__EJB31_Generated__PasswordValidatorServiceBean__Intf____Bean__.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.sun.ejb.containers.BaseContainer.instantiateOptionalEJBLocalBusinessObjectImpl(BaseContainer.java:3866)
	at com.sun.ejb.containers.StatelessSessionContainer.initializeHome(StatelessSessionContainer.java:237)
	at com.sun.ejb.containers.StatelessContainerFactory.createContainer(StatelessContainerFactory.java:63)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:221)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:291)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:99)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:206)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:313)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.MissingResourceException: Can't find bundle for base name Bundle, locale en
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1082)
	at edu.harvard.iq.dataverse.util.BundleUtil.getStringFromBundle(BundleUtil.java:47)
	at edu.harvard.iq.dataverse.util.BundleUtil.getStringFromBundle(BundleUtil.java:23)
	at edu.harvard.iq.dataverse.validation.GoodStrengthRule.<clinit>(GoodStrengthRule.java:18)
	... 54 more
]]
```

Please advise. Thanks!

**Comment by juancorr** [comment]
Hi @pdurbin and @JayanthyChengan,

  you can copy the Bundle.properties file to Bundle_en.properties if you
want to check it. I have thought open some little issues and suggestions
after finish the check (tomorrow or Friday).

Bests,

Juan

**Comment by JayanthyChengan** [comment]
Thanks @pdurbin and @juancorr .

@pdurbin : Hmm, I am not able to recreate the error at my end, not sure whether I am missing anything.  If the bundle for corresponding locale is not found, the application should pick the default bundle property ( bundle.properties).  Could you please give me more details, if possible?  Thanks

**Comment by pdurbin** [comment]
@JayanthyChengan maybe the best thing would be for us to both run `vagrant up` and compare results. As part of this effort, we should update the installation process to capture any additional steps that are now necessary. If you look at the `Vagrantfile` in the root of the repo, you will find the scripts it calls which ultimately call the main `install` script. I can help you with this. I'm going to guess that if you run `vagrant up` you will see a similar stace trace. Can you please confirm this? More instructions about Vagrant can be found at http://guides.dataverse.org/en/4.9.2/developers/tools.html#vagrant

The idea is that if we both use Vagrant our environments will be identical.

(We could use Docker instead of Vagrant if you want but to me Vagrant is a more tried and true tool than Docker.)

@juancorr I did try copying the bundle files to various places...

- cp src/main/java/Bundle.properties src/main/java/Bundle_en.properties
- cp src/main/java/Bundle.properties /tmp/lang/Bundle_en.properties

... but it didn't seem to help.

Again, any new steps need to be captured in the installation process, the installation scripts. I hope this makes sense.

**Comment by JayanthyChengan** [comment]
I haven't tried vagrant or docker before.  I will try to install vagrant and set it up soon.  thanks

**Comment by juancorr** [comment]
I have not used vagrant yet, I am testing the develop branch.

  Now, I cannot reproduce the exception, but I have seen it yesterday and
the English language is not accesible without the Bundle_en.properties .

  Bundle files are in the code under src/main/java/. In glassfish, under
glassfish/domains/domain1/applications/dataverseXXXX/WEB-INF/classes/

  I have removed the Bundle_en.properties file from my installation to
search the exception and I have restarted the glassfish. Now, English
version is not accesible, but I have not the MissingResourceException.

  In my faces-config.xml file, I have
    <application>
       <resource-bundle>
           <base-name>Bundle</base-name>
           <var>bundle</var>
       </resource-bundle>
       <locale-config>
           <default-locale>en</default-locale>
           <supported-locale>fr</supported-locale>
           <supported-locale>es</supported-locale>
       </locale-config>
   </application>

  And I have executed the curl command
 curl http://localhost:8080/api/admin/settings/:Languages -X PUT -d '[{
"locale":"en", "title":"English"}, { "locale":"fr", "title":"Français"}, {
"locale":"es", "title":"Español"}]'

  The URL of our test environment is http://oaimadrono.uned.es:8080/

**Comment by pameyer** [comment]
On 3a25fc7ddaccc37776e0583ca466da326eacfeee ; I see the same exception @pdurbin reported in https://github.com/IQSS/dataverse/issues/4892#issuecomment-420681045 with `setupIT.bash` in docker-aio.  Normal installer also fails with same exception trace.

From a (very brief) look at the code, I'm wondering if this could be due to `LocalBundle.java` assuming that there `dataverse.lang.directory` and passing `URLClassLoader(null)` (or something else related to not using a default when an additional localization bundle isn't configured).

**Comment by JayanthyChengan** [comment]
@pameyer : 
A quick question, did you set the below jvm options in your environment?
/usr/local/glassfish4/glassfish/bin/asadmin create-jvm-options "-Ddataverse.lang.directory=/tmp/lang"

and copied bundle property files to that location.  Thanks

**Comment by pameyer** [comment]
@JayanthyChengan No - which is part of why I'm suspecting that it's not failing over to default behaviour cleanly.

If the plan is for this is going to be a required setting, I'd suggest it not default to '/tmp'.

**Comment by pameyer** [comment]
@JayanthyChengan b5972b0 fixes the exceptions I was seeing, and things appear to deploy normally.

**Comment by JayanthyChengan** [comment]
@pameyer : Thanks for your comments.

@pdurbin : I was able to recreate the issue ( java.util.MissingResourceException: Can't find bundle for base name Bundle, locale en ) in my local environment, when I removed the directory from the file location( in my case /tmp/lang - I guess we can change it to /tmp in the java files as @pameyer 
 suggests) .  To handle the exception, I added the condition in BundleUtil.java and LocalBundle.java, to get the default english files from the Dataverse Application - if the directory specified in "dataverse.lang.directory" doesnot exists in the file system.

**Comment by JayanthyChengan** [comment]
Thanks @pdurbin

**Comment by juancorr** [comment]
Hi @JayanthyChengan  and @pdurbin ,
  We have found two translation issues:

  - One little issue related with French translation, there are utf-8 characters without the \u codification in the ValidationMessages_fr.properties file.

  - Another bug more important. Identification is not possible to a user with the interface in a not English language because the BuiltinAuthenticationProvider.java . You can check it in https://dev1.dataverse.org with a browser that go to the loginpage.xhtml in French before visit this page in English.

**Comment by pdurbin** [comment]
@juancorr good catch on the "can't log in" bug. Here's part of a stace trace:

`at edu.harvard.iq.dataverse.LoginPage.login(LoginPage.java:171)`

`at edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean.getUpdateAuthenticatedUser(AuthenticationServiceBean.java:346)`

`Caused by: java.lang.NullPointerException
	at org.passay.DictionarySubstringRule.doWordSearch(DictionarySubstringRule.java:35)
	at org.passay.AbstractDictionaryRule.validate(AbstractDictionaryRule.java:79)
	at org.passay.PasswordValidator.validate(PasswordValidator.java:59)
	at edu.harvard.iq.dataverse.validation.PasswordValidatorServiceBean.validate(PasswordValidatorServiceBean.java:160)`

The line numbers above are from d00d57b on the 4410-dataset-linking branch, which is what that dev1 server happens to be running.  We should figure out if this bug exists in the "develop" branch as well.

**Comment by juancorr** [comment]
Yes,
  the bug exists in develop branch. Problem is related to the way of work
with credentials:

  In the BuiltinAuthenticationProvider class, credentials are translated:
       KEY_USERNAME_OR_EMAIL = BundleUtil.getStringFromBundle(
"login.builtin.credential.usernameOrEmail");
       KEY_PASSWORD = BundleUtil.getStringFromBundle(
"login.builtin.credential.password");
       CREDENTIALS_LIST = Arrays.asList(new
Credential(KEY_USERNAME_OR_EMAIL), new Credential(KEY_PASSWORD, true));

  Previous list is shown in the loginpage.xhtml:
<ui:repeat id="credentialsContainer" value="#{LoginPage.filledCredentials}"
var="fc">
  <div class="form-group text-left">
    <label class="col-sm-4 control-label" for="credValue">
      #{fc.credential.title}
    </label>
    <div class="col-sm-8">
      <h:inputText rendered="#{not fc.credential.secret}" value=
"#{fc.value}" id="credValue" styleClass="form-control"/>
      <p:message rendered="#{not fc.credential.secret}" for="credValue"
display="text"/>
      <h:inputSecret rendered="#{fc.credential.secret}" value="#{fc.value}"
id="sCredValue" styleClass="form-control"/>
      <p:message rendered="#{not fc.credential.secret}" for="sCredValue"
display="text"/>
    </div>
  </div>
</ui:repeat>



Juan Corrales

**Comment by pdurbin** [comment]
@juancorr ok, thanks. Do you mind creating an issue for this? Otherwise I can do it.

**Comment by pdurbin** [comment]
@juancorr which commit on the "develop" branch are you testing? I just switched my dev1 server to cb07a1b on "develop" and I can no longer reproduce the "Can't log in while in French" bug. So I guess I won't open an issue. But if you can reproduce it, please go ahead and open and issue and please note which commit you are on. Thanks!

**Comment by juancorr** [comment]
Thank you @pdurbin,

  you are right, now I have checked with the dd4ba227c and it works.
  Bests,

Juan

**Comment by djbrooke** [comment]
Hi @JayanthyChengan! We're ready to QA this and some initial documentation would be helpful. I think a short piece about how Internationalization is implemented in Dataverse and adding the specific jvm option would do it, but other team members may suggest other areas as well. Is this something you can add? Also let me know if there's something that was included in a previous PR that I'm missing. Thanks!

**Comment by JayanthyChengan** [comment]
@djbrooke : added docs for the JVM option in this commit : https://github.com/IQSS/dataverse/pull/5023/commits/50dd7b6b563e8482fa21f81c07ece18660d70bce

Setting this JVM option and copying all the files should work.  Let me know, if I need to add any other documentation.

**Comment by kcondon** [comment]
@JayanathyChengan In testing the lang file setting, I renamed the Bundle* files in the war file to .bak to confirm the application was not reading from them and put the files in /tmp/lang, with jvm option:         <jvm-options>-Ddataverse.lang.directory=/tmp/lang</jvm-options>

However, when I restarted glassfish I ended up with this error when going to the homepage:

HTTP Status 500 - Internal Server Error
type Exception report

messageInternal Server Error

descriptionThe server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: /dataverse_template.xhtml @49,55 <f:loadBundle basename="Bundle"> Can't find bundle for base name Bundle, locale en
root cause

javax.faces.view.facelets.TagAttributeException: /dataverse_template.xhtml @49,55 <f:loadBundle basename="Bundle"> Can't find bundle for base name Bundle, locale en
root cause

java.util.MissingResourceException: Can't find bundle for base name Bundle, locale en
note The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 4.1 logs.


I realize renaming the bundle files in the app might be unexpected but isn't the purpose of moving these files so that the app does not read them? Have I missed something obvious?

Thanks for any information. Otherwise things are working ok.:q

**Comment by kcondon** [comment]
@JayanthyChengan Update:
It looks like renaming the french properties file is ok but not the default (en). However, if I keep the default in place and edit the contents of the moved default (en) file, those modifications do appear in the application, indicating it is referencing that file for content/strings.

So, I'm not sure whether there is some glassfish startup dependency on Bundle.properties being there and then it can look elsewhere for the app.

**Comment by JayanthyChengan** [comment]
@kcondon : Yes, english bundle.properties should be in the app. Since maven tests also depends on it too.

In this issue, we are testing only the bundle.properties outside the app.  

MimeType is handled in separate issue : https://github.com/IQSS/dataverse/issues/5055

ValidationMessages : https://github.com/IQSS/dataverse/issues/5040
