### ISSUE TITLE
Can't log in in French

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#5090]
By pulling the latest commits on develop branch (93cd4da28cffcc90fad852b340a7c8b0d184d18b), I ran into a login problem.
Here is the usecase:
- Going to the login page (and be pleasantly surprised by the french text)
- Enter login and password
- Nothing happens

On Glassfish logs, we can see this:

```
[2018-09-25T17:56:37.902+0200] [glassfish 4.1] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=28 _ThreadName=http-listener-1(3)] [timeMillis: 1537890997902] [levelValue: 1000] [[
  javax.faces.el.EvaluationException: javax.ejb.EJBTransactionRolledbackException
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ejb.EJBTransactionRolledbackException
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2342)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2123)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy493.validate(Unknown Source)
	at edu.harvard.iq.dataverse.validation.__EJB31_Generated__PasswordValidatorServiceBean__Intf____Bean__.validate(Unknown Source)
	at edu.harvard.iq.dataverse.authorization.providers.builtin.BuiltinAuthenticationProvider.authenticate(BuiltinAuthenticationProvider.java:119)
	at edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean.getUpdateAuthenticatedUser(AuthenticationServiceBean.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:46)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy545.getUpdateAuthenticatedUser(Unknown Source)
	at edu.harvard.iq.dataverse.authorization.__EJB31_Generated__AuthenticationServiceBean__Intf____Bean__.getUpdateAuthenticatedUser(Unknown Source)
	at edu.harvard.iq.dataverse.LoginPage.login(LoginPage.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:289)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
	... 44 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:662)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:507)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	... 94 more
Caused by: java.lang.NullPointerException
	at org.passay.DictionarySubstringRule.doWordSearch(DictionarySubstringRule.java:35)
	at org.passay.AbstractDictionaryRule.validate(AbstractDictionaryRule.java:79)
	at org.passay.PasswordValidator.validate(PasswordValidator.java:59)
	at edu.harvard.iq.dataverse.validation.PasswordValidatorServiceBean.validate(PasswordValidatorServiceBean.java:160)
	at edu.harvard.iq.dataverse.validation.PasswordValidatorServiceBean.validate(PasswordValidatorServiceBean.java:135)
	at edu.harvard.iq.dataverse.validation.PasswordValidatorServiceBean.validate(PasswordValidatorServiceBean.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:46)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 92 more
]]
```

I added some logs to understand what's happening, and it seems that the validate method receive a null password, which introduce some problems for authentication.

It seems somebody else (irc: tcoupin) had run into the same problem and had a talk with the dataverse team to solve it. I will let them explain the problem and the solution, cause my dev env is still broken :D

**Comment by pdurbin** [comment]
@rmo-cdsp thanks for opening this issue and for chatting about it at http://irclog.iq.harvard.edu/dataverse/2018-09-25 . I just took the liberty of renaming it to the phrase I was using in standup last week, which was "Can't log in in French" because that's how I was able to reproduce it https://github.com/IQSS/dataverse/issues/4892#issuecomment-422417899 but I wasn't able to reproduce it again a day later on the latest commit from develop. And yes, I think it's the same issue @tcoupin reported today in IRC. He sent use a stack trace, which can be downloaded from https://help.hmdc.harvard.edu/Ticket/Display.html?id=267442 . In IRC he mentioned a `LANG=C` fix. We definitely want to get you unblocked @rmo-cdsp , so you can work on #4593 or any other issues you like!

**Comment by tcoupin** [comment]
@rmo-cdsp Thanks for opening issue for me ;-)
My system local is fr so I use `LANG=G mvn package` instead of just `mvn package`

**Comment by rmo-cdsp** [comment]
I tried the LANG=C fix, but it changes nothing. I can't log, and the logs are the same. Am I missing something ?
I did : LANG=C mvn package
I undeployed and deployed the new war generated, also restarted the glassfish domain.

**Comment by pdurbin** [comment]
@rmo-cdsp are you using the new ":Languages" database setting? As documented at https://github.com/IQSS/dataverse/blob/d0cb4021a9396e6ac47aef97910abe028fa49510/doc/sphinx-guides/source/installation/config.rst#languages you can run a curl command like this:

`curl http://localhost:8080/api/admin/settings/:Languages -X PUT -d '[{ "locale":"en", "title":"English"}, { "locale":"fr", "title":"Français"}]'`

Then you have to restart Glassfish.

Then, in my case, I was able to log in from English rather than French. But again, on a newer commit I wasn't able to reproduce this bug at all.

**Comment by rmo-cdsp** [comment]
I still had the problem, even by using mvn package with LANG=C, and even by using the command @pdurbin gave.
But I found a way to "fix" the problem, by using some commands to deploy the war. But, be careful, because if you ever stop and start glassfish, the problem reappears ! I don't know why, but the same problem with the password validation persist (the error in the first post of the issue).
So, here is what I did to make it work again (your paths may diverge, of course, and be careful with your rights too):
/usr/local/glassfish4/bin/asadmin undeploy dataverse-4.9.4
/usr/local/glassfish4/glassfish/bin/asadmin stop-domain
rm -rf /usr/local/glassfish4/glassfish/domains/domain1/generated/
/usr/local/glassfish4/glassfish/bin/asadmin start-domain
/usr/local/glassfish4/bin/asadmin deploy /home/rmo/Documents/dataverse/dataverse2/dataverse/target/dataverse-4.9.4.war
/usr/local/glassfish4/glassfish/bin/asadmin stop-domain
/usr/local/glassfish4/glassfish/bin/asadmin start-domain
/usr/local/solr/solr-7.3.0/bin/solr stop
cp /home/rmo/Downloads/schema.xml /usr/local/solr/solr-7.3.0/server/solr/collection1/conf/
/usr/local/solr/solr-7.3.0/bin/solr start -force
curl -X DELETE http://localhost:8080/api/admin/index/timestamps
curl http://localhost:8080/api/admin/index/continue

After that, everything should be fixed. If I stop at the deploy and restart, I still has the problem, so I have to do the rest. Also, if I try to log during the procedure, it seems that at the end, it won't work. A very very very strange behaviour here.

**Comment by pdurbin** [comment]
@rmo-cdsp thanks for the update and the chatter in IRC.

@tcoupin are you still having this problem?

**Comment by tcoupin** [comment]
I upgrade my test server to 4.9.4 with provided war on release page and still have this issue.
Running curl has no effect, expect the language selector but the login form was still in french.
Manually remove bundles except the english one fix the log in form:
`rm -r GLASSFISH_PATH/glassfish4/glassfish/domains/domain1/applications/dataverse-4.9.4/WEB-INF/classes/Bundle_*`

**Comment by juancorr** [comment]
Sorry @pdurbin, now I can't reproduce the bug and I have not understand
the authentification code, but perhaps there are some clues in the code:

BuiltinAuthenticationProvider (credentials are translated):

        KEY_USERNAME_OR_EMAIL =
BundleUtil.getStringFromBundle("login.builtin.credential.usernameOrEmail");
        KEY_PASSWORD =
BundleUtil.getStringFromBundle("login.builtin.credential.password");
        CREDENTIALS_LIST = Arrays.asList(new
Credential(KEY_USERNAME_OR_EMAIL), new Credential(KEY_PASSWORD, true));


AuthenticationServiceBean (Singleton class):
        AuthenticationRequest authReq = new AuthenticationRequest();
        /**
         * @todo Should this really be coming from a bundle like this? Added
         * because that's what BuiltinAuthenticationProvider does.
         */

authReq.putCredential(BundleUtil.getStringFromBundle("login.builtin.credential.usernameOrEmail"),
username);

authReq.putCredential(BundleUtil.getStringFromBundle("login.builtin.credential.password"),
password);


I have obtained the exception, after replace the Bundle.properties
authentification entries with the Bundle_fr.properties ones:
In Bundle.properties:
login.builtin.credential.usernameOrEmail=Nom d'utilisateur/courriel
login.builtin.credential.password=Mot de passe

Juan

**Comment by pdurbin** [comment]
GitHub issues and pull requests seem a little broken right now ( https://blog.github.com/2018-10-21-october21-incident-report/ ) but I can see that @tcoupin tried to make a pull request and his fix at https://github.com/IQSS/dataverse/compare/develop...tcoupin:fix-5090 makes sense.
