### ISSUE TITLE
Harvesting OAI with URL identifier fail

### ISSUE THREAD

**Issue by tcoupin** [IQSS/dataverse#5245]
Where an OAI server uses url identifier (http://doi.org/...), Dataverse fail to parse globalId.

Log:
```
[2018-10-30T10:22:14.276+0000] [glassfish 4.1] [FINE] [] [edu.harvard.iq.dataverse.api.imports.ImportServiceBean] [tid: _ThreadID=155 _ThreadName=__ejb-thread-pool7] [timeMillis: 1540894934276] [levelValue: 500] [CLASSNAME: edu.harvard.iq.dataverse.api.imports.ImportServiceBean] [METHODNAME: doImportHarvestedDataset] [[
  importing DC /tmp/meta1606584145857252274.tmp]]

[2018-10-30T10:22:14.278+0000] [glassfish 4.1] [FINE] [] [edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean] [tid: _ThreadID=155 _ThreadName=__ejb-thread-pool7] [timeMillis: 1540894934278] [levelValue: 500] [CLASSNAME: edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean] [METHODNAME: processXMLElement] [[
  entering processXMLElement; (:)]]

[2018-10-30T10:22:14.286+0000] [glassfish 4.1] [FINE] [] [edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean] [tid: _ThreadID=155 _ThreadName=__ejb-thread-pool7] [timeMillis: 1540894934286] [levelValue: 500] [CLASSNAME: edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean] [METHODNAME: processOAIDCxml] [[
  Imported identifier: https://doi.org/10.5072/FK2/YIX6QZ]]

[2018-10-30T10:22:14.287+0000] [glassfish 4.1] [FINE] [] [edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean] [tid: _ThreadID=155 _ThreadName=__ejb-thread-pool7] [timeMillis: 1540894934287] [levelValue: 500] [CLASSNAME: edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean] [METHODNAME: reassignIdentifierAsGlobalId] [[
  Processing DOI identifier formatted as a resolver URL: https://doi.org/10.5072/FK2/YIX6QZ]]

....

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -10
        at java.lang.String.substring(String.java:1967)
        at edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean.reassignIdentifierAsGlobalId(ImportGenericServiceBean.java:434)
        at edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean.processOAIDCxml(ImportGenericServiceBean.java:225)
        at sun.reflect.GeneratedMethodAccessor1075.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)

```

PR to come...

**Comment by tcoupin** [comment]
Happy new year! 

Still work nedded?

**Comment by poikilotherm** [comment]
Maybe @pdurbin could move this to Code Review again? The failing IT tests seem to have been worked out recently...

**Comment by pdurbin** [comment]
@tcoupin hi! Before I move this to code review, can you please merge the latest from "develop" into your branch? We released 4.10. Thanks!

**Comment by pdurbin** [comment]
@tcoupin on second thought, I went ahead and moved this issue to code review but if you could please merge the latest from develop into your branch soon it would be appreciated.

**Comment by landreev** [comment]
I see, this was introduced in May - when .lastIndexOf('/') was changed to .indexOf('/') in line 362... Which I'm assuming was done to fix another problem... OK, so these are all consequences of switching to treating the DOI "shoulder" as part of the identifier...

**Comment by landreev** [comment]
OK, this PR fixes the problem at hand, so I'm moving this along as soon as the branch is merged w/ develop. 
But, looking at the rest of the code as it is now, it appears that we now assume that there can never be a '/' separator in the authority part of the identifier... I'm wondering if this is a safe assumption (with handles especially?).

**Comment by tcoupin** [comment]
Assuming http://www.handle.net/tech_manual/HN_Tech_Manual_9.pdf, page 6:
![image](https://user-images.githubusercontent.com/7457386/50764902-77fbae80-1274-11e9-878c-e62e51a8160a.png)
