### ISSUE TITLE
Roles: Defining a custom role results in exception errors when accessing ManagePermissions or My Data pages.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5296]
I think this was introduced with the internationlization changes. When a custom role is defined, accessing either manage permissions or my data page results in an exception:

[2018-11-08T16:05:15.050-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.application] 
[tid: _ThreadID=52 _ThreadName=jk-connector(1)] [timeMillis: 1541711115050] [levelValue: 1000] [[
  Error Rendering View[/permissions-manage.xhtml]
javax.el.ELException: /permissions-manage.xhtml @169,125 value="#{managePermissionsPage.availableRoles}": java.util.
MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key role.mycustomrole.nam
e
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:114)
        at com.sun.faces.facelets.component.UIRepeat.getValue(UIRepeat.java:279)
        at com.sun.faces.facelets.component.UIRepeat.getDataModel(UIRepeat.java:255)
        at com.sun.faces.facelets.component.UIRepeat.setIndex(UIRepeat.java:523)
        at com.sun.faces.facelets.component.UIRepeat.process(UIRepeat.java:577)
        at com.sun.faces.facelets.component.UIRepeat.encodeChildren(UIRepeat.java:1110)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at javax.faces.component.UIForm.visitTree(UIForm.java:371)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322)
        at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:219)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:430)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.el.ELException: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key role.mycustomrole.name
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:368)
        at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
        at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
        at com.sun.el.parser.AstValue.getValue(AstValue.java:140)
        at com.sun.el.parser.AstValue.getValue(AstValue.java:204)
        at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
        at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
        ... 67 more
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key role.mycustomrole.name
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at edu.harvard.iq.dataverse.util.BundleUtil.getStringFromBundleNoMissingCheck(BundleUtil.java:52)
        at edu.harvard.iq.dataverse.util.BundleUtil.getStringFromPropertyFile(BundleUtil.java:66)
        at edu.harvard.iq.dataverse.authorization.DataverseRole.getName(DataverseRole.java:125)
        at edu.harvard.iq.dataverse.authorization.DataverseRole$1.compare(DataverseRole.java:73)
        at edu.harvard.iq.dataverse.authorization.DataverseRole$1.compare(DataverseRole.java:69)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.util.TimSort.sort(TimSort.java:220)
        at java.util.Arrays.sort(Arrays.java:1438)
        at java.util.List.sort(List.java:478)
        at java.util.Collections.sort(Collections.java:175)
        at edu.harvard.iq.dataverse.ManagePermissionsPage.getAvailableRoles(ManagePermissionsPage.java:379)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:363)
        ... 74 more
:

**Comment by kcondon** [comment]
@JayanthyChengan Any ideas on this issue? Thanks

**Comment by JayanthyChengan** [comment]
Noticing a new function getStringFromBundleNoMissingCheck() was added in later stage and it's triggering this error.    

I can modify the method by adding try/catch around it
`
public static String getStringFromPropertyFile(String key, String propertyFileName  ) throws MissingResourceException {
        ResourceBundle bundle = getResourceBundle(propertyFileName);
        return getStringFromBundleNoMissingCheck(key, null, bundle);
    }

to

public static String getStringFromPropertyFile(String key, String propertyFileName  ) {
        ResourceBundle bundle = getResourceBundle(propertyFileName);
        try {
            return getStringFromBundleNoMissingCheck(key, null, bundle);
        } catch (MissingResourceException ex) {
            logger.warning("Could not find key \"" + key + "\" in bundle file: ");
            logger.log(Level.CONFIG, ex.getMessage(), ex);
            return null;
        }
    }`

But there is a testcase in BundleUtilTest.java which fails

`    //To assure that the MissingResourceException bubble up from this call
    @Test(expected = MissingResourceException.class)
    public void testStringFromPropertyFileException() {
        BundleUtil.getStringFromPropertyFile("FAKE","MimeTypeFacets");
    }`

**Comment by sekmiller** [comment]
Hi @JayanthyChengan I just put the try catch around the getName and getDescription methods on DataverseRole. It fixes the custom roles page in the same way that FileUtil handles exceptions. And the BundleUtilTest passes without any changes. Does this look ok to you?

**Comment by JayanthyChengan** [comment]
@sekmiller - Yes, I see that it fixes the exception.   

But soon, I will create a separate issue and remove the logic from getter methods in DataverseRole.java  
Please refer to this comment https://github.com/IQSS/dataverse/pull/5111#pullrequestreview-172152719 in my other PR.

Thanks
