### ISSUE TITLE
As a developer, I want IQSS Jenkins to work

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5602]
I'm code reviewing the 3925-tooltip-icons branch (#3925) and since the Style Guide seems to have changed significantly, I thought I'd create a job in Jenkins to build it. Unfortunately, I was greeted with this error:

![screen shot 2019-03-05 at 12 54 05 pm](https://user-images.githubusercontent.com/21006/53826196-19864000-3f46-11e9-9c20-662db4988ad5.png)

Additionally, I noticed that I can't run API tests on Jenkins. This worked last week on Feb 28:

![screen shot 2019-03-05 at 12 57 36 pm](https://user-images.githubusercontent.com/21006/53826283-46d2ee00-3f46-11e9-89d2-df4ab7997f32.png)

@landreev @djbrooke and I talked about this after standup and I pointed out the following stacktrace at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-build-develop/365/console  (the failed phoenix job above):

FATAL: Could not initialize class sun.nio.fs.LinuxNativeDispatcher

```
FATAL: Could not initialize class sun.nio.fs.LinuxNativeDispatcher
java.lang.NoClassDefFoundError: Could not initialize class sun.nio.fs.LinuxNativeDispatcher
	at sun.nio.fs.LinuxUserDefinedFileAttributeView.copyExtendedAttributes(LinuxUserDefinedFileAttributeView.java:291)
	at sun.nio.fs.LinuxFileSystem.copyNonPosixAttributes(LinuxFileSystem.java:72)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:267)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at hudson.FilePath$CopyRecursiveLocal$1.tryCopyWithAttributes(FilePath.java:2489)
	at hudson.FilePath$CopyRecursiveLocal$1.visit(FilePath.java:2474)
	at hudson.util.DirScanner.scanSingle(DirScanner.java:44)
	at hudson.FilePath$ExplicitlySpecifiedDirScanner.scan(FilePath.java:3166)
	at hudson.FilePath$CopyRecursiveLocal.invoke(FilePath.java:2465)
	at hudson.FilePath$CopyRecursiveLocal.invoke(FilePath.java:2449)
	at hudson.FilePath.act(FilePath.java:1078)
	at hudson.FilePath.act(FilePath.java:1061)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2397)
	at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:61)
	at hudson.maven.MavenBuild$ProxyImpl.performArchiving(MavenBuild.java:512)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:881)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

@djbrooke said he'd gather more info.

**Comment by pdurbin** [comment]
Java was updated which seemed to cause the failures.

We got in touch with the Ops team and they restarted Jenkins.

Now I can run the phoenix API test suite.

I was also able to close a Sphinx job to create http://guides.dataverse.org/en/3925-tooltip-icons/style/patterns.html
