### ISSUE TITLE
unable to rename or delete an empty dataverse

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#5777]
Running v. 4.11 build 1236-3721306 on RedHat7.  I'm unable to either rename or (as last resort) delete an empty dataverse. I tried renaming a dataverse this morning so it would be fresh in the server log.
I've added the glassfish server log and the solr log.

[glassfish-server.log](https://github.com/IQSS/dataverse/files/3104541/glassfish-server.log)

![dataverse-rename-issue](https://user-images.githubusercontent.com/229689/56519044-dc760d00-64f5-11e9-895e-432251868c7a.png)

Solr log also had an warning - not sure if this is related:
Caused by: java.lang.UnsatisfiedLinkError: no nio in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at sun.nio.fs.UnixCopyFile$2.run(UnixCopyFile.java:612)
        at sun.nio.fs.UnixCopyFile$2.run(UnixCopyFile.java:609)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.nio.fs.UnixCopyFile.<clinit>(UnixCopyFile.java:609)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at org.apache.lucene.store.FSDirectory.rename(FSDirectory.java:297)
        at org.apache.lucene.store.NRTCachingDirectory.rename(NRTCachingDirectory.java:168)
        at org.apache.lucene.store.LockValidatingDirectoryWrapper.rename(LockValidatingDirectoryWrapper.java:56)
        at org.apache.lucene.index.SegmentInfos.finishCommit(SegmentInfos.java:792)
        at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:3498)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3466)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3423)
        at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:684)
        at org.apache.solr.update.processor.RunUpdateProcessor.processCommit(RunUpdateProcessorFactory.java:93)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processCommit(UpdateRequestProcessor.java:68)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalCommit(DistributedUpdateProcessor.java:1924)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.processCommit(DistributedUpdateProcessor.java:1900)
        at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processCommit(LogUpdateProcessorFactory.java:160)
        at org.apache.solr.handler.RequestHandlerUtils.handleCommit(RequestHandlerUtils.java:69)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:62)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:195)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2503)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:711)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:517)
        ... 35 more

If needed I'd also upload the solr.log but it's really large - 32M.

Thank you,

Jamie

**Comment by pdurbin** [comment]
@jmjamison huh. Very strange. Have you tried reinstalling Solr? Here are the instructions for Dataverse 4.11: http://guides.dataverse.org/en/4.11/installation/prerequisites.html#solr

**Comment by jmjamison** [comment]
It was odd that the rename worked on test.   I'll try reinstalling Solr and post what happens.

**Comment by jmjamison** [comment]
Also, is there any place that lists what level what the various software parts - ie. solr, postgresql, etc - should be at?

**Comment by pdurbin** [comment]
@jmjamison well, when the version matters we say so but I guess the information is somewhat spread out. I don't think the version of jq, matters, for example. Usually when we first mention the software in the guides, we'll indicate a version if we need to. Please see the "Prerequisites" page above.

**Comment by jmjamison** [comment]
You're right.  I should have checked that.  All the same for newbies it would help to have a list on the releases page.

**Comment by pdurbin** [comment]
@jmjamison hi! Did reinstalling Solr help?

**Comment by jmjamison** [comment]
While upgrading to 4.12 (and then 4.13) I had to reindex solr.  The problem seems fixed.

**Comment by pdurbin** [comment]
@jmjamison thanks for following up. This was a weird one.
