### ISSUE TITLE
As a dataverse developer who likes code, I can not deploy `develop` branch

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#5914]
```
Severe:   Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton StartupFlywayMigrator
    at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:649)
...
Caused by: javax.ejb.CreateException: Initialization failed for Singleton StartupFlywayMigrator
    at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:476)
...
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration version 4.14.0.1
-> Applied to database : -703027202
-> Resolved locally    : 2019772659
    at org.flywaydb.core.Flyway.doValidate(Flyway.java:1482)
...
Severe:   Exception during lifecycle processing
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton StartupFlywayMigrator
...
Severe:   Exception while loading the app
Severe:   Undeployment failed for context
Info:   file:/Users/mheppler/NetBeansProjects/dataverse/target/dataverse-4.14/WEB-INF/classes/_VDCNet-ejbPU logout successful
Info:   No timers to be deleted for id: 102213927065747456
Severe:   Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton StartupFlywayMigrator
javax.ejb.CreateException: Initialization failed for Singleton StartupFlywayMigrator
    at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:476)
```

Seems highly related to 7e612be7bdb99ba589a2e66ea2bffcdc6a4c9beb.

**Comment by pdurbin** [comment]
I believe @sekmiller also saw "Migration checksum mismatch" recently but he ended up switching to a fresh empty database.

I wonder if we should add the ability to run `mvn flyway:repair`. I got this idea from googling for the error and finding https://stackoverflow.com/questions/41147768/caused-by-org-flywaydb-core-api-flywayexception-validate-failed-migration-che/50718584#50718584

**Comment by pdurbin** [comment]
@mheppler I wonder if something like this would work for you.

First you have to download flyway-commandline-5.2.4-macosx-x64.tar.gz from https://flywaydb.org/documentation/commandline/

Then you could try running a "repair" like this:

```
$ ./flyway repair -url=jdbc:postgresql://localhost:5432/dvndb
Database user: dvnapp
Database password: 
Flyway Community Edition 5.2.4 by Boxfuse
Database: jdbc:postgresql://localhost:5432/dvndb (PostgreSQL 9.6)
Repair of failed migration in Schema History table "public"."flyway_schema_history" not necessary. No failed migration detected.
Successfully repaired schema history table "public"."flyway_schema_history" (execution time 00:00.017s).
```

I tried getting `mvn flyway:repair` to work, by the way, but I couldn't get it to find the driver we're using (postgresql-42.2.2.jar).

**Comment by poikilotherm** [comment]
Once on Payara 5, we can include the driver in the WAR and it will be usable for resources on the app server "level", too.

**Comment by mheppler** [comment]
@landreev assisted in a workaround, manually deleting a row in the flyway db table. I am going to close this. Feel free to reopen if there is something to fix here.
