### ISSUE TITLE
publishing failing on phoenix server, API test suite down

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6172]
On 860d53e I tried to run the phoenix tests but the failed because publishing isn't working.

![Screen Shot 2019-09-16 at 4 45 23 PM](https://user-images.githubusercontent.com/21006/64992301-9acd7080-d8a1-11e9-81b2-4d6d70f04e93.png)

Caused by: java.lang.RuntimeException: Response code: 403, Access is denied
	at edu.harvard.iq.dataverse.DataCiteRESTfullClient.postMetadata(DataCiteRESTfullClient.java:190)
	at edu.harvard.iq.dataverse.DOIDataCiteRegisterService.registerIdentifier(DOIDataCiteRegisterService.java:110)

[2019-09-16T16:44:16.259-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=50 _ThreadName=jk-connector(1)] [timeMillis: 1568666656259] [levelValue: 1000] [[
  This dataset may not be published due to an error when contacting the <a href=http://status.datacite.org target="_blank"/> DataCite </a> Service. Please try again.]]

![Screen Shot 2019-09-16 at 4 45 20 PM](https://user-images.githubusercontent.com/21006/64992300-9acd7080-d8a1-11e9-99b4-fe52e83818b1.png)

**Comment by landreev** [comment]
Note that this is a DataCite error, and Phoenix is supposed to be using "FAKE" registration provider: 
```
$ grep FAKE scripts/deploy/phoenix.dataverse.org/*
scripts/deploy/phoenix.dataverse.org/post:curl http://localhost:8080/api/admin/settings/:DoiProvider -X PUT -d FAKE
```

So this is likely the result of #6173 that I just opened. 
(I'm using the API line above as an example there)

Datasets created by the "sample data" scripts are not getting published for the same reason on instances build from the develop branch.

**Comment by djbrooke** [comment]
Closing as a duplicate (symptom?) of #6173.
