### ISSUE TITLE
Test install in VirtualBox - No dataverse or dataset creation possible

### ISSUE THREAD

**Issue by tjouneau** [IQSS/dataverse#6393]
Hi
I'm currently testing Dataverse 4.18 build 253-118aa71 into a CentOS 7 virtual machine under VirtualBox running on Windows.
I followed every step on the Prerequisites and Install pages and wanted to get a good idea of the software and its capabilities before going a little further on real servers.
Running the software and logging in went fine. 
Trying to create a dataverse results in the following message
_This dataverse was not able to be created. – Please contact Root Support for assistance. Date/Time: 2019-11-21 13:42:56 Server: localhost_ 
Trying to create a dataset results in almost the same
_Error – The dataset could not be created. If you believe this is an error, please contact Root Support for assistance._
_Page Not Found - The page you are looking for was not found. If you believe this is an error, please contact Root Support for assistance._
I'm attaching the glassfish log for reference.
I checked issue #4427 and the solr schema*.xml files are those provided with dvinstall.
What did I possibly miss?
Thanks!
[server.log](https://github.com/IQSS/dataverse/files/3875632/server.log)

Thank you for contributing an issue to the Dataverse Project! If this is a bug report, please let us know when the issue occurs, which page it occurs on, to whom it occurs, and which version of Dataverse you're using. If this is a feature request, please let us know what you'd like to see and give us some context - what kind of user is the feature intended for, the relevant use cases, and what inspired the request? No matter the issue, screenshots are always welcome.

**Comment by djbrooke** [comment]
Hi @tjouneau - have you published the root dataverse?

**Comment by pdurbin** [comment]
@tjouneau thank you for the server.log!

All of this noise...

[2019-11-21T14:29:19.975+0100] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=26 _ThreadName=http-listener-1(2)] [timeMillis: 1574342959975] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB IndexServiceBean, method: public java.util.concurrent.Future edu.harvard.iq.dataverse.search.IndexServiceBean.indexDataset(edu.harvard.iq.dataverse.Dataset,boolean) throws org.apache.solr.client.solrj.SolrServerException,java.io.IOException]]

[2019-11-21T14:29:19.975+0100] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=26 _ThreadName=http-listener-1(2)] [timeMillis: 1574342959975] [levelValue: 900] [[
  
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
...
	at edu.harvard.iq.dataverse.search.__EJB31_Generated__IndexServiceBean__Intf____Bean__.indexDataset(Unknown Source)
	at edu.harvard.iq.dataverse.engine.command.impl.AbstractCreateDatasetCommand.execute(AbstractCreateDatasetCommand.java:136)
	at edu.harvard.iq.dataverse.engine.command.impl.AbstractCreateDatasetCommand.execute(AbstractCreateDatasetCommand.java:28)
	at edu.harvard.iq.dataverse.EjbDataverseEngineInner.submit(EjbDataverseEngineInner.java:36)
...
	at edu.harvard.iq.dataverse.__EJB31_Generated__EjbDataverseEngineInner__Intf____Bean__.submit(Unknown Source)
	at edu.harvard.iq.dataverse.EjbDataverseEngine.submit(EjbDataverseEngine.java:256)
...
	at java.lang.Thread.run(Thread.java:748)

```
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/collection1: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/collection1/select. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
```
...	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:607)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:255)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:244)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:194)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:942)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:957)
	at edu.harvard.iq.dataverse.search.IndexServiceBean.findFilesOfParentDataset(IndexServiceBean.java:1580)
	at edu.harvard.iq.dataverse.search.IndexServiceBean.indexDataset(IndexServiceBean.java:387)
...
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 126 more
]]

... is probably an indication that "collection1" wasn't created, which is this step

    cp -r server/solr/configsets/_default server/solr/collection1

... from http://guides.dataverse.org/en/4.18.1/installation/prerequisites.html#installing-solr 

I'm going to guess that http://localhost:8983/solr/collection1/schema/fields doesn't show any dataset fields. That "fields" endpoint is mentioned at http://guides.dataverse.org/en/4.18.1/developers/tips.html#solr

Here's what I would suggest:

- spin up a fresh CentOS 7 VM in VirtualBox
- install ansible (via yum) and execute the two commands in the quickstart at https://github.com/IQSS/dataverse-ansible#quickstart
- keep asking questions if you get stuck!
- join us in http://chat.dataverse.org

**Comment by tjouneau** [comment]
Hi
Wow, thanks both for these extra fast answers.
@djbrooke The root Dataverse was indeed unpublished... Shame on me. However publishing it doesn't solve the issue, I still can't seem to be able to create a Dataverse under root.
@pdurbin The command you're pointing at was executed and the directory _default was copied in collection1 under the solr user, as per the instructions. So I don't see an explanation here as well.
I'm going to do as you suggest and try a fresh reinstall through ansible. I'll make another ticket if the issue reappears then.
Thanks!
Thomas
