### ISSUE TITLE
Unable to load "My Data" on production

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#6781]
I have not been able to load My Data in production for several months. 

- Using gmail account

- dvn-cloud-app-1

Kevin got this from the log file:

    [2020-03-31T16:41:41.286-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler]
    [tid: _ThreadID=3520 _ThreadName=jk-connector(107)] [timeMillis: 1585687301286] [levelValue: 1000] [[
    API internal error a04c9666-d233-4158-9d22-147e22bd7ab6: Null Pointer
    java.lang.NullPointerException
    ]]    

    [2020-03-31T16:41:43.683-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.DataverseHeaderFragment] 
    [tid: _ThreadID=3594 _ThreadName=jk-connector(179)] [timeMillis: 1585687303683] [levelValue: 800] [[
    Sending user to = /dataverseuser.xhtml]]

    [2020-03-31T16:41:54.559-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] 
    [tid: _ThreadID=3486 _ThreadName=jk-connector(75)]  [timeMillis: 1585687314559] [levelValue: 900] [[  
    caught IOException trying to open an input stream for worldmap .img file (s3://dvn-cloud:155d1847e11-11f9f553c5ce). 
    Original Error: java.io.IOException: Failed to open auxilary file img for S3 file]]

    [2020-03-31T16:41:55.724-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler] 
    [tid: _ThreadID=3495 _ThreadName=jk-connector(84)] 
    [timeMillis: 1585687315724] [levelValue: 1000] [[
    API internal error 858adef2-f20d-49ab-84bb-4adbd2eb9857: Null Pointer
    java.lang.NullPointerException
    ]]

**Comment by BPeuch** [comment]
I encountered the same problem. We have two Dataverse installations at the State Archives of Belgium, one that is online and one accessible only through our local network. The My Data section displays without problems on the latter but not on the former (regardless of Web browsers).

Paradoxically, it works fine on demo.dataverse.org.

**Comment by shlake** [comment]
Was working until V4.19. UVa just upgraded from 4.16 (did each step, 4.17, 4.18, 4.18.1, 4.19). "My Data" worked until 4.19. 
Doesn't load for me as general user nor as dataverseAdmin.

**Comment by djbrooke** [comment]
@BPeuch @shlake Thanks for the reports. Can you check your logs to see if there's anything similar to what's reported for @TaniaSchlatter above?

**Comment by shlake** [comment]
@djbrooke which logs (files) and what am I (or actually my sysadmin) looking for? I don't have access to the logs, so need to tell my system admin what to info to pull for me.

**Comment by shlake** [comment]
Yep: Here's the beginning:
```
[2020-04-07T15:20:45.814-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler] [tid: _ThreadID=50 _ThreadName=jk-connector(3)] [timeMillis: 1586287245814] [levelValue: 1000] [[
  API internal error 2c5bec76-08ab-4802-be8f-56b6e4b192a0: Null Pointer
java.lang.NullPointerException
```
then a long list of 
```
        at edu.harvard.iq.dataverse.search.SolrSearchResult.json(SolrSearchResult.java:575)
	at edu.harvard.iq.dataverse.search.SolrSearchResult.getJsonForMyData(SolrSearchResult.java:414)
	at edu.harvard.iq.dataverse.mydata.DataRetrieverAPI.formatSolrDocs(DataRetrieverAPI.java:513)
	at edu.harvard.iq.dataverse.mydata.DataRetrieverAPI.retrieveMyDataAsJsonString(DataRetrieverAPI.java:447)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
```

[ PLUS more lines] like this "at.....
UVa is all on local server (database and files) - no cloud.

**Comment by djbrooke** [comment]
Thanks @shlake !

**Comment by pdurbin** [comment]
> (SolrSearchResult.java:575)

Hmm, this line *was* added in 4.19 as part of pull request #6441 but I'm not sure why it would be throwing a NullPointerException: https://github.com/IQSS/dataverse/blob/v4.19/src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java#L575

**Comment by BPeuch** [comment]
Hey @djbrooke. I checked the logs and we also have a "Null Pointer" error. I believe it's the same error messages that Tania and Sherry got…
 
```
[2020-04-09T14:54:33.642+0200] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler] [tid: _ThreadID=26 _ThreadName=http-listener-1(2)] [timeMillis: 1586436873642] [levelValue: 1000] [[
  API internal error 41da6538-fa3a-4528-b466-43ac6b05580c: Null Pointer
java.lang.NullPointerException
	at edu.harvard.iq.dataverse.search.SolrSearchResult.json(SolrSearchResult.java:575)
	at edu.harvard.iq.dataverse.search.SolrSearchResult.getJsonForMyData(SolrSearchResult.java:414)
	at edu.harvard.iq.dataverse.mydata.DataRetrieverAPI.formatSolrDocs(DataRetrieverAPI.java:513)
	at edu.harvard.iq.dataverse.mydata.DataRetrieverAPI.retrieveMyDataAsJsonString(DataRetrieverAPI.java:447)
[…] [more "at…" lines]
```

… with perhaps the exception of this message, but I'm not absolutely sure it's related to displaying the My Data section:

```
[2020-04-09T14:55:18.649+0200] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.mydata.DataRetrieverAPI] [tid: _ThreadID=26 _ThreadName=http-listener-1(2)] [timeMillis: 1586436918649] [levelValue: 1000] [[
  Sorry, nothing was found for these roles: Admin, File Downloader, Dataverse + Dataset Creator, Dataverse Creator, Dataset Creator, Contributor, Curator, Member]]
```

**Comment by djbrooke** [comment]
Thanks @BPeuch, this will help with debugging.

**Comment by BPeuch** [comment]
I think @kaitlinnewson might have found out the origin of the problem our side, as detailed here: https://github.com/IQSS/dataverse/issues/6843. It would explain why we encountered this problem with one Dataverse installation and not another.
