### ISSUE TITLE
getOutputStream() placeholder ticket

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#703]
---

Author Name: **Elda Sotiri** (@esotiri)
Original Redmine Issue: 4162, https://redmine.hmdc.harvard.edu/issues/4162
Original Date: 2014-06-30
Original Assignee: Gustavo Durand

---

We have been getting getOutputStream() exceptions on glassfish log and I am opening this ticket as a placeholder. 
- Steps to reproduce: 
Create a dataset and enter "Contact E-mail" "info@experts-exchange.com" (only entered information on the required fields and did not add any files). Note that dataset was successfully created with the above contact email. 

[2014-06-30T10:20:09.835-0400] [glassfish 4.0] [INFO] [] [edu.harvard.iq.dataverse.engine.command.impl.CreateDatasetCommand] [tid: _ThreadID=3287 _ThreadName=http-listener-1(10)] [timeMillis: 1404138009835] [levelValue: 800] [[
during dataset save, indexing result was: indexDraftResult:indexed dataset 474 as dataset_474_draft
indexFilesResults for dataset_474_draft, filesIndexed: [], 
rationale:
version found with database id 113
- title: one more test for contact
- semanticVersion-STATE: DRAFT-DRAFT
- isWorkingCopy: true
- isReleased: false
- files: 0 []
The latest version is a working copy (latestVersionState: DRAFT) and will be indexed as dataset_474_draft (only visible by creator)
There is no released version yet so nothing will be indexed as dataset_474]]

[2014-06-30T10:20:10.420-0400] [glassfish 4.0] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.application] [tid: _ThreadID=3289 _ThreadName=http-listener-1(12)] [timeMillis: 1404138010420] [levelValue: 1000] [[
Error Rendering View[/dataset.xhtml]
java.lang.IllegalStateException: getOutputStream() has already been called for this response
at org.apache.catalina.connector.Response.getWriter(Response.java:777)
at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:224)
at com.sun.faces.context.ExternalContextImpl.getResponseOutputWriter(ExternalContextImpl.java:834)
at com.sun.faces.application.view.FaceletViewHandlingStrategy.createResponseWriter(FaceletViewHandlingStrategy.java:1169)
at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:390)
at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:131)

**Comment by scolapasta** [comment]
@kcondon @esotiri can we see if this is still happening (in light of our move to glassfish 4.1)?

**Comment by esotiri** [comment]
so far I haven't been able to reproduce
