### ISSUE TITLE
OpenAire export failure when Author's first name is missing

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#7059]
`TL;DR:` If the author is entered with an empty comma-separated  first name, like this: "Smith," it results in a fatal error in the OpenAire export, making it impossible to publish the dataset. 

This came up as part of a real-life support issue. May not be the most urgent of problems... But it causes a disproportionate amount of trouble and confusion for the user, vs. how simple it would be to fix. So maybe add this to d5 on account of that? 

Looking at the exception stack trace and the corresponding code, it looks like adding some null/empty check there would fix this. (but maybe validation logic should also be added, to prevent the user from entering a name formatted like that?)

The exception stack trace:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.harvard.iq.dataverse.export.openaire.OpenAireExportUtil.writeCreatorsElement(OpenAireExportUtil.java:279)
	at edu.harvard.iq.dataverse.export.openaire.OpenAireExportUtil.createOpenAire(OpenAireExportUtil.java:88)
	at edu.harvard.iq.dataverse.export.openaire.OpenAireExportUtil.dto2openaire(OpenAireExportUtil.java:60)
	at edu.harvard.iq.dataverse.export.openaire.OpenAireExportUtil.datasetJson2openaire(OpenAireExportUtil.java:48)
	at edu.harvard.iq.dataverse.export.OpenAireExporter.exportDataset(OpenAireExporter.java:35)
	at edu.harvard.iq.dataverse.export.ExportService.cacheExport(ExportService.java:268)
	at edu.harvard.iq.dataverse.export.ExportService.exportAllFormats(ExportService.java:168)
	at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.exportMetadata(FinalizeDatasetPublicationCommand.java:198)
	at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.onSuccess(FinalizeDatasetPublicationCommand.java:185)
```

An example from prod.:
![Screen Shot 2020-06-24 at 11 48 54 AM](https://user-images.githubusercontent.com/737558/86802987-939b6d00-c043-11ea-8e6c-8bd33369abe7.png)

**Comment by landreev** [comment]
There's an open issue #6492, where splitting the author name into separate "first name" and "last name"  fields was being debated. OpenAire is specifically mentioned there. Having two separate fields would make the problem described above moot. However, I'm NOT suggesting touching that can of warms at all (it is complicated, as discussed there), but rather to just fix the problem at hand.
