### ISSUE TITLE
Dataset page: null pointer trying to export LD Json metadata

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7310]
Dataset page inserts "LD Json" (aka "schema.org") metadata fragment, for published datasets. This format is normally already exported and cached; so we  never noticed the issue below: 

If the fragment is not cached, export is called to generate it on the fly. And then it fails, with a null pointer below. Note that this is uniquely specific to calling this export from the page while it's loading. Requesting the format using the API works and caches the format, fixing the issue. 

This is likely caused by the fact that during the initial loading of the page we are using some optimized, minimalist way of initializing the dataset. So it loads without all the entities fully instantiated from the database yet. (The null pointer from DataFile.java:456 suggests the FileMetadata objects are not yet attached to the DataFiles). 

Depending on how much effort this would take to fix, we may just choose to leave it as is - but intercept the exception in a way that does not kill the page. So basically just live with the fact that for some published datasets this metadata fragment is not going to be included until it's exported elsewhere.

**Comment by landreev** [comment]
stacktrace: 
```
[2020-10-07T10:33:28.465-0400] [Payara 5.2020] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.application] [tid: _ThreadID=262 _ThreadName=http-thread-pool::jk-connector(7)] [timeMillis: 1602081208465] [levelValue: 1000] [[
 Error Rendering View[/dataset.xhtml]
javax.el.ELException: /dataset.xhtml @59,66 value="#{DatasetPage.jsonLd}": java.lang.NullPointerException
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:77)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:170)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:157)
	at javax.faces.component.UIOutput.getValue(UIOutput.java:140)
	at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getValue(HtmlBasicInputRenderer.java:181)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getCurrentValue(HtmlBasicRenderer.java:328)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeEnd(HtmlBasicRenderer.java:143)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at org.primefaces.renderkit.HeadRenderer.encodeBegin(HeadRenderer.java:72)
	at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:540)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1644)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:368)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.el.ELException: java.lang.NullPointerException
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:304)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:156)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:184)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:114)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:177)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:183)
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
	... 58 more
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DataFile.getDerivedOriginalFileName(DataFile.java:456)
	at edu.harvard.iq.dataverse.DataFile.getOriginalFileName(DataFile.java:447)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.json(JsonPrinter.java:608)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.json(JsonPrinter.java:562)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.jsonFileMetadatas(JsonPrinter.java:445)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.json(JsonPrinter.java:365)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.jsonWithCitation(JsonPrinter.java:419)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.jsonAsDatasetDto(JsonPrinter.java:438)
	at edu.harvard.iq.dataverse.export.ExportService.exportFormat(ExportService.java:211)
	at edu.harvard.iq.dataverse.export.ExportService.getExport(ExportService.java:99)
	at edu.harvard.iq.dataverse.export.ExportService.getExportAsString(ExportService.java:118)
	at edu.harvard.iq.dataverse.DatasetPage.getJsonLd(DatasetPage.java:5486)
	at sun.reflect.GeneratedMethodAccessor1192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:299)
	... 65 more
]]
```

**Comment by landreev** [comment]
One  important detail, it appears to only be bombing on datasets with tabular files. So to reproduce the error, use any published dataset with at least one tabular file; and remove, or rename the file export_schema.org.cached in the dataset directory. dataset page should bomb with the exception above. Put that file back, or run `/api/datasets/export?...exporter=schema.org`  - and it should be working again.

**Comment by qqmyers** [comment]
Unless I've missed something, it seems like the only way DataFile.java:456 fails is if there are no filemetadatas associated with the datafile. Can you confirm that the db has those relationships? (If it does, the issue is how they're missed. If not, the issue is how they didn't get created, etc.)

**Comment by landreev** [comment]
No, everything's fine in the db. (Again, note that the export works just fine when called via the API/in any other context). 
This part is likely the answer: "This is likely caused by the fact that during the initial loading of the page we are using some optimized, minimalist way of initializing the dataset". 
I.e. those are not real entities, but pseudo entities produced by custom queries. Filemetadata objects have links to the Datafiles; but no link back to the Filemetadata from the Datafile - hence the null pointer... Something like that.

**Comment by landreev** [comment]
Scratch the "initial" part above - but yes, we are using custom, hacky ways to populate the dataset with datafiles and associated objects, using custom queries; to avoid executing separate queries for each one, like EJB normally would: 
`datafileService.findFileMetadataOptimizedExperimental(dataset);`
and it does indeed look like we are doing this:
`fileMetadata.setDataFile(dataFiles.get(file_list_id));`
but not the reverse (`dataFile.setFileMetadata(...)`)
And of course the custom query that populates the datatable entries needs to be updated, to take the new originalfilename field into account.
So yeah, it's working for non-tabular files - because with those we never have to go from datafile back to filemetadata. 

Stuff like this works really fast... But, like with all hacks, there are associated maintenance costs...

**Comment by djbrooke** [comment]
Thanks @kcondon and @landreev. Seems like we've spent some time investigating and we know how we'd want to approach a fix. I'll move to up next so we can discuss in the next sprint planning meeting. I think it'd be good to fix so that we can make sure we're exposing the appropriate metadata for datasets to show in Google Dataset Search.

**Comment by kcondon** [comment]
I am seeing this in test on develop:
So what I'd done and may explain the failure, is I was impatient in waiting for dataset to publish so kept refreshing it to update status. It resulted in 500 error but I'd thought it was because url still had draft as arg and draft was gone but it appears to have triggered the export while page is loading condition. When I just published and let it take its sweet time, it worked fine

**Comment by landreev** [comment]
(just to repeat what I said on slack)

> it appears to have triggered the export while page is loading condition

Correct: your refreshing the page ensured that you caught the dataset in that brief window of being already published, but before the async. export following the publish command had a chance to finish creating the json fragment. (but if you kept refreshing the page would go back to working eventually).
