### ISSUE TITLE
intermittent 500 errors on signup / login

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#7534]
Depending on the route one takes to either sign up and/or login to Dataverse 5.3, any user might experience an error screen on login:

<img width="1188" alt="Screen Shot 2021-01-25 at 11 29 55" src="https://user-images.githubusercontent.com/12831666/105734479-abafdc80-5f00-11eb-9765-50f6c7f7a66c.png">

server.log says

```
{DataverseUserPage.init}: java.lang.NullPointerException
javax.faces.FacesException: #{DataverseUserPage.init}: java.lang.NullPointerException
        at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:96)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:71)
        at javax.faces.component.UIViewAction.broadcast(UIViewAction.java:548)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:847)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1396)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:58)
StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
java.lang.NullPointerException
        at edu.harvard.iq.dataverse.authorization.providers.builtin.DataverseUserPage.init(DataverseUserPage.java:170)
```

@scolapasta says "The error is happening on: switch (selectTab) { and may be an artifact of moving to Payara."

The error seems to be intermittent, and browser-independent. This morning I could produce it consistently in Chrome while creating dummy accounts through the web interface and signing in directly, though a more reliable way to produce it is to click on the Sign Up tab (but don't sign up), then the Login tab, then log in. Once the user is logged in and moves off of dataverse.xhtml all other pages display correctly.

A cosmetic snafu under the hood, but one an end-user might not understand, and a "Tums" moment for Dataverse administrators who encounter the error while testing configuration changes and forget that it's not uncommon on 5.x.

**Comment by djbrooke** [comment]
Thanks @donsizemore - I've seen this too.

**Comment by djbrooke** [comment]
- we suspect this may be caused by the dataverseuser page is being called without the selectTab parameter. It should have a default value but maybe this is not happening and null is being sent instead
- it could also be due to redirects (@qqmyers may have some fix implemented for QDR related to this)
