### ISSUE TITLE
Publication fails because File DOIs cannot be registered via DataCite

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#7670]
We have an issue that occurred for the first time today in our instance (v5.3). The publication of a dataset fails because the file DOIs cannot be registered.

Hopefully this has nothing to do with the fact that I called the Data Integrity API several times yesterday (see #7663)?

server.log:

[2021-03-10T13:51:21.322+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681322] [levelValue: 800] [[
  Finalizing publication of the dataset doi:10.11588/data/HRCX1P]]

[2021-03-10T13:51:21.389+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681389] [levelValue: 800] [[
  successfully validated DataFile 4,711; checksum 12da93448e6c6503e9d25d7960bc6a5b]]

[2021-03-10T13:51:21.394+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681394] [levelValue: 800] [[
  successfully validated DataFile 4,712; checksum 12ed5c4c7ffe30c62cc2ed46a9737ced]]

[2021-03-10T13:51:21.405+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681405] [levelValue: 800] [[
  successfully validated DataFile 4,713; checksum 6fdd11c078b29e19a5b06b7c8de64e6f]]

[2021-03-10T13:51:21.408+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681408] [levelValue: 800] [[
  successfully validated DataFile 4,714; checksum 4e9acae40b380d93fe6fcc91a12d0b39]]

[2021-03-10T13:51:21.412+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681412] [levelValue: 800] [[
  successfully validated DataFile 4,715; checksum cb5fdf6d713637dedb5ccda4afba737f]]

[2021-03-10T13:51:21.416+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681416] [levelValue: 800] [[
  successfully validated DataFile 4,716; checksum 4c344442e6c106fe156e2fb60befba72]]

[2021-03-10T13:51:21.419+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681419] [levelValue: 800] [[
  successfully validated DataFile 4,717; checksum f55c59b52213811f12a520efa307740b]]

[2021-03-10T13:51:21.447+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681447] [levelValue: 800] [[
  successfully validated DataFile 4,718; checksum 2498fd3a84ac3564dcd88aebd5941615]]

[2021-03-10T13:51:21.454+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681454] [levelValue: 800] [[
  successfully validated DataFile 4,719; checksum 8bb9bc35b98cc598e20f0d849ea71721]]

[2021-03-10T13:51:21.459+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681459] [levelValue: 800] [[
  successfully validated DataFile 4,720; checksum 0cb661fe3d2bf851e6e0dd2d065f3232]]

[2021-03-10T13:51:21.467+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681467] [levelValue: 800] [[
  successfully validated DataFile 4,721; checksum ddde3c6cf3e97a20d31cb882b176d4b9]]

[2021-03-10T13:51:21.470+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681470] [levelValue: 800] [[
  successfully validated DataFile 4,722; checksum 27a878f46a35587cb0a6e68f06d1dc76]]

[2021-03-10T13:51:21.473+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681473] [levelValue: 800] [[
  successfully validated DataFile 4,723; checksum d083d93768e19048588d481b2992af2a]]

[2021-03-10T13:51:21.476+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681476] [levelValue: 800] [[
  successfully validated DataFile 4,724; checksum 05f19a29977ed717daa58d1ff2e85202]]

[2021-03-10T13:51:21.479+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681479] [levelValue: 800] [[
  successfully validated DataFile 4,725; checksum 679db6b036c03e27de68d4a7b29095b2]]

[2021-03-10T13:51:21.482+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681482] [levelValue: 800] [[
  successfully validated DataFile 4,726; checksum 6f370234d8e84651c2f0ec1506826581]]

[2021-03-10T13:51:21.484+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681484] [levelValue: 800] [[
  successfully validated DataFile 4,727; checksum 8df5cd069d5ebb8e6ed33cc33c0d37d3]]

[2021-03-10T13:51:21.487+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681487] [levelValue: 800] [[
  successfully validated DataFile 4,728; checksum d87ff7ae5b1a9f90166813dd2faa817f]]

[2021-03-10T13:51:21.490+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681490] [levelValue: 800] [[
  successfully validated DataFile 4,729; checksum 6874f1b448389ef2dbe437cfeacf253e]]

[2021-03-10T13:51:21.494+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681494] [levelValue: 800] [[
  successfully validated DataFile 4,730; checksum 18e736dedaeb5f97cee9316b493930ed]]

[2021-03-10T13:51:21.497+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681497] [levelValue: 800] [[
  successfully validated DataFile 4,731; checksum e023f80859a77e7b3d60261f2483b9c3]]

[2021-03-10T13:51:21.503+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681503] [levelValue: 800] [[
  successfully validated DataFile 4,732; checksum 7bbd0a8f7c1a9702bd58f3bd15974d03]]

[2021-03-10T13:51:21.536+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681536] [levelValue: 800] [[
  successfully validated DataFile 4,733; checksum 663b829865549508e63300110f20b002]]

[2021-03-10T13:51:21.546+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681546] [levelValue: 800] [[
  successfully validated DataFile 4,734; checksum 409544e31ee48779ca5d429e571c21d8]]

[2021-03-10T13:51:21.557+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681557] [levelValue: 800] [[
  successfully validated DataFile 4,735; checksum ae0f8c79b0fdbcbd25d9f0fc5e8e8284]]

[2021-03-10T13:51:21.560+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681560] [levelValue: 800] [[
  successfully validated DataFile 4,736; checksum 1effb88c0fc820523de13531e8092135]]

[2021-03-10T13:51:21.593+0100] [Payara 5.2020.7] [INFO] [] [edu.harvard.iq.dataverse.util.FileUtil] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380681593] [levelValue: 800] [[
  successfully validated DataFile 4,737; checksum 1dd39b8518a442a99ff39d914e9c4432]]

[2021-03-10T13:51:24.731+0100] [Payara 5.2020.7] [SEVERE] [] [edu.harvard.iq.dataverse.DataCiteRESTfullClient] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380684731] [levelValue: 1000] [[
  Response from postMetadata: 422, DOI 10.11588/data/hrcx1p/ow5l9i: [facet 'minLength'] The value has a length of '0'; this underruns the allowed minimum length of '1'. at line 56, column 0]]

[2021-03-10T13:51:24.732+0100] [Payara 5.2020.7] [WARNING] [] [edu.harvard.iq.dataverse.DOIDataCiteServiceBean] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380684732] [levelValue: 900] [[
  modifyMetadata failed: Response from postMetadata: 422, DOI 10.11588/data/hrcx1p/ow5l9i: [facet 'minLength'] The value has a length of '0'; this underruns the allowed minimum length of '1'. at line 56, column 0
java.io.IOException: Response from postMetadata: 422, DOI 10.11588/data/hrcx1p/ow5l9i: [facet 'minLength'] The value has a length of '0'; this underruns the allowed minimum length of '1'. at line 56, column 0
	at edu.harvard.iq.dataverse.DataCiteRESTfullClient.postMetadata(DataCiteRESTfullClient.java:175)
	at edu.harvard.iq.dataverse.DOIDataCiteRegisterService.registerIdentifier(DOIDataCiteRegisterService.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy362.registerIdentifier(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__DOIDataCiteRegisterService__Intf____Bean__.registerIdentifier(Unknown Source)
	at edu.harvard.iq.dataverse.DOIDataCiteServiceBean.publicizeIdentifier(DOIDataCiteServiceBean.java:261)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy309.publicizeIdentifier(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__DOIDataCiteServiceBean__Intf____Bean__.publicizeIdentifier(Unknown Source)
	at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.publicizeExternalIdentifier(FinalizeDatasetPublicationCommand.java:369)
	at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.execute(FinalizeDatasetPublicationCommand.java:172)
	at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.execute(FinalizeDatasetPublicationCommand.java:46)
	at edu.harvard.iq.dataverse.EjbDataverseEngineInner.submit(EjbDataverseEngineInner.java:36)
	at sun.reflect.GeneratedMethodAccessor1191.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy335.submit(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__EjbDataverseEngineInner__Intf____Bean__.submit(Unknown Source)
	at edu.harvard.iq.dataverse.EjbDataverseEngine.submit(EjbDataverseEngine.java:259)
	at sun.reflect.GeneratedMethodAccessor1086.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy299.submit(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__EjbDataverseEngine__Intf____Bean__.submit(Unknown Source)
	at edu.harvard.iq.dataverse.DatasetServiceBean.callFinalizePublishCommandAsynchronously(DatasetServiceBean.java:817)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]

[2021-03-10T13:51:24.734+0100] [Payara 5.2020.7] [WARNING] [] [edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand] [tid: _ThreadID=261 _ThreadName=__ejb-thread-pool14] [timeMillis: 1615380684734] [levelValue: 900] [[
  Failed to register the identifier doi:10.11588/data/HRCX1P, or to register a file in the dataset; notifying the user(s), unlocking the dataset]]

**Comment by lmaylein** [comment]
This is what it looks like on the frontend. It is noticeable that for each file only the DOI of the dataset is displayed under "File Citation".

![heiARCHIVE-logo-v1 svg_](https://user-images.githubusercontent.com/7468155/110633644-4dd20e00-81a9-11eb-8cc9-119dc2156566.png)

**Comment by lmaylein** [comment]
Indeed. There was a producer URL entered but no name. After entering the name, the dataset could be publicated.

Thank you very much.
