### ISSUE TITLE
Normal upload to a direct upload store is broken

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7770]
@jmjamison reports getting an error when trying a normal upload via pyDataverse to a dataset that is using an s3 store configured for direct upload. The stack trace shows:
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -5
	at java.lang.String.substring(String.java:1931)
	at edu.harvard.iq.dataverse.dataaccess.S3AccessIO.open(S3AccessIO.java:172)
	at edu.harvard.iq.dataverse.dataaccess.DataAccess.createNewStorageIO(DataAccess.java:199)
	at edu.harvard.iq.dataverse.dataaccess.DataAccess.createNewStorageIO(DataAccess.java:155)
	at edu.harvard.iq.dataverse.ingest.IngestServiceBean.saveAndAddFilesToDataset(IngestServiceBean.java:195)

```
which nominally appears to be triggered by the storageidentifier being passed around not having the store name prepended (e.g. 's3://' at the start corresponding to the -5 in the string index out of range) - which is normal for normal upload but not for direct uploads. My initial assumption was that this is a ~bug w.r.t. handling normal uploads when using a direct-upload store, but I have so far been unable to reproduce the problem - using ~5.4 and the API rather than 5.3 via pyDataverse. So - the problem may be with specific ingestable file types or with optional metadata instead. (@jmjamison - can you provide more detail on the parameters you used with the pyDataverse call and the file type that fails?)

In any case, there is probably some work to catch the error and provide a more useful error message/status code. If it is a problem with normal upload to a direct-upload s3 store, we could decide to prohibit that, or restore the functionality. (The direct-upload code didn't disable normal uploads via API, but it may or may not make sense, especially given the larger file sizes involved with direct-upload).

**Comment by jmjamison** [comment]
This may be more then you need but this is the code I'm using.  Works perfectly for regular, non-direct-upload.  The error is when I try this on direct-upload.  I should say I'm using direct upload because this is for Lariac data which is large.

from pyDataverse.api import NativeApi
from pyDataverse.models import Datafile
df = Datafile()
import json  

Setting the filename and pid in-code
api = NativeApi(base_url, dv_token)

df.set({"pid": ds_pid, "filename": df_filename, "description":"LARIAC4", "contentType":"LAS file Lidar","categories":["LARIAC4", "GIS","LAS file", "Lidar"],"restrict":True})

resp = api.upload_datafile(ds_pid, df_filename,  df.json())

**Comment by jmjamison** [comment]
I don't know if this is relevant but I get the same response if I attempt a direct upload using curl at the command line:
curl -H X-Dataverse-key:xxxxxxxxxxxx -X POST -F file=@L4_6292_1842a.las -F 'jsonData={"description":"LARIAC4","restrict":True}' "https://dataverse.ucla.edu/api/datasets/:persistentId/add?persistentId=doi:10.25346/S6/T4LHZF"
{}

This is based on the example in Dataverse Native API (<https://guides.dataverse.org/en/latest/api/native-api.html>)

**Comment by qqmyers** [comment]
Cool - that's useful info - confirming that this is a Dataverse issue (#7770 in fact :-)) and not something pyDataverse specific or something related to the ingest process for specific file types. 

If you want to try a 'direct' upload via API - it requires a series of calls as described in the [new direct upload api material in the guides](https://guides.dataverse.org/en/latest/developers/s3-direct-upload-api.html). 

If you want to try that, I'd recommend looking at the pre-release version of that info at [s3-direct-upload-api](https://github.com/IQSS/dataverse/blob/08968bb047ef6e8cf451fc1e6c836f3fa5fb5d25/doc/sphinx-guides/source/developers/s3-direct-upload-api.rst) which fixes some typos in the examples. (The pre-release part is that direct upload can't yet be used with the File /replace API call which is part of a PR in testing, but the discussion of doing direct upload with the Dataset /add api call is consistent with 5.3.).

**Comment by jmjamison** [comment]
I'm trying the s3-direct-upoad-api

curl -H 'X-Dataverse-key:xxxxxxxxxx' "https://dataverse.ucla.edu/api/datasets/:persistentId/uploadurls?persistentId=doi:10.25346/S6/T4LHZF&size=300000"
{"status":"ERROR","message":"You are not permitted to upload files to this dataset."}

That may something incorrect on my part.  I have uploaded directly using the web interface and to be sure I just checked that CORS is allowed.

I found this error:  An exception or error occurred in the container during the request processing
java.lang.Exception: Host is not set

I'm attaching a server.log - since I may have not recognized an important error.
[march9-server.log](https://github.com/IQSS/dataverse/files/6288215/march9-server.log)

**Comment by qqmyers** [comment]
I don't see anything in the log related to this call (just a prior failure from the normal upload) and the basic form of the curl command above looks OK, so I'd suspect, from the fact that the error is about permissions, that the API key was not valid/for a user who can't edit this dataset,  or there's a typo in the DOI, etc. 

I don't think CORS would affect this call or cause this error. Incorrect CORS settings could affect the second step where you're sending the file or its parts to S3.

**Comment by jmjamison** [comment]
Unfortunately the api key is still the right one.  I'll check the doi again. This has to be a typo on my part.

**Comment by qqmyers** [comment]
or perhaps this dataset isn't using the store that has direct upload enabled?

**Comment by jmjamison** [comment]
No, still the same store. The Lidar files are all set to direct-upload.

**Comment by jmjamison** [comment]
The error has to be something I'm doing or not doing. I got something similar from dvuploader:

***Parsing arguments:***

Using apiKey: xxxxxxxxxxx
Adding content to: doi:10.25346/S6/T4LHZF
Using server: https://dataverse.ucla.edu
Request to upload: upload

***Starting to Process Upload Requests:***


PROCESSING(D): upload
              Found as: doi:10.25346/S6/T4LHZF

PROCESSING(F): upload\L4_6276_1842b.las
              Found as: MD5:0c0788b787d97374aed0ca6310e47e36

PROCESSING(F): upload\L4_6292_1842a.las
               Does not yet exist on server.
Error response when processing D:\work-related\dvuploader\upload\L4_6292_1842a.las : Internal Server Error
{}

***Execution Complete.***

**Comment by qqmyers** [comment]
Hmm - the code is pretty simple - it looks for the dataset, gets the user (from the api key), and then checks to see if that user has Edit permission on that Dataset and if not, sends the 403 error you're seeing with the api .

For DVUploader, you need to add the -directupload parameter to make it use direct upload, so that may be why you've gotten an Internal Server Error - the original error when trying a normal upload. If you add -directupload, you should at least see a 403/Forbidden error rather than an internal server error, but if you've got the right user and dataset, hopefully it will work.

Also - the DVUploader creates a log file that sometimes has more info in it that what the command line displays - checking there might help debug.

**Comment by jmjamison** [comment]
My mistake about missing the -directupload parameter.  This time dvuploader worked.

**Comment by qqmyers** [comment]
Awesome! It really should be the case that the DVUploader is using the same exact API call as you were using. I don't know if you can see anything in your Apache log/Dataverse access log that would show any difference between what curl sent and what DVUploader sent, but that might give a clue.

**Comment by qqmyers** [comment]
As this is from 2021 and there may have been confounding issues with configuration (related to priority of different AWS S3 credentials mechanisms), I'm suggesting we close this. If there's confirmation that this is still a current problem, we can create a new issue.
