### ISSUE TITLE
S3 direct-upload: uncaught duplicate file warning

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#7858]
One of our archivists, using an S3 bucket with upload-direct enabled, reported:

![image](https://user-images.githubusercontent.com/12831666/117497095-f8ff0980-af45-11eb-906e-93fc792cb792.png)

searching for Demo_Geo.zip yields

```
[2021-04-27T17:45:30.410+0000] [Payara 5.2020.6] [INFO] [] [] [tid: _ThreadID=107 _ThreadName=http-thread-pool::jk-connector(1)] [timeMillis: 1619545530410] [levelValue: 800] [[
  upload error]]

[2021-04-27T17:45:30.411+0000] [Payara 5.2020.6] [INFO] [] [] [tid: _ThreadID=107 _ThreadName=http-thread-pool::jk-connector(1)] [timeMillis: 1619545530411] [levelValue: 800] [[
  Error! You may not replace a file with a file that has duplicate content.]]

[2021-04-27T17:45:30.411+0000] [Payara 5.2020.6] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=107 _ThreadName=http-thread-pool::jk-connector(1)] [timeMillis: 1619545530411] [levelValue: 900] [[
  #{EditDatafilesPage.handleExternalUpload()}: java.lang.NullPointerException
javax.faces.FacesException: #{EditDatafilesPage.handleExternalUpload()}: java.lang.NullPointerException

Caused by: java.lang.NullPointerException
        at edu.harvard.iq.dataverse.EditDatafilesPage.handleExternalUpload(EditDatafilesPage.java:2033)

javax.faces.el.EvaluationException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
        at edu.harvard.iq.dataverse.EditDatafilesPage.handleExternalUpload(EditDatafilesPage.java:2033)
```

I ask Jim whether it's possible this duplicate content error isn't percolating back up to the browser, who says:

> Probably - line 2033 of v5.3 includes fileReplacePageHelper.getNewFileMetadatasBeforeSave() which will return null if 'phase 1' of adding the file fails, so any problem in phase 1 would break it. The problem still exists in the develop branch, so worth an issue there.

**Comment by djbrooke** [comment]
- Note the line number above - test on S3 direct upload or regular upload
- Upload a file, try to upload the file again

**Comment by sekmiller** [comment]
Also in the RequestRsyncScriptCommand if the :DataCaptureModuleUrl is null the command throws a runtime exception that isn't caught leaving the file upload widget blank with no info on what is wrong and how to proceed.

**Comment by qqmyers** [comment]
Is this related/connected to S3/direct upload or a new issue?

**Comment by sekmiller** [comment]
it's connected enough to fix in the same branch, which is my current plan - along with any other error handling i can tighten up.
