### ISSUE TITLE
DDI/OAI-DDI exports crash for some records in 5.9

### ISSUE THREAD

**Issue by bappun** [IQSS/dataverse#8452]
**What steps does it take to reproduce the issue?**
Not sure why it happens on our Dataverse instance.

* When does this issue occur?
When some datasets are exported to DDI.

* Which page(s) does it occurs on?
  - OAI-DDI ListRecords
https://data.sciencespo.fr/oai?verb=ListRecords&metadataPrefix=oai_ddi

  - **Not working** dataset: https://data.sciencespo.fr/dataset.xhtml?persistentId=doi:10.21410/7E4/075L2L
    - OAI-DDI GetRecord: https://data.sciencespo.fr/oai?verb=GetRecord&metadataPrefix=oai_ddi&identifier=doi:10.21410/7E4/075L2L
    - DDI export: https://data.sciencespo.fr/api/datasets/export?exporter=ddi&persistentId=doi:10.21410/7E4/075L2L

  - **Working** dataset: https://data.sciencespo.fr/dataset.xhtml?persistentId=doi:10.21410/7E4/YE586X
    - OAI-DDI GetRecord: https://data.sciencespo.fr/oai?verb=GetRecord&metadataPrefix=oai_ddi&identifier=doi:10.21410/7E4/YE586X
    - DDI export: https://data.sciencespo.fr/api/datasets/export?exporter=ddi&persistentId=doi:10.21410/7E4/YE586X

* What happens?
The DDI/OAI-DDI exports crash when getting records:
![image](https://user-images.githubusercontent.com/24225471/155743074-a91dc616-e39d-4de5-947e-8a0e9c0a2efa.png)
We upgraded our instance from 4.2 to 5.9 and noticed this issue when using the OAI. It does not happen on all records but one error makes the whole ListRecord crash. Here are the logs from server.log when the issue is raised:
```
[2022-02-25T16:29:14.054+0100] [Payara 5.2021.10] [WARNING] [] [edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet] [tid: _ThreadID=105 _ThreadName=http-thread-pool::jk-connector(1)] [timeMillis: 1645802954054] [levelValue: 900] [[
 IO exception in Get; Xrecord: failed to open metadata stream.]]

[2022-02-25T16:29:14.054+0100] [Payara 5.2021.10] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=105 _ThreadName=http-thread-pool::jk-connector(1)] [timeMillis: 1645802954054] [levelValue: 900] [[
 StandardWrapperValve[OAIServlet]: Servlet.service() for servlet OAIServlet threw exception
java.io.IOException: Xrecord: failed to open metadata stream.
       at edu.harvard.iq.dataverse.harvest.server.xoai.Xrecord.writeToStream(Xrecord.java:98)
       at edu.harvard.iq.dataverse.harvest.server.xoai.XlistRecords.writeToStream(XlistRecords.java:40)
       at edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet.writeListRecords(OAIServlet.java:300)
       at edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet.processRequest(OAIServlet.java:252)
       at edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet.doGet(OAIServlet.java:222)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
       at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
       at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
       at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
```

**Which version of Dataverse are you using?**
5.9

**Any related open or closed issues to this bug report?**
No

**Comment by landreev** [comment]
Thank you for the detailed report.
The exception stack trace above is from the failing GetRecord call. Could you please add the stack trace that you see in the log from the failure to export, as well? (i.e., when you try the export API - https://data.sciencespo.fr/api/datasets/export?exporter=ddi&persistentId=doi:10.21410/7E4/075L2L). I would expect any useful information about the actual reason for the export to fail to be there. 

(In other words, OAI/GetRecord does not try to export the metadata; it expects the record to be ready to read. So indeed the OAI error is just about the error to open the file. On top of the error to export, this is definitely looking like a bug, that the record was added to the OAI set, as if the DDI format was exported and saved; even though it failed.)

**Comment by qqmyers** [comment]
Could this be #8036? It was fixed with #8039 ~v5.6, but you'd have to reExport to pick up the fix.

**Comment by landreev** [comment]
> Could this be #8036? It was fixed with #8039 ~v5.6, but you'd have to reExport to pick up the fix.

To me it looks like this is likely something else; (note that there are no files in the dataset; that misplaced tag was happening in the files section, I think?)
I feel like this is more likely to be some UNF character issue... but that's a very superficial guess, so I need to take a closer look.

**Comment by bappun** [comment]
We reexported all after upgrading. We also have the same issue on our pre-production server where we reexported multiple times.

I have trouble getting logs. Last week when I was refreshing the page causing errors, there were stacktraces but now there is none. I set the logs to FINE, restarted payara, reexported, and still no stacktrace. Is there some cache for the exports that prevents me from getting the errors in the logs?

**Comment by landreev** [comment]
OK, it's looking like maybe your last attempt to re-export actually cached that broken, incomplete xml record on disk (or in your S3 bucket, whichever you are using). So that's what Dataverse is using now, hence no export exceptions. 

Could you please try to delete the file `export_oai_ddi.cached` in the dataset directory (if it indeed exists). And then try `https://data.sciencespo.fr/api/datasets/export?exporter=oai_ddi&persistentId=doi:10.21410/7E4/075L2L` again, and look for a stack trace then? (Note the "exporter=oai_ddi" above, this is the format OAI is using; although I'm assuming "ddi" should be subject to the same issue)

The file will be located somewhere like `<YOUR FILES DIRECTORY>/10.21410/7E4/075L2L/export_oai_ddi.cached`, or a similar S3 location.

**Comment by landreev** [comment]
Just to confirm, when you say "refreshed the export page", that was `https://data.sciencespo.fr/api/datasets/export?exporter=oai_ddi&persistentId=doi:10.21410/7E4/075L2L`?
That "No published version" is extremely confusing... Still looking into this/reading the code underneath.

**Comment by bappun** [comment]
Yes it was this link (I copy pasted the one you sent before).

`{"status":"ERROR","message":"Export Failed"}` only appeared when the cache was not generated yet. However we also tried the same procedure with the working dataset and we did not get this error, we directly got the XML response.

**Comment by donsizemore** [comment]
@bappun Dataverse tries to write a temporary export file into `/tmp` before placing it in the dataset's storage location. If you're hitting the problem I suspect you may be, you'll see such files left lying around, as there may be some character in your metadata which is legal in JSON but illegal in XML. Examining the last line or so can help you pinpoint whether this is in fact a problem. If you're unable to edit the metadata through the GUI you can also edit it directly in the DB, though this is not a fun experience.

**Comment by jggautier** [comment]
I'm not sure that the fact that the schema technically allows it means it should be done, but letting depositors add multiple Collection Modes makes sense to me. And for search purposes I'd rather have depositors enter each mode in a different field then (maybe even better to pick terms from a vocabulary) then to add all modes in one field.

I'm not sure why the field was set up to allow only one instance. Maybe at the time they weren't aware of any real cases of people needing to add multiple collection modes?

Most of the fields in the Social Science metadatablock don't let depositors add text boxes. Has your social_science.tsv been edited to allow multiples for other fields, e.g. Type of Research Instrument? If so, would creating a dataset with multiple Type of Research Instrument values also break the DDI export because it doesn't expect Type of Research Instrument to allow multiples?

**Comment by bappun** [comment]
In our social_science.tsv we do not have Research Instrument as multiple but we have Unit of Analysis. Unit of Analysis seems to be the same type of field as Collection Mode but it works great with the DDI export and the search as a facet.

Here are our TSV if you want to take a look: https://github.com/CDSP-SCPO/dataverse-controlledvocabulary

**Comment by jggautier** [comment]
Ah thanks.

Is a solution then to change the code that creates that DDI export so that it's able to include multiple collMode elements? Sounds like a similar situation to what's done already for the Unit of Analysis field. Maybe by doing this, we can let the social science metadatablock TSV file that ships with the software continue to not allow multiples (until there's resources to do the research needed to make sure that it's a good idea to change property in the social science metadatablock TSV file that ships with the software).

**Comment by landreev** [comment]
I had to take a day off/look into something else. 
Looking into this now, this is super interesting... All that time I was expecting that it was happening because you had some exotic UTF character in some of the values. Was about to send you a database query to extract the raw values to send us. 

But if it is as simple as this - a potentially multiple value that our DDI export insists on treating as a single-value-only, then it is clearly a bug that we need to fix. 
For the Unit of Analysis, I am indeed seeing that it is explicitly handled as a multiple: 

```
if (DatasetFieldConstant.unitOfAnalysis.equals(fieldDTO.getTypeName())) {
   writeI18NElementList(xmlw, "anlyUnit", fieldDTO.getMultipleVocab(), "unitOfAnalysis", fieldDTO.getTypeClass(), "socialscience", lang);
}
```

while collMode is exported as 
```
writeI18NElement(xmlw, "collMode", version, DatasetFieldConstant.collectionMode, lang);
```

**Comment by landreev** [comment]
(Aside from the issue of how to treat this specific field, it is obviously a bug, that Dataverse assumed that this dataset was successfully exported - even though it was not - and added it to the OAI set; so that needs to be resolved too).

**Comment by landreev** [comment]
OK, I just got the part that it is multiple, because YOU made it multiple in your installation. (Finally). 

Yeah, it is allowed to be multiple in the DDI schema. Just hard-coded to single in our code.

**Comment by landreev** [comment]
We are close to releasing Dataverse 5.10, and I am trying to add a fix for this to the release.

**Comment by bappun** [comment]
Thank you all for your help with this issue. We really appreciate it!

**Comment by landreev** [comment]
Note to self: remember to open a new issue for the apparent bug in the export code that marked the dataset as successfully exported (which resulted, among other things, in it being added to the OAI set), even though the export clearly failed.
