### ISSUE TITLE
Adding workflow using API results in NullPtrException

### ISSUE THREAD

**Issue by TanayKarve** [IQSS/dataverse#8569]
**What steps does it take to reproduce the issue?**
```bash
curl -H X-Dataverse-key:DATAVERSETOKEN -L -X POST "http://dataverse.dsmlp.ucsd.edu/api/admin/workflows/?unblock-key=UNBLOCKKEY" -d @workflow.json
```
Contents of workflow.json:
```json
{
    "provider":":internal",
    "stepType":"http/sr",
    "parameters": {
        "url":"http://my.dataverse.url.com/flask/_dv_test/${dataset.identifier}/${dataset.displayName}",
        "method":"GET",
        "contentType":"text/plain",
        "body":"hello from dataverse",
        "expectedResponse":"OK.*",
        "rollbackUrl":"http://localhost:5050/rollbackMetadata/${dataset.identifier}",
        "rollbackMethod":"DELETE ${dataset.id}"
    }
}
```

* When does this issue occur?
While adding a workflow trigger using the API.

* What happens?
```json
{"status":"ERROR","code":500,"message":"Internal server error. More details available at the server logs.","incidentId":"8712e016-2f24-4c65-8423-cba1f96a5bb5"}
```
Server logs:
```
[#|2022-04-01T19:11:22.876+0000|SEVERE|glassfish 4.1|edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler|_ThreadID=34;_ThreadName=http-listener-1(5);_TimeMillis=1648840282876;_LevelValue=1000;|
  API internal error 8712e016-2f24-4c65-8423-cba1f96a5bb5: Null Pointer
java.lang.NullPointerException
	at edu.harvard.iq.dataverse.util.json.JsonParser.validate(JsonParser.java:847)
	at edu.harvard.iq.dataverse.util.json.JsonParser.parseWorkflow(JsonParser.java:700)
	at edu.harvard.iq.dataverse.api.WorkflowsAdmin.addWorkflow(WorkflowsAdmin.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at edu.harvard.iq.dataverse.api.ApiBlockingFilter$4.doBlock(ApiBlockingFilter.java:108)
	at edu.harvard.iq.dataverse.api.ApiBlockingFilter.doFilter(ApiBlockingFilter.java:158)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at edu.harvard.iq.dataverse.api.ApiRouter.doFilter(ApiRouter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:873)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:739)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:575)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:546)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:428)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:378)
	at edu.harvard.iq.dataverse.api.ApiRouter.doFilter(ApiRouter.java:34)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:748)
```
* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
Workflow should have been setup

**Which version of Dataverse are you using?**

v. 4.20 build 413-4e07b62 on kubernetes.

**Comment by qqmyers** [comment]
It looks like you are sending the definition of a single step instead of a workflow. (Hence json validation fails to find a "name" for the workflow in what you sent). 
https://github.com/IQSS/dataverse/blob/develop/scripts/api/data/workflows/internal-httpSR-workflow.json might be a helpful example. (It is one of the json examples mentioned in the [Native API guide section for workflows ](https://guides.dataverse.org/en/latest/api/native-api.html?highlight=workflow#workflows) which is separate from where the specific steps are discussed. (PR to make the guides clearer welcome!).

**Comment by TanayKarve** [comment]
Thank you for your prompt response.
I inculcated the changes as per the example, and now my workflow.json looks like this:
```json
{
	"name": "metadata-updater",
	"steps": [{
		"provider": ":internal",
		"stepType": "http/sr",
		"parameters": {
			"url": "http://dataverse.dsmlp.ucsd.edu/flask/_dv_test/${dataset.globalId}/${dataset.displayName}",
			"method": "GET",
			"contentType": "text/plain",
			"body": "hello from dataverse",
			"expectedResponse": "OK.*",
			"rollbackUrl": "http://localhost:5050/rollbackMetadata/${dataset.identifier}",
			"rollbackMethod": "DELETE ${dataset.id}"
		}
	}]
}
```
However, still getting the same errors.
Am I missing something? 
Thanks.

**Comment by TanayKarve** [comment]
Thank you for your prompt response.
I inculcated the changes as per the example, and now my workflow.json looks like this:
```json
{
	"name": "metadata-updater",
	"steps": [{
		"provider": ":internal",
		"stepType": "http/sr",
		"parameters": {
			"url": "http://my.dataverse.url.com/flask/_dv_test/${dataset.globalId}/${dataset.displayName}",
			"method": "GET",
			"contentType": "text/plain",
			"body": "hello from dataverse",
			"expectedResponse": "OK.*",
			"rollbackUrl": "http://localhost:5050/rollbackMetadata/${dataset.identifier}",
			"rollbackMethod": "DELETE ${dataset.id}"
		}
	}]
}
```
However, still getting the same errors.
Am I missing something? 
Thanks.

**Comment by qqmyers** [comment]
The line in JsonParser from v4.20 (700) is the check for "name" in the top-level of what you send. Other than guessing that you're not sending the json you think I can't think of why this would still fail. If the log is showing a different line where validation is failing, it could be that there is some other field that is expected that is not in the example.

**Comment by pdurbin** [comment]
For what it's worth, I'm able to load the update JSON example with "name". I'm on the develop branch (8c70b7ab2c).

`curl -H "X-Dataverse-key:$API_TOKEN" -H "Content-Type: application/json"  -X POST "http://localhost:8080/api/admin/workflows" -d @workflow.json`

`{"status":"OK","data":{"name":"metadata-updater","id":1,"steps":[{"stepType":"http/sr","provider":":internal","parameters":{"rollbackUrl":"http://localhost:5050/rollbackMetadata/${dataset.identifier}","expectedResponse":"OK.*","rollbackMethod":"DELETE ${dataset.id}","method":"GET","body":"hello from dataverse","contentType":"text/plain","url":"http://my.dataverse.url.com/flask/_dv_test/${dataset.globalId}/${dataset.displayName}"}}]}}`

**Comment by TanayKarve** [comment]
The log is still showing the error on line 700, with the updated json on my instance.
Confirmed that I'm sending the correct json.
Anyway to increase the level of logging so that the real issue could be highlighted?

**Comment by qqmyers** [comment]
Hmm - In general you can increase logging per class with the asadmin set-log-levels (in the developer guide) but I don't see any additional statements in the area of the code involved here.

Looking further, since the validation error from line 847 is an NPE, it is possible that you're just not getting your json to the server at all. The only thought I have is that you might want to send a -H 'Content-Type:application/json' header. Not sure why you would need that if Phil doesn't be he's testing against a newer version, so maybe. 

If that doesn't help, the only suggestions I have would be to make sure other json-oriented APIs work in your config, try some of the other samples, etc. If you have access to a 5.10/5.x server, you could try there as well.

**Comment by TanayKarve** [comment]
Finally fixed this by adding **-H "Content-Type: application/json"** to the curl.
However, now getting this error on workflow execution:

```
[#|2022-05-01T00:17:53.649+0000|WARNING|glassfish 4.1|edu.harvard.iq.dataverse.workflow.WorkflowServiceBean|_ThreadID=160;_ThreadName=__ejb-thread-pool14;_TimeMillis=1651364273649;_LevelValue=900;|

  Workflow 4d5329c0-4309-4a87-befc-32cc33111049 failed: Error executing request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target|#]
```
What might the problem be?

**Comment by qqmyers** [comment]
This probably means your are trying to call an https:// service that has a self-signed certificate (or perhaps a LetsEncrypt cert). You can google the error. The two paths for a fix that don't involve code changes are to either get a certificate for your service from a provider trusted by Java or to add your current cert (if self-signed) or the root certificate authority you are using to the Java trust store. (Or use http for your testing, etc.). These are both cases where a search should help you find how to do this on your particular operating system.

**Comment by TanayKarve** [comment]
Okay, thanks. That fixed it.
However, now dataverse is rolling back the workflow because it's getting a HTTP 308 redirect instead of 200.
I tried changing `expectedResponse:"*"` instead of `expectedResponse:"OK.*"` but it still doesn't work.
How to allow redirects in the workflow.json file that is being uploaded to  /api/admin/workflows/?

**Comment by qqmyers** [comment]
The HttpSendReceiveClientStep class that calls you code in the send expects a response <=200 and <300. If it doesn't get that, it assumes the send has failed (and it rolls back and never waits to see if the remote service ever sends an expectedResponse.  Given that 308 means permanent redirect, the most appropriate fix might be to simply use that URL directly in your json configuration. (Presumably since Dataverse is not following the 308 redirect now, whatever service you're trying to contact isn't actually doing whatever you want it to do, i.e. what it would do if you then called the URL provided in the 308 response. It's just telling Dataverse to call the redirect URL and stopping (if it isn't it probably shouldn't be sending 308.).)

**Comment by TanayKarve** [comment]
Thank you so much, this fixed it.
However, when the workflow is getting paused for some reason.
My workflow.json file contains this:
```
{
"name":"metadata-updater-final",
"id":1,
"steps":[
    {
        "provider":":internal",
        "stepType":"log",
        "parameters": {
            "message": "Pre-http request"
        }
    },
    {
        "provider":":internal",
        "stepType":"http/sr",
        "parameters": {
            "url":"https://URL/flask/genMetadata/${dataset.globalId}/",
            "method":"GET",
            "contentType":"text/plain",
            "body":"hello from dataverse",
            "expectedResponse":"OK.*",
            "rollbackUrl":"https://localhost:5050/rollbackMetadata/${dataset.identifier}/wf",
            "rollbackMethod":"DELETE ${dataset.id}"
        }
    },
    {
        "provider":":internal",
        "stepType":"log",
        "parameters": {
            "message": "Post-http request"
        }
    }
]
}
```

But when the workflow executes, I see this on the dataset page on dataverse:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/42843134/169727618-52f218cf-95f4-4c3d-9a2e-099b1ca9a22c.png">
The dataverse logs look like this:
```

[#|2022-05-23T01:19:18.473+0000|INFO|glassfish 4.1|edu.harvard.iq.dataverse.workflow.internalspi.LoggingWorkflowStep|_ThreadID=136;_ThreadName=__ejb-thread-pool3;_TimeMillis=1653268758473;_LevelValue=800;|
  Invocation id 20f232c8-9457-417f-bc14-773cb25f9f58|#]

[#|2022-05-23T01:19:18.473+0000|INFO|glassfish 4.1|edu.harvard.iq.dataverse.workflow.internalspi.LoggingWorkflowStep|_ThreadID=136;_ThreadName=__ejb-thread-pool3;_TimeMillis=1653268758473;_LevelValue=800;|
  Dataset id:3|#]

[#|2022-05-23T01:19:18.473+0000|INFO|glassfish 4.1|edu.harvard.iq.dataverse.workflow.internalspi.LoggingWorkflowStep|_ThreadID=136;_ThreadName=__ejb-thread-pool3;_TimeMillis=1653268758473;_LevelValue=800;|
  Trigger Type PrePublishDataset|#]

[#|2022-05-23T01:19:18.474+0000|INFO|glassfish 4.1|edu.harvard.iq.dataverse.workflow.internalspi.LoggingWorkflowStep|_ThreadID=136;_ThreadName=__ejb-thread-pool3;_TimeMillis=1653268758474;_LevelValue=800;|
  Next version:2.0 isMinor:false|#]

[#|2022-05-23T01:19:18.474+0000|INFO|glassfish 4.1|edu.harvard.iq.dataverse.workflow.internalspi.LoggingWorkflowStep|_ThreadID=136;_ThreadName=__ejb-thread-pool3;_TimeMillis=1653268758474;_LevelValue=800;|
  message -> Pre-http request|#]

[#|2022-05-23T01:19:18.474+0000|INFO|glassfish 4.1|edu.harvard.iq.dataverse.workflow.internalspi.LoggingWorkflowStep|_ThreadID=136;_ThreadName=__ejb-thread-pool3;_TimeMillis=1653268758474;_LevelValue=800;|
  /Logging Step|#]

[#|2022-05-23T01:19:18.474+0000|INFO|glassfish 4.1|edu.harvard.iq.dataverse.workflow.WorkflowServiceBean|_ThreadID=136;_ThreadName=__ejb-thread-pool3;_TimeMillis=1653268758474;_LevelValue=800;|
  Workflow 20f232c8-9457-417f-bc14-773cb25f9f58 step 0: OK|#]
```
I notice that *Post-http request* is not logged.

**Comment by pdurbin** [comment]
@TanayKarve did the comment by @qqmyers help? Are you all set?
