### ISSUE TITLE
After email change, blank Account Information, Notifications, and API Token tabs

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8643]
@kcondon and I have established that this bug exists in 5.10.1 but the stack traces below are from 978350403b in the 8227-verify-email branch.

To reproduce:

- Sign in as dataverseAdmin (any builtin account, really).
- Change email to dataverse2@mailinator.com (or anything different).
- observe that you are on the "My Data" tab (staying on "Account Information" would be preferable).
- Observe stacktrace 1 below.
- Click "Account Information" and note that the tab is blank (see screenshot).
- Observe stacktrace 2 below.
- Observe similar behavior if you click "Notifications" or "API Token" tabs (blank in UI, more stacetrace 2).

## Screenshot (blank under "Account Information" tab)

![Screen Shot 2022-04-22 at 1 25 56 PM](https://user-images.githubusercontent.com/21006/164765549-688a3e0c-8217-421c-b159-e73388f512b6.png)

## Stacktrace 1 (after saving email change)

[2022-04-22T13:22:43.759-0400] [Payara 5.2021.5] [WARNING] [jsf.externalcontext.flash.response.already.committed] [javax.enterprise.resource.webcontainer.jsf.flash] [tid: _ThreadID=119 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1650648163759] [levelValue: 900] [[
  JSF1095: The response was already committed by the time we tried to set the outgoing cookie for the flash.  Any values stored to the flash will not be available on the next request.]]

## Stacktrace 2 (after clicking "Account Information" or other tabs)

[2022-04-22T13:24:11.704-0400] [Payara 5.2021.5] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=118 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1650648251704] [levelValue: 1000] [[
  java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at javax.faces.component.AttachedObjectListHolder.restoreState(AttachedObjectListHolder.java:146)
	at javax.faces.component.UIInput.restoreState(UIInput.java:1517)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy$2.visit(FaceletPartialStateManagementStrategy.java:372)
	at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:127)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1456)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:939)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.restoreView(FaceletPartialStateManagementStrategy.java:358)
	at com.sun.faces.application.StateManagerImpl.restoreView(StateManagerImpl.java:113)
	at com.sun.faces.application.view.ViewHandlingStrategy.restoreView(ViewHandlingStrategy.java:99)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.restoreView(FaceletViewHandlingStrategy.java:272)
	at com.sun.faces.application.view.MultiViewHandler.restoreView(MultiViewHandler.java:133)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:101)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:101)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:101)
	at org.omnifaces.viewhandler.OmniViewHandler.restoreView(OmniViewHandler.java:102)
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:181)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:110)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]

**Comment by pdurbin** [comment]
I tried returning early from the validateUserEmail method but the problem still occurs.

```
$ git diff
diff --git a/src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java b/src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
index e380d3f902..9df00757f9 100644
--- a/src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
+++ b/src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
@@ -224,6 +224,10 @@ public class DataverseUserPage implements java.io.Serializable {
     }
 
     public void validateUserEmail(FacesContext context, UIComponent toValidate, Object value) {
+        if (true) {
+            logger.info("in validateUserEmail but returning early...");
+            return;
+        }
         String userEmail = (String) value;
         boolean emailValid = EMailValidator.isEmailValid(userEmail);
         if (!emailValid) {
```

[2022-04-22T13:45:31.580-0400] [Payara 5.2021.5] [INFO] [] [edu.harvard.iq.dataverse.authorization.providers.builtin.DataverseUserPage] [tid: _ThreadID=118 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1650649531580] [levelValue: 800] [[
  in validateUserEmail but returning early...]]

[2022-04-22T13:45:31.668-0400] [Payara 5.2021.5] [WARNING] [jsf.externalcontext.flash.response.already.committed] [javax.enterprise.resource.webcontainer.jsf.flash] [tid: _ThreadID=118 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1650649531668] [levelValue: 900] [[
  JSF1095: The response was already committed by the time we tried to set the outgoing cookie for the flash.  Any values stored to the flash will not be available on the next request.]]

[2022-04-22T13:45:42.856-0400] [Payara 5.2021.5] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=119 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1650649542856] [levelValue: 1000] [[
  java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2

**Comment by pdurbin** [comment]
I also tried removing the email validator from the xhtml. Same thing. The bug is still there.

```
$ git diff
diff --git a/src/main/webapp/dataverseuser.xhtml b/src/main/webapp/dataverseuser.xhtml
index bbb7b7b0bc..e00be692dc 100644
--- a/src/main/webapp/dataverseuser.xhtml
+++ b/src/main/webapp/dataverseuser.xhtml
@@ -691,7 +691,6 @@
                                     </h:outputLabel>
                                     <div class="col-sm-4">
                                         <p:inputText id="email" styleClass="form-control"
-                                                     validator="#{DataverseUserPage.validateUserEmail}"
                                                      value="#{DataverseUserPage.userDisplayInfo.emailAddress}" />
                                         <p:message for="email" display="text" />
                                     </div>
```
