### ISSUE TITLE
Custom roles cannot be edited, throws error: "The role was not able to be saved. Role with this alias already exists"

### ISSUE THREAD

**Issue by chrpauls** [IQSS/dataverse#8808]
**What steps does it take to reproduce the issue?**
 when editing a custom role and trying to save the changes made, I get the error message "The role was not able to be saved. Role with this alias already exists."

* When does this issue occur?
Anytime I try to edit a custom role

* Which page(s) does it occurs on?
The 'Edit Role' window

* What happens?
Changes are not accepted.

* To whom does it occur (all users, curators, superusers)?
Admin

* What did you expect to happen?
For changes to a custom role to be accepted and saved.

**Which version of Dataverse are you using?**
v. 5.9 build 750-fb24c87

**Any related open or closed issues to this bug report?**
I found none

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/41664469/174531169-5bee256a-60f1-41fe-bdb9-bb2ed77d4344.png)

**Comment by pdurbin** [comment]
> when the role already exists in the db

@chrpauls in your case, did the role already exist? Any news on this?

**Comment by chrpauls** [comment]
No, the role did not exist prior. I was trying to create some custom roles and noticed the bug when I wanted to modify one of them.

The dataverse has been updated in the meantime to 5.11.1 build 1069-02e3e92 but the same thing happens :|

**Comment by pdurbin** [comment]
@chrpauls ok so to reproduce it we should try the following?

- create a custom role
- try to edit a custom role
- BOOM: (the error you showed)

(It looks like @qqmyers already linked to a commit from last year that may have introduced this problem.)

Thanks for testing on the latest release!

**Comment by chrpauls** [comment]
@pdurbin yes, those steps should reproduce it :)

**Comment by pdurbin** [comment]
Yep. Pretty broken. I just tested as of 5.12 (9686ab86f9).

I agree with the assessment by @qqmyers above...

> it appears that the CreateRoleCommand is also used when a role is edited and the change in [this commit](https://github.com/IQSS/dataverse/commit/9d872d083b225b792c0ecba9fc9b4d0aeb3d7880) now throws an exception when the role already exists in the db.

... from a quick look I'm not sure why we don't have a UpdateRoleCommand. We do have an updateRole method in ManagePermissionsPage.java on line 598 which is being called. I'll copy the method and stacktrace below.

Here's the user experience (not great!) of me trying to edit a role description:

## finish creating role (about to click save)

![Screen Shot 2022-10-06 at 9 11 26 AM](https://user-images.githubusercontent.com/21006/194324554-713621bb-b78a-41c7-88d2-7a9f7c6c0efc.png)

## clicking "edit role"

![Screen Shot 2022-10-06 at 9 12 03 AM](https://user-images.githubusercontent.com/21006/194324561-baa63f07-4799-4753-bf06-239a266f7c07.png)

## type new description

![Screen Shot 2022-10-06 at 9 12 30 AM](https://user-images.githubusercontent.com/21006/194324564-010f09f6-08ab-44aa-8f08-55695c2d9496.png)

## BOOM! 💣

![Screen Shot 2022-10-06 at 9 12 47 AM](https://user-images.githubusercontent.com/21006/194324568-b87464af-b515-4198-847b-25e9143d2697.png)


```
    public void updateRole(ActionEvent e) {
        // @todo currently only works for Dataverse since CreateRoleCommand only takes a dataverse
        // we need to decide if we want roles at the dataset level or not
        if (dvObject instanceof Dataverse) {
            role.clearPermissions();
            for (String pmsnStr : getSelectedPermissions()) {
                role.addPermission(Permission.valueOf(pmsnStr));
            }
            try {
                String roleState = role.getId() != null ? BundleUtil.getStringFromBundle("permission.updated") : BundleUtil.getStringFromBundle("permission.created");
                setRole(commandEngine.submit(new CreateRoleCommand(role, dvRequestService.getDataverseRequest(), (Dataverse) role.getOwner())));
                JsfHelper.addSuccessMessage(BundleUtil.getStringFromBundle("permission.roleWas", Arrays.asList(roleState)));
            } catch (PermissionException ex) {
                JH.addMessage(FacesMessage.SEVERITY_ERROR, BundleUtil.getStringFromBundle("permission.roleNotSaved"), BundleUtil.getStringFromBundle("permission.permissionsMissing", Arrays.asList(ex.getRequiredPermissions().toString())));
            } catch (CommandException ex) {
                JH.addMessage(FacesMessage.SEVERITY_ERROR, BundleUtil.getStringFromBundle("permission.roleNotSaved").concat(" " + ex.getMessage()) );
                logger.log(Level.SEVERE, "Error saving role: " + ex.getMessage(), ex);
            }
        }
        showRoleMessages();
    }
```

[2022-10-06T09:12:39.285-0400] [Payara 5.2022.3] [SEVERE] [] [edu.harvard.iq.dataverse.ManagePermissionsPage] [tid: _ThreadID=120 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1665061959285] [levelValue: 1000] [[
  Error saving role: Role with this alias already exists.
edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: Role with this alias already exists.
	at edu.harvard.iq.dataverse.engine.command.impl.CreateRoleCommand.execute(CreateRoleCommand.java:48)
	at edu.harvard.iq.dataverse.engine.command.impl.CreateRoleCommand.execute(CreateRoleCommand.java:23)
	at edu.harvard.iq.dataverse.EjbDataverseEngineInner.submit(EjbDataverseEngineInner.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
	at edu.harvard.iq.dataverse.__EJB31_Generated__EjbDataverseEngine__Intf____Bean__.submit(Unknown Source)
	at edu.harvard.iq.dataverse.ManagePermissionsPage.updateRole(ManagePermissionsPage.java:598)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by pdurbin** [comment]
It looks like this bug was first noticed here:

- #8008

**Comment by sergejzr** [comment]
Hello, just to confirm, the bug is there.

as workarounds 
Option 1:  delete role through the api and create a new one (will increase the role ID)
Option 2: Edit the identifier to at the same time to a random string, save, edit the identifier back

I also would like to note that deleting a role is not possible through thw GUI
