### ISSUE TITLE
Using editMetadata API endpoint fails when editing non-multiple compound or vocabulary fields

### ISSUE THREAD

**Issue by doigl** [IQSS/dataverse#8860]
**What steps does it take to reproduce the issue?**
If one tries to change the value of a single (not multiple) vocabulary field via the edit metadata API endpoint, the response is an empty object "{}", nothing happens and there is a NullPointerException in the server log.

```
curl -H 'X-Dataverse-Key:$API_KEY' -X PUT "https://demo.dataverse.org/api/datasets/:persistentId/editMetadata?persistentId=doi%3A10.70122%2FFK2%2FN7XGAF&replace=true" --upload-file edit_journal.json -H 'Content-Type: application/json'
```

edit_journal.json
```
{
  "fields": [
    {
      "typeName": "journalArticleType",
      "value": "abstract"
    }
 ]
}
```
The same holds for single (not multiple compound fields) like Series

```
curl -H 'X-Dataverse-Key:$API_KEY' -X PUT "https://demo.dataverse.org/api/datasets/:persistentId/editMetadata?persistentId=doi%3A10.70122%2FFK2%2FN7XGAF&replace=true" --upload-file edit_series.json -H 'Content-Type: application/json'
```

edit_series.json

```
{
  "fields": [
    {
      "typeName": "series",
      "value": {
          {
           "typeName": "seriesName",
           "value" : "bla"
          }

      }
    }
 ]
}
```

* When does this issue occur?

* Which page(s) does it occurs on?
bug does not occur if one edits a dataset via GUI

* What happens?
API returns 
``` {} ```

Error message in server.log (for vocabulary field)
```
[2022-07-26T09:57:07.636+0200] [Payara 5.2021.6] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ThrowableHandler] [tid: _ThreadID=101 _ThreadName=http-api-pool::jk-api-connector(1)] [timeMillis: 1658822227636] [levelValue: 1000] [[
  _status="ERROR";_code=500;_message="Internal server error. More details available at the server logs.";_incidentId="561c1fc5-d9f0-47b4-a095-0149dde59e25";_interalError="NullPointerException";_requestUrl="https://demodarus.izus.uni-stuttgart.de/api/v1/datasets/:persistentId/editMetadata/?persistentId=doi:10.15770/darus-1460&replace=true";_requestMethod="PUT"|]]

[2022-07-26T09:57:07.636+0200] [Payara 5.2021.6] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ThrowableHandler] [tid: _ThreadID=101 _ThreadName=http-api-pool::jk-api-connector(1)] [timeMillis: 1658822227636] [levelValue: 1000] [[
  java.lang.NullPointerException
        at edu.harvard.iq.dataverse.api.Datasets.validateDatasetFieldValues(Datasets.java:1041)
        at edu.harvard.iq.dataverse.api.Datasets.processDatasetUpdate(Datasets.java:925)
        at edu.harvard.iq.dataverse.api.Datasets.editVersionMetadata(Datasets.java:902)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at edu.harvard.iq.dataverse.api.ApiBlockingFilter.doFilter(ApiBlockingFilter.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at edu.harvard.iq.dataverse.api.ApiRouter.doFilter(ApiRouter.java:30)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:816)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:683)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:527)
        at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:497)
        at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:379)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:329)
        at edu.harvard.iq.dataverse.api.ApiRouter.doFilter(ApiRouter.java:34)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)
]]
	

```

* To whom does it occur (all users, curators, superusers)?
tested as super user on our own instance and as a normal user on demo.dataverse.org

* What did you expect to happen?
That the edited field gets edited :-)

**Which version of Dataverse are you using?**
5.9 on our own server, reproduced also on demo.dataverse.org with version 5.11

**Any related open or closed issues to this bug report?**
haven't found any issue, but is related to [new codemeta metadatablock](https://github.com/IQSS/dataverse/pull/7877#pullrequestreview-1049720894), where the field developmentStatus is a non-multiple vocabulary field.

**Comment by pdurbin** [comment]
@doigl yikes. Thanks for confirming this is broken on the demo server too.

**Comment by jo-pol** [comment]
Fixing the null pointer exception as tried on https://github.com/DANS-KNAW/dataverse/pull/194 turns both responses into "_400 Client Error: Bad Request_" The server log shows "_Semantic error parsing dataset update Json: Empty value for field: Notes_" 
This still does not allow to make the intended updates with the API.

**Comment by vera** [comment]
I may have discovered the same issue using Dataverse 6.5 (not sure, because my server log looks slightly different).

From my testing, it appears that the updated field needs to be 1. non-multiple, 2. controlled vocabulary, and 3. not nested for the following to occur:

When updating using the `/api/datasets/<id>/editMetadata` API, I receive a 500 error and the server log prints this error:

```
dev_dataverse>   _status="ERROR";_code=500;_message="Internal server error. More details available at the server logs.";_incidentId="2ca8605e-a233-4981-a5f1-f376f22b0718";_interalError="NullPointerException";_requestUrl="http://localhost:8080/api/v1/datasets/%3ApersistentId/editMetadata/?persistentId=doi%3A10.5072%2FFK2%2FD62RDS";_requestMethod="PUT"||#]
dev_dataverse> 
dev_dataverse> [#|2025-01-16T08:47:27.217+0000|SEVERE|Payara 6.2024.6|edu.harvard.iq.dataverse.api.errorhandlers.ThrowableHandler|_ThreadID=315;_ThreadName=http-thread-pool::http-listener-1(19);_TimeMillis=1737017247217;_LevelValue=1000;|
dev_dataverse>   java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because the return value of "edu.harvard.iq.dataverse.DatasetFieldValue.getValue()" is null
dev_dataverse>  at edu.harvard.iq.dataverse.api.Datasets.validateDatasetFieldValues(Datasets.java:1187)
dev_dataverse>  at edu.harvard.iq.dataverse.api.Datasets.processDatasetUpdate(Datasets.java:1077)
dev_dataverse>  at edu.harvard.iq.dataverse.api.Datasets.editVersionMetadata(Datasets.java:1053)
dev_dataverse>  at edu.harvard.iq.dataverse.api.Datasets$Proxy$_$$_WeldSubclass.editVersionMetadata(Unknown Source)
dev_dataverse>  at jdk.internal.reflect.GeneratedMethodAccessor411.invoke(Unknown Source)
dev_dataverse>  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
dev_dataverse>  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
dev_dataverse>  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
dev_dataverse>  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
dev_dataverse>  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
dev_dataverse>  at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
dev_dataverse>  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
dev_dataverse>  at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
dev_dataverse>  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
dev_dataverse>  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
dev_dataverse>  at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
dev_dataverse>  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
dev_dataverse>  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
dev_dataverse>  at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
dev_dataverse>  at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
dev_dataverse>  at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
dev_dataverse>  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
dev_dataverse>  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
dev_dataverse>  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
dev_dataverse>  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
dev_dataverse>  at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
dev_dataverse>  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
dev_dataverse>  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
dev_dataverse>  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
dev_dataverse>  at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1554)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
dev_dataverse>  at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
dev_dataverse>  at edu.harvard.iq.dataverse.api.ApiBlockingFilter.doFilter(ApiBlockingFilter.java:170)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
dev_dataverse>  at edu.harvard.iq.dataverse.api.ApiRouter.doFilter(ApiRouter.java:31)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
dev_dataverse>  at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:816)
dev_dataverse>  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:683)
dev_dataverse>  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:527)
dev_dataverse>  at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:497)
dev_dataverse>  at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:379)
dev_dataverse>  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:329)
dev_dataverse>  at edu.harvard.iq.dataverse.api.ApiRouter.doFilter(ApiRouter.java:35)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
dev_dataverse>  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
dev_dataverse>  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
dev_dataverse>  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:166)
dev_dataverse>  at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
dev_dataverse>  at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
dev_dataverse>  at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
dev_dataverse>  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
dev_dataverse>  at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
dev_dataverse>  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
dev_dataverse>  at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
dev_dataverse>  at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
dev_dataverse>  at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
dev_dataverse>  at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
dev_dataverse>  at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
dev_dataverse>  at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
dev_dataverse>  at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
dev_dataverse>  at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
dev_dataverse>  at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
dev_dataverse>  at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
dev_dataverse>  at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
dev_dataverse>  at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
dev_dataverse>  at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
dev_dataverse>  at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
dev_dataverse>  at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
dev_dataverse>  at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
dev_dataverse>  at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
dev_dataverse>  at java.base/java.lang.Thread.run(Unknown Source)
dev_dataverse> |#]
```

For example, in the standard metadata blocks, the field `journalArticleType` fulfills these criteria. So the error can be reproduced by activating the journals block and sending the following update to the API:

```
{
    "fields": [
        {
            "typeName": "journalArticleType",
            "value": "abstract"
        }
    ]
}
```

If I understand correctly, there is no open PR for this issue, right?
