### ISSUE TITLE
Spinning up Dataverse in Docker no longer works

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9749]
**What steps does it take to reproduce the issue?**

- Clone the repo
- Run `docker compose -f docker-compose-dev.yml up` as described at http://preview.guides.gdcc.io/en/develop/container/dev-usage.html
- After a minute or two, observe that Dataverse is not running. You'll see `dev_bootstrap         | Error: context deadline exceeded`. Here's the full log: [docker.txt](https://github.com/IQSS/dataverse/files/12240397/docker.txt)
 
The war file is not being deployed. From the log above:

```
dev_dataverse         | [#|2023-08-02T13:13:10.109+0000|INFO|Payara 5.2022.5|org.jboss.weld.Bootstrap|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990109;_LevelValue=800;|
dev_dataverse         |   WELD-000119: Not generating any bean definitions from org.omnifaces.cdi.converter.ConverterManager because of underlying class loading error: Type jakarta.enterprise.inject.spi.BeanManager not found.  If this is unexpected, enable DEBUG logging to see the full error.|#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.112+0000|INFO|Payara 5.2022.5|org.jboss.weld.Bootstrap|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990112;_LevelValue=800;|
dev_dataverse         |   WELD-000119: Not generating any bean definitions from org.omnifaces.cdi.BeanStorage because of underlying class loading error: Type jakarta.enterprise.context.spi.Contextual not found.  If this is unexpected, enable DEBUG logging to see the full error.|#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.117+0000|INFO|Payara 5.2022.5|org.jboss.weld.Bootstrap|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990117;_LevelValue=800;|
dev_dataverse         |   WELD-000119: Not generating any bean definitions from org.omnifaces.cdi.push.SocketPushContextProducer because of underlying class loading error: Type jakarta.enterprise.inject.spi.InjectionPoint not found.  If this is unexpected, enable DEBUG logging to see the full error.|#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.122+0000|INFO|Payara 5.2022.5|org.jboss.weld.Bootstrap|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990122;_LevelValue=800;|
dev_dataverse         |   WELD-000119: Not generating any bean definitions from org.omnifaces.component.output.GraphicImage$PropertyKeys because of underlying class loading error: Type jakarta.faces.component.html.HtmlGraphicImage not found.  If this is unexpected, enable DEBUG logging to see the full error.|#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.126+0000|INFO|Payara 5.2022.5|org.jboss.weld.Bootstrap|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990126;_LevelValue=800;|
dev_dataverse         |   WELD-000119: Not generating any bean definitions from org.omnifaces.cdi.viewscope.ViewScopeManager because of underlying class loading error: Type jakarta.enterprise.inject.spi.BeanManager not found.  If this is unexpected, enable DEBUG logging to see the full error.|#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.159+0000|INFO|Payara 5.2022.5|org.jboss.weld.Bootstrap|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990159;_LevelValue=800;|
dev_dataverse         |   WELD-000119: Not generating any bean definitions from org.omnifaces.resourcehandler.CombinedResourceInfo because of underlying class loading error: Type jakarta.faces.application.Resource not found.  If this is unexpected, enable DEBUG logging to see the full error.|#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.176+0000|SEVERE|Payara 5.2022.5|javax.enterprise.system.core|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990176;_LevelValue=1000;_MessageID=NCLS-CORE-00026;|
dev_dataverse         |   Exception during lifecycle processing
dev_dataverse         | org.glassfish.deployment.common.DeploymentException: CDI deployment failure:jakarta/faces/event/SystemEventListener -- jakarta/faces/event/SystemEventListener
dev_dataverse         | 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
dev_dataverse         | 	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
dev_dataverse         | 	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
dev_dataverse         | 	at org.glassfish.web.loader.WebappClassLoader.defineLoadedClass(WebappClassLoader.java:3529)
dev_dataverse         | 	at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1212)
dev_dataverse         | 	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1784)
dev_dataverse         | 	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1662)
dev_dataverse         | 	at java.base/java.lang.Class.getEnclosingMethod0(Native Method)
dev_dataverse         | 	at java.base/java.lang.Class.hasEnclosingMethodInfo(Unknown Source)
dev_dataverse         | 	at java.base/java.lang.Class.isLocalOrAnonymousClass(Unknown Source)
dev_dataverse         | 	at java.base/java.lang.Class.isAnonymousClass(Unknown Source)
dev_dataverse         | 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.internalLoadAnnotatedType(AnnotatedTypeLoader.java:92)
dev_dataverse         | 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:75)
dev_dataverse         | 	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:92)
dev_dataverse         | 	at org.jboss.weld.bootstrap.BeanDeployer.addLoadedClasses(BeanDeployer.java:142)
dev_dataverse         | 	at org.jboss.weld.bootstrap.BeanDeployment.createClasses(BeanDeployment.java:197)
dev_dataverse         | 	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:417)
dev_dataverse         | 	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:79)
dev_dataverse         | 	at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:520)
dev_dataverse         | 	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:434)
dev_dataverse         | 	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
dev_dataverse         | 	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:344)
dev_dataverse         | 	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:576)
dev_dataverse         | 	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:593)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
dev_dataverse         | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
dev_dataverse         | 	at java.base/javax.security.auth.Subject.doAs(Unknown Source)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
dev_dataverse         | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
dev_dataverse         | 	at java.base/javax.security.auth.Subject.doAs(Unknown Source)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1200(CommandRunnerImpl.java:120)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1869)
dev_dataverse         | 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
dev_dataverse         | 	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:183)
dev_dataverse         | 	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
dev_dataverse         | 	at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
dev_dataverse         | 	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:142)
dev_dataverse         | 	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:136)
dev_dataverse         | 	at com.sun.enterprise.v3.bootstrap.BootCommandService.doBootCommands(BootCommandService.java:81)
dev_dataverse         | 	at com.sun.enterprise.v3.bootstrap.BootCommandService.postConstruct(BootCommandService.java:91)
dev_dataverse         | 	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
dev_dataverse         | 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
dev_dataverse         | 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
dev_dataverse         | 	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
dev_dataverse         | 	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
dev_dataverse         | 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
dev_dataverse         | 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
dev_dataverse         | 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
dev_dataverse         | 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
dev_dataverse         | 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
dev_dataverse         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
dev_dataverse         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
dev_dataverse         | 	at java.base/java.lang.Thread.run(Unknown Source)
dev_dataverse         | |#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.178+0000|SEVERE|Payara 5.2022.5|javax.enterprise.system.core|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990178;_LevelValue=1000;|
dev_dataverse         |   Exception while loading the app|#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.179+0000|SEVERE|Payara 5.2022.5|javax.enterprise.web|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990179;_LevelValue=1000;_MessageID=AS-WEB-GLUE-00192;|
dev_dataverse         |   Undeployment failed for context |#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.209+0000|SEVERE|Payara 5.2022.5|javax.enterprise.system.core|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990209;_LevelValue=1000;|
dev_dataverse         |   Exception while loading the app : CDI deployment failure:jakarta/faces/event/SystemEventListener -- jakarta/faces/event/SystemEventListener|#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.222+0000|WARNING|Payara 5.2022.5|fish.payara.boot.runtime.BootCommand|_ThreadID=37;_ThreadName=RunLevelControllerThread-1690981964592;_TimeMillis=1690981990222;_LevelValue=900;|
dev_dataverse         |   Boot Command deploy failed PlainTextActionReporterFAILUREDescription: deploy AdminCommandError occurred during deployment: Exception while loading the app : CDI deployment failure:jakarta/faces/event/SystemEventListener -- jakarta/faces/event/SystemEventListener. Please see server.log for more details.
dev_dataverse         |     [name=dataverse
dev_dataverse         |  |#]
dev_dataverse         | 
dev_dataverse         | [#|2023-08-02T13:13:10.241+0000|INFO|Payara 5.2022.5|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1690981990241;_LevelValue=800;_MessageID=NCLS-CORE-00017;|
dev_dataverse         |   Payara Server  5.2022.5 #badassfish (492) startup time : Felix (5,979ms), startup services(26,594ms), total(32,573ms)|#]
```

It's also possible to reproduce the issue using GitHub Actions. For example: https://github.com/pdurbin/dataverse-api-test-runner/actions/runs/5738631301 shows a failure as of https://github.com/pdurbin/dataverse-api-test-runner/tree/1b5155a6b02c2b61684accfe75ec9fe618c45b26 . The files in play are:

- https://github.com/pdurbin/dataverse-api-test-runner/blob/1b5155a6b02c2b61684accfe75ec9fe618c45b26/.github/workflows/develop.yml
- https://github.com/pdurbin/dataverse-api-test-runner/blob/1b5155a6b02c2b61684accfe75ec9fe618c45b26/docker-compose-develop.yml

**Which version of Dataverse are you using?**

The develop branch as of 54fd71e

**Any related open or closed issues to this bug report?**

No, but I started a topic here: https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/Exception.20while.20loading.20the.20app

**Anything else?**

This was working very consistently from GitHub Actions all day yesterday. Then it suddenly started failing very consistently. 😞 

- 4:22pm working: https://github.com/pdurbin/dataverse-api-test-runner/actions/runs/5731302013/job/15531939818
- 6:16pm not working: https://github.com/pdurbin/dataverse-api-test-runner/actions/runs/5731823269/job/15535144343

What's weird about the "4:22pm working" run above is that it seems to be running the branch for #9737 (where we are adding the "query" type) instead of develop. I have no idea why. It shows this output:

```
 Expected: Type must be one of these values: [explore, configure, preview].
  Actual: Type must be one of these values: [explore, configure, preview, query].
```

Interestingly while `docker compose -f docker-compose-dev.yml up` doesn't work, `mvn -Pct clean package docker:run` does seem to work.

**Comment by pdurbin** [comment]
I just went to https://hub.docker.com/u/gdcc and noticed that gdcc/dataverse was updated 3 hours ago.

On my laptop, I deleted my old images with this:

`docker images | grep -i gdcc | awk '{print $3}' | while read i; do docker rmi $i; done`

Then I deleted the volumes, just in case:

`rm -rf docker-dev-volumes`

Then I tried to spin them up...

`docker compose -f docker-compose-dev.yml up`

... and it worked!

I also kicked off a couple GitHub Actions runs:

- https://github.com/pdurbin/dataverse-api-test-runner/actions/runs/5741393793
- https://github.com/IQSS/dataverse-sample-data/actions/runs/5741461156

**Comment by pdurbin** [comment]
https://github.com/pdurbin/dataverse-api-test-runner/actions/runs/5741393793 failed but with the error we expect until we merge https://github.com/IQSS/dataverse/pull/9685/commits/8efb96487d181f83726ac5a338a13692b1710850 into develop to fix an API test about harvesting.

https://github.com/IQSS/dataverse-sample-data/actions/runs/5741461156 passed. It doesn't run API tests.

So I guess it fixed itself. But now what? Why did this happen? How can we prevent this from happening again? Why did we see weird stuff from a branch (the query tool thing above)? Should we be testing these containers (automatically, I assume) before we push them?

Maybe we can talk about it at the next Containerization Working Group meeting: https://ct.gdcc.io

I'll go ahead and close this because it seems to be fixed. It fixed itself. 😓

**Comment by beepsoft** [comment]
Just for future reference: it must have been a problem with an incompatible base image. In this case one should build the base image based on the current Dataverse source version using:

```
mvn -Pct -f modules/container-base install
```

And then:

```
mvn -Pct clean package
mvn -Pct docker:run
```
