### ISSUE TITLE
File upload: Server log errors when click save

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#998]
[2014-10-24T17:35:45.047-0400] [glassfish 4.0] [WARNING] [] [javax.enterprise.web.core] [tid: _ThreadID=39 _ThreadName=jk-connector(1)] [timeMillis: 1414186545047] [levelValue: 900] [[
  Error invoking requestDestroyed method on ServletRequestListener org.jboss.weld.servlet.WeldListener
java.lang.NullPointerException
	at org.jboss.weld.context.AbstractBoundContext.deactivate(AbstractBoundContext.java:71)
	at org.jboss.weld.context.http.HttpRequestContextImpl.deactivate(HttpRequestContextImpl.java:70)
	at org.jboss.weld.servlet.WeldListener.requestDestroyed(WeldListener.java:154)
	at org.apache.catalina.core.StandardContext.fireRequestDestroyedEvent(StandardContext.java:5261)
	at org.apache.catalina.core.StandardHostValve.postInvoke(StandardHostValve.java:255)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:735)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:354)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:260)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:188)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:191)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:168)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:189)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:288)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:206)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:136)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:114)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:838)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:113)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:115)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:55)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:135)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:564)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:544)
	at java.lang.Thread.run(Thread.java:745)
]]

**Comment by esotiri** [comment]
Tested uploading image, STATA, SPSS and R file without any server log error. 

However I got this uploading the R file.  Refreshing the page shows file uploaded successfully.
 
![screen shot 2015-01-07 at 12 16 31 pm](https://cloud.githubusercontent.com/assets/1107614/5649920/e97cba00-9667-11e4-942e-9ed14de15139.png)

**Comment by esotiri** [comment]
Uploaded another R file without problem.
